export const biology_Part1 = [
  { id: 1, category: "생물", question: "생명체를 구성하는 가장 기본적인 구조적, 기능적 단위는?", options: ["조직", "기관", "세포", "개체"], answer: "세포", isCalc: false },
  { id: 2, category: "생물", question: "세포 내에서 호흡을 통해 에너지를 생성하는 세포 소기관은?", options: ["핵", "리보솜", "미토콘드리아", "엽록체"], answer: "미토콘드리아", isCalc: false },
  { id: 3, category: "생물", question: "식물 세포에만 존재하며 광합성을 하는 세포 소기관은?", options: ["세포벽", "액포", "엽록체", "리소좀"], answer: "엽록체", isCalc: false },
  { id: 4, category: "생물", question: "유전 정보를 담고 있는 DNA가 존재하는 세포 내 구조물은?", options: ["핵", "세포질", "세포막", "골지체"], answer: "핵", isCalc: false },
  { id: 5, category: "생물", question: "단백질을 합성하는 세포 소기관은?", options: ["리보솜", "소포체", "골지체", "액포"], answer: "리보솜", isCalc: false },
  { id: 6, category: "생물", question: "세포막의 주성분으로 인지질과 함께 막의 유동성을 결정하는 물질은?", options: ["탄수화물", "단백질", "핵산", "무기염류"], answer: "단백질", isCalc: false },
  { id: 7, category: "생물", question: "물질이 농도가 높은 곳에서 낮은 곳으로 퍼져나가는 현상은?", options: ["삼투", "능동 수송", "확산", "내포 작용"], answer: "확산", isCalc: false },
  { id: 8, category: "생물", question: "반투과성 막을 경계로 물이 농도가 낮은 곳에서 높은 곳으로 이동하는 현상은?", options: ["확산", "삼투", "세포 분열", "엔도사이토시스"], answer: "삼투", isCalc: false },
  { id: 9, category: "생물", question: "에너지를 소모하여 물질을 농도 기울기 역방향으로 이동시키는 것은?", options: ["확산", "촉진 확산", "능동 수송", "여과"], answer: "능동 수송", isCalc: false },
  { id: 10, category: "생물", question: "생체 내에서 화학 반응 속도를 빠르게 하는 단백질 성분의 물질은?", options: ["호르몬", "비타민", "효소", "항체"], answer: "효소", isCalc: false },
  { id: 11, category: "생물", question: "효소가 반응을 일으키는 특정 물질을 무엇이라 하는가?", options: ["생성물", "기질", "촉매", "억제제"], answer: "기질", isCalc: false },
  { id: 12, category: "생물", question: "세포 호흡의 첫 번째 단계로 세포질에서 일어나는 과정은?", options: ["크렙스 회로", "전자 전달계", "당분해 과정", "광인산화"], answer: "당분해 과정", isCalc: false },
  { id: 13, category: "생물", question: "세포 호흡의 결과 생성되어 에너지의 화폐 역할을 하는 물질은?", options: ["ADP", "ATP", "NADPH", "포도당"], answer: "ATP", isCalc: false },
  { id: 14, category: "생물", question: "산소가 없는 환경에서 일어나는 세포 호흡의 일종은?", options: ["유산소 호흡", "발효", "광합성", "동화 작용"], answer: "발효", isCalc: false },
  { id: 15, category: "생물", question: "광합성에서 빛 에너지를 흡수하는 색소는?", options: ["카로틴", "잔토필", "엽록소", "안토사이언"], answer: "엽록소", isCalc: false },
  { id: 16, category: "생물", question: "광합성의 결과 생성되는 주요 유기물은?", options: ["이산화 탄소", "산소", "포도당", "물"], answer: "포도당", isCalc: false },
  { id: 17, category: "생물", question: "세포 분열 전 DNA가 복제되어 두 배가 되는 시기는?", options: ["간기", "전기", "중기", "후기"], answer: "간기", isCalc: false },
  { id: 18, category: "생물", question: "체세포 분열에서 염색체가 세포 중앙에 배열되는 시기는?", options: ["전기", "중기", "후기", "말기"], answer: "중기", isCalc: false },
  { id: 19, category: "생물", question: "생식 세포(정자, 난자) 형성 시 일어나는 분열 방식은?", options: ["체세포 분열", "감수 분열", "이분법", "출아법"], answer: "감수 분열", isCalc: false },
  { id: 20, category: "생물", question: "DNA의 기본 단위로 인산, 당, 염기로 구성된 것은?", options: ["아미노산", "뉴클레오타이드", "지방산", "포도당"], answer: "뉴클레오타이드", isCalc: false },
  { id: 21, category: "생물", question: "DNA의 이중 나선 구조를 밝혀낸 과학자는?", options: ["멘델", "다윈", "왓슨과 크릭", "파스퇴르"], answer: "왓슨과 크릭", isCalc: false },
  { id: 22, category: "생물", question: "DNA의 유전 정보를 RNA로 복사하는 과정을 무엇이라 하는가?", options: ["복제", "전사", "번역", "돌연변이"], answer: "전사", isCalc: false },
  { id: 23, category: "생물", question: "RNA의 정보를 바탕으로 단백질을 합성하는 과정을 무엇이라 하는가?", options: ["전사", "번역", "복제", "조절"], answer: "번역", isCalc: false },
  { id: 24, category: "생물", question: "유전 법칙을 발견하여 유전학의 기초를 확립한 사람은?", options: ["멘델", "모건", "다윈", "람마르크"], answer: "멘델", isCalc: false },
  { id: 25, category: "생물", question: "한 쌍의 대립 유전자가 생식 세포 형성 시 분리되어 각각 다른 생식 세포로 들어간다는 법칙은?", options: ["우열의 원리", "분리의 법칙", "독립의 법칙", "유전자의 연쇄"], answer: "분리의 법칙", isCalc: false },
  { id: 26, category: "생물", question: "표현형으로 나타나는 우성 형질을 나타내는 유전자 구성은? (예: AA, Aa)", options: ["동형 접합", "이형 접합", "우성", "열성"], answer: "우성", isCalc: false },
  { id: 27, category: "생물", question: "성염색체에 있는 유전자에 의해 남녀 간 발현 빈도가 다른 유전은?", options: ["상염색체 유전", "성염색체 유전(반성 유전)", "다인자 유전", "중간 유전"], answer: "성염색체 유전(반성 유전)", isCalc: false },
  { id: 28, category: "생물", question: "사람의 ABO식 혈액형 유전에서 나타나는 유전 현상은?", options: ["중간 유전", "공우성", "반성 유전", "다인자 유전"], answer: "공우성", isCalc: false },
  { id: 29, category: "생물", question: "염색체 수나 구조의 이상으로 발생하는 질환은?", options: ["유전자 돌연변이", "염색체 돌연변이", "유전병", "감염병"], answer: "염색체 돌연변이", isCalc: false },
  { id: 30, category: "생물", question: "진화론의 핵심 원리인 '자연 선택설'을 주장한 사람은?", options: ["람마르크", "다윈", "멘델", "월리스"], answer: "다윈", isCalc: false },
  { id: 31, category: "생물", question: "생물이 환경에 적응하여 형질이 변하고 새로운 종으로 나뉘는 과정은?", options: ["변이", "진화", "적응", "대사"], answer: "진화", isCalc: false },
  { id: 32, category: "생물", question: "생물 분류의 기본 단위는?", options: ["계", "문", "강", "종"], answer: "종", isCalc: false },
  { id: 33, category: "생물", question: "세균처럼 핵막이 없는 세포를 가진 생물은?", options: ["진핵생물", "원핵생물", "바이러스", "균류"], answer: "원핵생물", isCalc: false },
  { id: 34, category: "생물", question: "세포벽이 키틴질로 구성되어 있으며 광합성을 하지 않는 생물은?", options: ["식물계", "동물계", "균계(곰팡이)", "원생생물계"], answer: "균계(곰팡이)", isCalc: false },
  { id: 35, category: "생물", question: "바이러스가 생물적 특징과 무생물적 특징 중 생물적 특징에 해당하는 것은?", options: ["세포 구조를 가진다", "물질대사를 한다", "유전 물질을 가지고 복제한다", "결정으로 존재한다"], answer: "유전 물질을 가지고 복제한다", isCalc: false },
  { id: 36, category: "생물", question: "식물의 뿌리에서 물을 흡수하는 주된 힘은?", options: ["뿌리압", "모세관 현상", "증산 작용", "확산"], answer: "증산 작용", isCalc: false },
  { id: 37, category: "생물", question: "식물에서 물과 무기 양분의 이동 통로는?", options: ["체관", "물관", "형성층", "피층"], answer: "물관", isCalc: false },
  { id: 38, category: "생물", question: "식물에서 광합성 산물(유기물)의 이동 통로는?", options: ["물관", "체관", "피층", "형성층"], answer: "체관", isCalc: false },
  { id: 39, category: "생물", question: "동물의 몸 안에서 혈액을 순환시켜 물질을 운반하는 기관은?", options: ["호흡 기관", "소화 기관", "순환 기관", "배설 기관"], answer: "순환 기관", isCalc: false },
  { id: 40, category: "생물", question: "혈액 중 산소를 운반하는 주요 세포는?", options: ["백혈구", "적혈구", "혈소판", "혈장"], answer: "적혈구", isCalc: false },
  { id: 41, category: "생물", question: "몸의 항상성을 유지하기 위해 호르몬을 분비하는 기관계는?", options: ["신경계", "내분비계", "소화계", "호흡계"], answer: "내분비계", isCalc: false },
  { id: 42, category: "생물", question: "신경계의 기본 구조적, 기능적 단위는?", options: ["뉴런", "뇌", "척수", "세포"], answer: "뉴런", isCalc: false },
  { id: 43, category: "생물", question: "외부 자극에 대해 방어 작용을 하는 림프구 중 항체를 생산하는 것은?", options: ["T 림프구", "B 림프구", "적혈구", "혈소판"], answer: "B 림프구", isCalc: false },
  { id: 44, category: "생물", question: "생태계에서 태양 에너지를 이용하여 유기물을 생산하는 생물은?", options: ["생산자", "소비자", "분해자", "포식자"], answer: "생산자", isCalc: false },
  { id: 45, category: "생물", question: "생태계에서 먹이 사슬의 최종 단계에 위치하며 유기물을 무기물로 분해하는 생물은?", options: ["생산자", "소비자", "분해자", "경쟁자"], answer: "분해자", isCalc: false },
  { id: 46, category: "생물", question: "개체군의 크기를 결정하는 요인 중 개체 수가 늘어나는 요인은?", options: ["사망률", "이출", "출생률", "경쟁"], answer: "출생률", isCalc: false },
  { id: 47, category: "생물", question: "서로 다른 종이 같은 자원을 두고 다투는 상호 작용은?", options: ["경쟁", "공생", "포식", "피식"], answer: "경쟁", isCalc: false },
  { id: 48, category: "생물", question: "생태계의 한 종이 사라져 먹이 그물 전체에 영향을 미치는 중요 종은?", options: ["핵심종", "우점종", "희귀종", "외래종"], answer: "핵심종", isCalc: false },
  { id: 49, category: "생물", question: "물질의 양을 나타내는 단위로 생물에서는 주로 질량을 사용하지만, 이 문제는 생물학적 농도 단위에 관한 것입니다. 용액 속에 용질의 양을 나타내는 것은?", options: ["kg", "m", "mol/L", "J"], answer: "mol/L", isCalc: true },
  { id: 50, category: "생물", question: "생물막을 통과하는 물질의 속도를 측정하는 실험에서, 온도가 올라가면 분자 운동이 활발해져 이동 속도가 ( ). 빈칸은?", options: ["느려진다", "빨라진다", "변함없다", "0이 된다"], answer: "빨라진다", isCalc: false }
];export const biology_Part2 = [
  { id: 51, category: "생물", question: "포도당이 세포 호흡을 통해 완전히 분해될 때 생성되는 최종 노폐물 두 가지는?", options: ["이산화 탄소와 물", "이산화 탄소와 산소", "물과 암모니아", "포도당과 물"], answer: "이산화 탄소와 물", isCalc: false },
  { id: 52, category: "생물", question: "단백질이 분해될 때 생성되며 간에서 요소로 전환되는 노폐물은?", options: ["이산화 탄소", "암모니아", "요산", "질산"], answer: "암모니아", isCalc: false },
  { id: 53, category: "생물", question: "콩팥의 기본 단위로 사구체, 보먼주머니, 세뇨관으로 구성된 것은?", options: ["뉴런", "네프론", "세포", "조직"], answer: "네프론", isCalc: false },
  { id: 54, category: "생물", question: "혈액이 사구체에서 보먼주머니로 이동하는 현상은?", options: ["여과", "재흡수", "분비", "확산"], answer: "여과", isCalc: false },
  { id: 55, category: "생물", question: "포도당이나 아미노산이 세뇨관에서 모세혈관으로 100% 돌아오는 과정은?", options: ["여과", "재흡수", "분비", "배설"], answer: "재흡수", isCalc: false },
  { id: 56, category: "생물", question: "심장에서 나가는 혈액이 흐르는 혈관은?", options: ["동맥", "정맥", "모세혈관", "림프관"], answer: "동맥", isCalc: false },
  { id: 57, category: "생물", question: "혈액이 역류하는 것을 막기 위해 정맥과 심장에 존재하는 구조는?", options: ["동맥판", "판막", "모세혈관망", "근육"], answer: "판막", isCalc: false },
  { id: 58, category: "생물", question: "항상성 조절의 중추로 체온, 혈당량 등을 조절하는 뇌 부위는?", options: ["대뇌", "소뇌", "간뇌", "연수"], answer: "간뇌", isCalc: false },
  { id: 59, category: "생물", question: "심장 박동, 호흡 운동 등 생명 유지와 직결된 자율 신경 중추는?", options: ["대뇌", "간뇌", "연수", "중간뇌"], answer: "연수", isCalc: false },
  { id: 60, category: "생물", question: "뉴런에서 자극을 수용하는 부분은?", options: ["축삭 돌기", "가지 돌기", "신경 세포체", "시냅스"], answer: "가지 돌기", isCalc: false },
  { id: 61, category: "생물", question: "말이집 뉴런에서 흥분이 도약하며 빠르게 전달되는 현상은?", options: ["도약 전도", "시냅스 전달", "탈분극", "재분극"], answer: "도약 전도", isCalc: false },
  { id: 62, category: "생물", question: "시냅스 소포에서 방출되어 다음 뉴런으로 신호를 전달하는 물질은?", options: ["호르몬", "신경 전달 물질", "효소", "항체"], answer: "신경 전달 물질", isCalc: false },
  { id: 63, category: "생물", question: "긴박한 상황에서 심장 박동을 촉진하고 동공을 확장시키는 신경은?", options: ["교감 신경", "부교감 신경", "감각 신경", "운동 신경"], answer: "교감 신경", isCalc: false },
  { id: 64, category: "생물", question: "혈당량을 낮추는 역할을 하는 이자의 호르몬은?", options: ["글루카곤", "인슐린", "아드레날린", "티록신"], answer: "인슐린", isCalc: false },
  { id: 65, category: "생물", question: "갑상샘 호르몬인 티록신의 성분이며 부족 시 갑상샘종을 유발하는 원소는?", options: ["철", "칼슘", "아이오딘", "마그네슘"], answer: "아이오딘", isCalc: false },
  { id: 66, category: "생물", question: "항이뇨 호르몬(ADH)은 콩팥에서 무엇의 재흡수를 촉진하는가?", options: ["포도당", "물", "나트륨", "요소"], answer: "물", isCalc: false },
  { id: 67, category: "생물", question: "병원균이 몸에 침입했을 때 백혈구가 균을 잡아먹는 작용은?", options: ["염증 반응", "식균 작용", "항체 반응", "중화 반응"], answer: "식균 작용", isCalc: false },
  { id: 68, category: "생물", question: "특정 항원을 기억했다가 재침입 시 빠르게 항체를 생산하는 세포는?", options: ["보조 T 세포", "기억 세포", "형질 세포", "비만 세포"], answer: "기억 세포", isCalc: false },
  { id: 69, category: "생물", question: "인위적으로 약화시킨 항원을 주입하여 면역을 형성하는 방법은?", options: ["항생제 처방", "백신 접종", "혈청 주사", "수혈"], answer: "백신 접종", isCalc: false },
  { id: 70, category: "생물", question: "자신의 몸 구성을 항원으로 인식하여 공격하는 질환은?", options: ["알레르기", "자가 면역 질환", "결핍증", "감염병"], answer: "자가 면역 질환", isCalc: false },
  { id: 71, category: "생물", question: "독립된 두 쌍의 형질이 유전될 때 서로 영향을 주지 않는다는 법칙은?", options: ["분리의 법칙", "독립의 법칙", "우열의 원리", "연관 유전"], answer: "독립의 법칙", isCalc: false },
  { id: 72, category: "생물", question: "사람의 피부색 유전처럼 여러 쌍의 유전자가 관여하는 유전 방식은?", options: ["단일 인자 유전", "다인자 유전", "복대립 유전", "반성 유전"], answer: "다인자 유전", isCalc: false },
  { id: 73, category: "생물", question: "남성에게만 나타나며 Y 염색체에 유전자가 있는 유전 현상은?", options: ["반성 유전", "한성 유전", "중간 유전", "종성 유전"], answer: "한성 유전", isCalc: false },
  { id: 74, category: "생물", question: "21번 염색체가 3개여서 발생하는 유전병은?", options: ["터너 증후군", "클라인펠터 증후군", "다운 증후군", "묘성 증후군"], answer: "다운 증후군", isCalc: false },
  { id: 75, category: "생물", question: "DNA 복제 시 한쪽 가닥을 바탕으로 새로운 가닥이 만들어지는 방식은?", options: ["보존적 복제", "반보존적 복제", "분산적 복제", "비보존적 복제"], answer: "반보존적 복제", isCalc: false },
  { id: 76, category: "생물", question: "RNA에서 티민(T) 대신 들어있는 염기는?", options: ["아데닌", "구아닌", "사이토신", "우라실"], answer: "우라실", isCalc: false },
  { id: 77, category: "생물", question: "하나의 아미노산을 지정하는 3개의 염기 조합을 무엇이라 하는가?", options: ["코돈", "유전자", "인트론", "엑손"], answer: "코돈", isCalc: false },
  { id: 78, category: "생물", question: "생물의 화석이 진화의 증거가 될 때, 오래된 지층일수록 어떤 생물이 발견되는가?", options: ["복잡한 생물", "간단하고 하등한 생물", "현대 생물", "육상 생물"], answer: "간단하고 하등한 생물", isCalc: false },
  { id: 79, category: "생물", question: "겉모양과 기능은 다르지만 발생 기원이 같아 뼈 구조가 유사한 기관은?", options: ["상동 기관", "상사 기관", "흔적 기관", "퇴화 기관"], answer: "상동 기관", isCalc: false },
  { id: 80, category: "생물", question: "개체군 내에서 먹이, 공간 등을 차지하기 위해 순위를 정하는 행동은?", options: ["텃세", "순위제", "리더제", "사회 생활"], answer: "순위제", isCalc: false },
  { id: 81, category: "생물", question: "버섯이나 곰팡이는 생태계의 역할 중 어디에 해당하는가?", options: ["생산자", "소비자", "분해자", "매개자"], answer: "분해자", isCalc: false },
  { id: 82, category: "생물", question: "에너지 효율은 상위 영양 단계로 갈수록 어떻게 되는 경향이 있는가?", options: ["감소한다", "증가한다", "일정하다", "0이 된다"], answer: "증가한다", isCalc: true },
  { id: 83, category: "생물", question: "대기 중의 질소를 생물이 이용할 수 있는 형태로 바꾸는 과정은?", options: ["질소 고정", "탈질산화", "광합성", "호흡"], answer: "질소 고정", isCalc: false },
  { id: 84, category: "생물", question: "지구 온난화로 인해 생태계의 종 다양성이 ( ). 빈칸은?", options: ["증가한다", "감소한다", "유지된다", "회복된다"], answer: "감소한다", isCalc: false },
  { id: 85, category: "생물", question: "인슐린을 대량 생산하기 위해 사용하는 생명 공학 기술은?", options: ["세포 융합", "유전자 재조합", "핵 이식", "조직 배양"], answer: "유전자 재조합", isCalc: false },
  { id: 86, category: "생물", question: "동일한 유전 정보를 가진 개체를 복제하는 기술은?", options: ["세포 융합", "핵 이식", "PCR", "전기 영동"], answer: "핵 이식", isCalc: false },
  { id: 87, category: "생물", question: "아밀레이스가 녹말을 엿당으로 분해하는 소화 기관은?", options: ["위", "입", "소장", "대장"], answer: "입", isCalc: false },
  { id: 88, category: "생물", question: "위에서 분비되며 단백질 분해 효소인 펩신의 활성을 돕는 물질은?", options: ["담즙산", "염산", "인슐린", "뮤신"], answer: "염산", isCalc: false },
  { id: 89, category: "생물", question: "지방의 소화를 돕기 위해 간에서 생성되어 쓸개에 저장되는 액체는?", options: ["이자액", "위액", "쓸개즙", "장액"], answer: "쓸개즙", isCalc: false },
  { id: 90, category: "생물", question: "소장 내벽의 구조로 영양소의 흡수 면적을 넓혀주는 것은?", options: ["융털", "주름", "편막", "세뇨관"], answer: "융털", isCalc: false },
  { id: 91, category: "생물", question: "폐포와 모세혈관 사이에서 기체 교환이 일어나는 원리는?", options: ["확산", "삼투", "능동 수송", "여과"], answer: "확산", isCalc: false },
  { id: 92, category: "생물", question: "혈소판이 부족할 때 나타나는 주요 증상은?", options: ["빈혈", "면역 저하", "혈액 응고 지연", "저혈압"], answer: "혈액 응고 지연", isCalc: false },
  { id: 93, category: "생물", question: "항상성 조절 방식 중 결과가 원인을 억제하여 상태를 유지하는 방식은?", options: ["양성 피드백", "음성 피드백", "길항 작용", "촉진 작용"], answer: "음성 피드백", isCalc: false },
  { id: 94, category: "생물", question: "무릎 반사의 조절 중추는?", options: ["대뇌", "척수", "연수", "소뇌"], answer: "척수", isCalc: false },
  { id: 95, category: "생물", question: "DNA 이중 나선에서 아데닌(A)은 항상 누구와 결합하는가?", options: ["구아닌", "사이토신", "티민", "우라실"], answer: "티민", isCalc: false },
  { id: 96, category: "생물", question: "인간의 염색체 수는 총 몇 개인가?", options: ["23개", "44개", "46개", "48개"], answer: "46개", isCalc: true },
  { id: 97, category: "생물", question: "생물체 내 수분 함량이 가장 높은 물질은?", options: ["단백질", "지방", "물", "무기염류"], answer: "물", isCalc: false },
  { id: 98, category: "생물", question: "심장 마비 환자에게 사용하는 자동 심장 충격기(AED)와 관련된 기관계는?", options: ["호흡계", "순환계", "신경계", "배설계"], answer: "순환계", isCalc: false },
  { id: 99, category: "생물", question: "식물의 광합성 속도에 영향을 주는 요인이 아닌 것은?", options: ["빛의 세기", "이산화 탄소 농도", "온도", "토양의 깊이"], answer: "토양의 깊이", isCalc: false },
  { id: 100, category: "생물", question: "유전자 변형 생물을 뜻하는 용어는?", options: ["GOP", "GMO", "GPS", "GNP"], answer: "GMO", isCalc: false }
];export const biology_Part3 = [
  { id: 101, category: "생물", question: "세포설의 내용 중 모든 생물은 ( )로 이루어져 있다는 것이 있다. 빈칸은?", options: ["원소", "세포", "단백질", "유전자"], answer: "세포", isCalc: false },
  { id: 102, category: "생물", question: "원핵세포와 진핵세포의 가장 큰 차이점은 무엇의 유무인가?", options: ["세포막", "세포벽", "핵막", "리보솜"], answer: "핵막", isCalc: false },
  { id: 103, category: "생물", question: "단백질의 가공 및 운반에 관여하며 주머니 모양이 겹쳐진 소기관은?", options: ["골지체", "미토콘드리아", "리소좀", "중심체"], answer: "골지체", isCalc: false },
  { id: 104, category: "생물", question: "세포 내 가수 분해 효소를 포함하여 노폐물을 분해하는 주머니는?", options: ["액포", "리소좀", "엽록체", "리보솜"], answer: "리소좀", isCalc: false },
  { id: 105, category: "생물", question: "세포막을 통한 물질 이동 중 운반체 단백질을 이용하지만 에너지는 쓰지 않는 방식은?", options: ["단순 확산", "촉진 확산", "능동 수송", "삼투"], answer: "촉진 확산", isCalc: false },
  { id: 106, category: "생물", question: "식물 세포를 고장액에 넣었을 때 세포막이 세포벽에서 분리되는 현상은?", options: ["용혈 현상", "원형질 분리", "팽윤 상태", "수축"], answer: "원형질 분리", isCalc: false },
  { id: 107, category: "생물", question: "효소의 주성분은 무엇인가?", options: ["탄수화물", "단백질", "지방", "비타민"], answer: "단백질", isCalc: false },
  { id: 108, category: "생물", question: "효소가 반응을 촉진하는 이유는 ( ) 에너지를 낮추기 때문이다. 빈칸은?", options: ["운동", "위치", "활성화", "열"], answer: "활성화", isCalc: false },
  { id: 109, category: "생물", question: "ATP가 ADP와 무기 인산으로 분해될 때 에너지가 ( ). 빈칸은?", options: ["흡수된다", "방출된다", "소멸한다", "생성되지 않는다"], answer: "방출된다", isCalc: false },
  { id: 110, category: "생물", question: "포도당 한 분자가 유산소 호흡을 통해 생성하는 ATP의 최대 개수는 대략 몇 개인가?", options: ["2개", "32~38개", "100개", "1000개"], answer: "32~38개", isCalc: true },
  { id: 111, category: "생물", question: "근육 세포에서 산소가 부족할 때 일어나는 발효는?", options: ["알코올 발효", "젖산 발효", "아세트산 발효", "부패"], answer: "젖산 발효", isCalc: false },
  { id: 112, category: "생물", question: "광합성의 명반응이 일어나는 엽록체 내의 장소는?", options: ["스트로마", "틸라코이드(그라나)", "외막", "내막"], answer: "틸라코이드(그라나)", isCalc: false },
  { id: 113, category: "생물", question: "광합성 중 이산화 탄소를 이용하여 포도당을 합성하는 과정은?", options: ["명반응", "캘빈 회로(암반응)", "전자 전달계", "TCA 회로"], answer: "캘빈 회로(암반응)", isCalc: false },
  { id: 114, category: "생물", question: "염색체를 구성하는 주요 두 성분은?", options: ["DNA와 단백질", "RNA와 단백질", "DNA와 지질", "단백질과 탄수화물"], answer: "DNA와 단백질", isCalc: false },
  { id: 115, category: "생물", question: "모양과 크기가 같아 쌍을 이루는 염색체를 무엇이라 하는가?", options: ["2가 염색체", "상동 염색체", "염색 분체", "성염색체"], answer: "상동 염색체", isCalc: false },
  { id: 116, category: "생물", question: "암세포의 특징 중 하나는 세포 분열 조절 기능이 ( ) 것이다. 빈칸은?", options: ["강화된", "상실된", "정상인", "느려진"], answer: "상실된", isCalc: false },
  { id: 117, category: "생물", question: "감수 분열 1분기 전기에 상동 염색체가 접합하여 형성된 것은?", options: ["염색 분체", "2가 염색체", "핵", "인"], answer: "2가 염색체", isCalc: false },
  { id: 118, category: "생물", question: "감수 분열 결과 생성된 딸세포의 염색체 수는 모세포의 몇 배인가?", options: ["1배", "2배", "0.5배", "4배"], answer: "0.5배", isCalc: true },
  { id: 119, category: "생물", question: "DNA 복제 시 원래 가닥과 상보적으로 결합하는 효소는?", options: ["DNA 중합 효소", "RNA 중합 효소", "제한 효소", "연결 효소"], answer: "DNA 중합 효소", isCalc: false },
  { id: 120, category: "생물", question: "단백질 합성 장소인 리보솜으로 유전 정보를 전달하는 RNA는?", options: ["mRNA", "tRNA", "rRNA", "snRNA"], answer: "mRNA", isCalc: false },
  { id: 121, category: "생물", question: "tRNA가 가지고 있으며 코돈과 상보적으로 결합하는 3개의 염기는?", options: ["코돈", "안티코돈", "인트론", "엑손"], answer: "안티코돈", isCalc: false },
  { id: 122, category: "생물", question: "멘델의 유전 실험에서 사용된 생물은?", options: ["초파리", "완두", "옥수수", "생쥐"], answer: "완두", isCalc: false },
  { id: 123, category: "생물", question: "분꽃의 꽃잎 색깔 유전처럼 우열 관계가 불분명하여 중간 형질이 나타나는 유전은?", options: ["중간 유전", "복대립 유전", "다인자 유전", "반성 유전"], answer: "중간 유전", isCalc: false },
  { id: 124, category: "생물", question: "적록 색맹 유전자는 어느 염색체에 존재하는가?", options: ["상염색체", "X 염색체", "Y 염색체", "미토콘드리아 DNA"], answer: "X 염색체", isCalc: false },
  { id: 125, category: "생물", question: "하나의 형질에 3개 이상의 대립 유전자가 관여하는 유전 방식은?", options: ["다인자 유전", "복대립 유전", "중간 유전", "연관 유전"], answer: "복대립 유전", isCalc: false },
  { id: 126, category: "생물", question: "돌연변이가 자손에게 유전되려면 어떤 세포에서 일어나야 하는가?", options: ["체세포", "생식 세포", "신경 세포", "근육 세포"], answer: "생식 세포", isCalc: false },
  { id: 127, category: "생물", question: "종의 기원을 쓴 다윈이 진화의 주요 원동력으로 본 것은?", options: ["용불용설", "자연 선택", "격리", "돌연변이"], answer: "자연 선택", isCalc: false },
  { id: 128, category: "생물", question: "서로 다른 생물이 유사한 환경에 적응하여 외형이 비슷해지는 현상은?", options: ["수렴 진화", "산출 진화", "공진화", "평행 진화"], answer: "수렴 진화", isCalc: false },
  { id: 129, category: "생물", question: "생물 분류 체계 중 가장 상위 단계는? (3역 체계 기준)", options: ["계", "문", "역", "강"], answer: "역", isCalc: false },
  { id: 130, category: "생물", question: "세균(Bacteria)과 고세균(Archaea)의 공통점은?", options: ["원핵생물이다", "진핵생물이다", "다세포 생물이다", "광합성을 한다"], answer: "원핵생물이다", isCalc: false },
  { id: 131, category: "생물", question: "항생제인 페니실린은 어떤 생물에서 처음 발견되었는가?", options: ["세균", "푸른곰팡이", "바이러스", "이끼"], answer: "푸른곰팡이", isCalc: false },
  { id: 132, category: "생물", question: "식물의 기공을 조절하여 증산 작용을 조절하는 세포는?", options: ["표피 세포", "공변 세포", "울타리 조직", "해면 조직"], answer: "공변 세포", isCalc: false },
  { id: 133, category: "생물", question: "질소 비료의 주성분이며 식물 성장에 필수적인 원소는?", options: ["탄소", "질소", "아이오딘", "나트륨"], answer: "질소", isCalc: false },
  { id: 134, category: "생물", question: "사람의 소화 기관 중 수분을 주로 흡수하는 곳은?", options: ["위", "소장", "대장", "식도"], answer: "대장", isCalc: false },
  { id: 135, category: "생물", question: "혈장 속에 존재하며 면역 반응에서 항체 역할을 하는 단백질은?", options: ["알부민", "감마 글로불린", "피브리노겐", "헤모글로빈"], answer: "감마 글로불린", isCalc: false },
  { id: 136, category: "생물", question: "혈압을 측정할 때 주로 사용하는 수치는 수축기 혈압과 ( ) 혈압이다.", options: ["이완기", "평균", "모세관", "맥압"], answer: "이완기", isCalc: false },
  { id: 137, category: "생물", question: "자극을 전달하는 뉴런의 막전위가 급격히 상승하는 현상은?", options: ["분극", "탈분극", "재분극", "과분극"], answer: "탈분극", isCalc: false },
  { id: 138, category: "생물", question: "뇌의 좌우 반구를 연결하는 신경 섬유 다발은?", options: ["뇌교", "뇌량", "시상", "시상하부"], answer: "뇌량", isCalc: false },
  { id: 139, category: "생물", question: "성장 호르몬이 과다 분비될 때 나타나는 증상은?", options: ["소인증", "거인증(말단 비대증)", "당뇨병", "점액 부종"], answer: "거인증(말단 비대증)", isCalc: false },
  { id: 140, category: "생물", question: "혈당 조절에서 인슐린과 반대 작용(길항 작용)을 하는 호르몬은?", options: ["글루카곤", "티록신", "옥시토신", "프로락틴"], answer: "글루카곤", isCalc: false },
  { id: 141, category: "생물", question: "외부 독소나 병원체에 대항하기 위해 혈액 속에 만들어지는 단백질은?", options: ["항원", "항체", "보체", "인터페론"], answer: "항체", isCalc: false },
  { id: 142, category: "생물", question: "에이즈(AIDS)를 일으키는 바이러스의 이름은?", options: ["HPV", "HIV", "HBV", "HSV"], answer: "HIV", isCalc: false },
  { id: 143, category: "생물", question: "생태계에서 비생물적 요인(환경)이 생물에게 영향을 주는 것은?", options: ["작용", "반작용", "상호 작용", "적응"], answer: "작용", isCalc: false },
  { id: 144, category: "생물", question: "군집 내에서 가장 수가 많거나 점유 면적이 넓은 종은?", options: ["핵심종", "우점종", "지표종", "희귀종"], answer: "우점종", isCalc: false },
  { id: 145, category: "생물", question: "생태계 평형을 유지하는 먹이 관계의 복잡한 그물망은?", options: ["먹이 사슬", "먹이 그물", "생태 피라미드", "영양 단계"], answer: "먹이 그물", isCalc: false },
  { id: 146, category: "생물", question: "특정 지역에만 서식하는 종을 보존해야 하는 이유는 무엇을 높이기 위함인가?", options: ["개체수", "종 다양성", "먹이 경쟁", "이동 속도"], answer: "종 다양성", isCalc: false },
  { id: 147, category: "생물", question: "PCR 기술에서 DNA를 대량으로 증폭하기 위해 필요한 효소는?", options: ["열저항성 DNA 중합 효소", "제한 효소", "라이게이스", "아밀레이스"], answer: "열저항성 DNA 중합 효소", isCalc: false },
  { id: 148, category: "생물", question: "생쥐의 배아 줄기 세포를 이용해 특정 유전자를 제거한 쥐는?", options: ["트랜스제닉 쥐", "녹아웃 쥐", "복제 쥐", "돌연변이 쥐"], answer: "녹아웃 쥐", isCalc: false },
  { id: 149, category: "생물", question: "세포 호흡 과정 중 미토콘드리아 기질에서 일어나는 회로는?", options: ["캘빈 회로", "TCA 회로(크렙스 회로)", "당분해 회로", "오르니틴 회로"], answer: "TCA 회로(크렙스 회로)", isCalc: false },
  { id: 150, category: "생물", question: "DNA 칩을 이용해 수만 개의 유전자 발현 양상을 한꺼번에 분석하는 분야는?", options: ["유전체학(Genomics)", "단백질체학", "세포학", "분류학"], answer: "유전체학(Genomics)", isCalc: false }
];export const biology_Part4 = [
  { id: 151, category: "생물", question: "염색체 비분리 현상이 제1감수분열에서 일어날 경우, 생성된 4개의 생식 세포 중 정상인 것은?", options: ["0개", "1개", "2개", "4개"], answer: "0개", isCalc: true },
  { id: 152, category: "생물", question: "세포 주기 중 DNA 복제가 일어나는 시기는?", options: ["G1기", "S기", "G2기", "M기"], answer: "S기", isCalc: false },
  { id: 153, category: "생물", question: "심장 박동을 조절하는 자율 신경 중 박동을 느리게 하는 것은?", options: ["교감 신경", "부교감 신경", "척수 신경", "감각 신경"], answer: "부교감 신경", isCalc: false },
  { id: 154, category: "생물", question: "근육 수축의 에너지원으로 직접 사용되는 물질은?", options: ["포도당", "글리코젠", "ATP", "크레아틴"], answer: "ATP", isCalc: false },
  { id: 155, category: "생물", question: "활주설에 따르면 근육 수축 시 길이가 줄어드는 구간은?", options: ["A대", "I대", "마이오신 필라멘트", "액틴 필라멘트"], answer: "I대", isCalc: false },
  { id: 156, category: "생물", question: "혈장 삼투압이 높을 때 분비되어 수분 재흡수를 촉진하는 호르몬은?", options: ["인슐린", "항이뇨 호르몬(ADH)", "옥시토신", "에피네프린"], answer: "항이뇨 호르몬(ADH)", isCalc: false },
  { id: 157, category: "생물", question: "신경 세포에서 나트륨-칼륨 펌프가 사용하는 에너지는?", options: ["열에너지", "ATP", "빛에너지", "위치에너지"], answer: "ATP", isCalc: false },
  { id: 158, category: "생물", question: "눈에 들어오는 빛의 양을 조절하는 구조는?", options: ["수정체", "홍채", "망막", "각막"], answer: "홍채", isCalc: false },
  { id: 159, category: "생물", question: "소리의 진동을 전기 신호로 바꾸는 청각 세포가 있는 곳은?", options: ["고막", "반고리관", "달팽이관", "귀인두관"], answer: "달팽이관", isCalc: false },
  { id: 160, category: "생물", question: "척추동물의 뇌 중 평형 감각과 정교한 운동 조절을 담당하는 곳은?", options: ["대뇌", "소뇌", "간뇌", "연수"], answer: "소뇌", isCalc: false },
  { id: 161, category: "생물", question: "산소가 충분할 때 미토콘드리아 내부로 들어가는 당분해 산물은?", options: ["젖산", "에탄올", "피루브산", "아세틸 CoA"], answer: "피루브산", isCalc: false },
  { id: 162, category: "생물", question: "세포 호흡의 전자 전달계에서 최종 전자 수용체 역할을 하는 분자는?", options: ["CO₂", "H₂O", "O₂", "NAD⁺"], answer: "O₂", isCalc: false },
  { id: 163, category: "생물", question: "식물의 광합성 명반응에서 물의 광분해 결과 방출되는 기체는?", options: ["CO₂", "O₂", "H₂", "N₂"], answer: "O₂", isCalc: false },
  { id: 164, category: "생물", question: "캘빈 회로에서 이산화 탄소를 고정하는 데 관여하는 효소는?", options: ["아밀레이스", "루비스코(Rubisco)", "펩신", "카탈레이스"], answer: "루비스코(Rubisco)", isCalc: false },
  { id: 165, category: "생물", question: "세포막을 경계로 이온의 농도 차이에 의해 형성되는 전위는?", options: ["막전위", "화학 전위", "중력 전위", "삼투압"], answer: "막전위", isCalc: false },
  { id: 166, category: "생물", question: "흥분의 전달 방향은 축삭 돌기 말단에서 다음 뉴런의 ( ) 방향이다.", options: ["가지 돌기", "축삭 돌기", "핵", "말이집"], answer: "가지 돌기", isCalc: false },
  { id: 167, category: "생물", question: "길항 작용을 통해 심장 박동을 조절하는 두 신경은?", options: ["교감과 부교감", "감각과 운동", "뇌와 척수", "체성과 자율"], answer: "교감과 부교감", isCalc: false },
  { id: 168, category: "생물", question: "정상인의 경우 포도당이 오줌에 섞여 나오지 않는 이유는?", options: ["여과되지 않아서", "100% 재흡수되어서", "전부 분비되어서", "방광에서 분해되어서"], answer: "100% 재흡수되어서", isCalc: false },
  { id: 169, category: "생물", question: "혈중 칼슘 농도가 낮을 때 부갑상샘에서 분비되는 호르몬은?", options: ["칼시토닌", "파라토르몬", "티록신", "코르티코이드"], answer: "파라토르몬", isCalc: false },
  { id: 170, category: "생물", question: "병원체에 감염된 세포를 직접 공격하여 파괴하는 세포는?", options: ["B 림프구", "보조 T 림프구", "세포 독성 T 림프구", "혈장 세포"], answer: "세포 독성 T 림프구", isCalc: false },
  { id: 171, category: "생물", question: "알레르기 반응 시 분비되어 혈관 확장 및 가려움을 유발하는 물질은?", options: ["항체", "히스타민", "인슐린", "헤모글로빈"], answer: "히스타민", isCalc: false },
  { id: 172, category: "생물", question: "부모의 혈액형이 AB형과 O형일 때, 자녀에게서 나올 수 없는 혈액형은?", options: ["A형", "B형", "AB형", "모두 가능"], answer: "AB형", isCalc: true },
  { id: 173, category: "생물", question: "생물 종의 다양성을 유지하기 위한 가장 효과적인 방법은?", options: ["서식지 보존", "외래종 도입", "개체수 인위적 조절", "사냥 허가"], answer: "서식지 보존", isCalc: false },
  { id: 174, category: "생물", question: "군집의 천이 과정 중 가장 마지막 단계의 안정된 상태는?", options: ["개척자", "초원", "관목림", "극상"], answer: "극상", isCalc: false },
  { id: 175, category: "생물", question: "질소 순환 과정 중 암모늄 이온이 질산 이온으로 변하는 과정은?", options: ["질소 고정", "질산화 작용", "탈질산화 작용", "질소 동화 작용"], answer: "질산화 작용", isCalc: false },
  { id: 176, category: "생물", question: "생물 농축 현상이 일어나는 주된 이유는?", options: ["배설이 잘 안 되어서", "분해가 빨라서", "독성이 없어서", "에너지가 많아서"], answer: "배설이 잘 안 되어서", isCalc: false },
  { id: 177, category: "생물", question: "제한 효소로 자른 DNA 조각을 연결해주는 효소는?", options: ["중합 효소", "연결 효소(Ligase)", "분해 효소", "산화 효소"], answer: "연결 효소(Ligase)", isCalc: false },
  { id: 178, category: "생물", question: "세포가 스스로 죽음을 택하여 신체 형성을 조절하는 현상은?", options: ["세포 분열", "세포 사멸(Apoptosis)", "괴사", "분화"], answer: "세포 사멸(Apoptosis)", isCalc: false },
  { id: 179, category: "생물", question: "포유류의 적혈구가 성숙 과정에서 핵을 잃는 이유는?", options: ["수명 연장", "산소 운반 효율 증대", "세포 분열 촉진", "에너지 절약"], answer: "산소 운반 효율 증대", isCalc: false },
  { id: 180, category: "생물", question: "생체 내 단백질 합성이 일어나는 구체적인 장소는?", options: ["핵 속", "리보솜", "미토콘드리아 외막", "세포벽"], answer: "리보솜", isCalc: false },
  { id: 181, category: "생물", question: "염색체의 말단 부분으로 세포 분열이 반복될수록 짧아지는 구간은?", options: ["동원체", "텔로미어", "뉴클레오솜", "히스톤"], answer: "텔로미어", isCalc: false },
  { id: 182, category: "생물", question: "식물의 굴광성에 관여하며 줄기 끝에서 생성되는 호르몬은?", options: ["지베렐린", "옥신", "시토키닌", "에틸렌"], answer: "옥신", isCalc: false },
  { id: 183, category: "생물", question: "과일을 익게 하는 기체 상태의 식물 호르몬은?", options: ["옥신", "에틸렌", "아브시스산", "지베렐린"], answer: "에틸렌", isCalc: false },
  { id: 184, category: "생물", question: "사람의 뇌 중 시각 정보를 일차적으로 처리하는 부위는?", options: ["전두엽", "측두엽", "후두엽", "두정엽"], answer: "후두엽", isCalc: false },
  { id: 185, category: "생물", question: "세포막의 인지질 이중층에서 소수성 부분은 어디를 향하는가?", options: ["안쪽", "바깥쪽", "양쪽 모두", "무작위"], answer: "안쪽", isCalc: false },
  { id: 186, category: "생물", question: "세균의 세포벽 성분은?", options: ["셀룰로오스", "키틴", "펩티도글리칸", "글리코젠"], answer: "펩티도글리칸", isCalc: false },
  { id: 187, category: "생물", question: "ATP 한 분자가 ADP로 될 때 방출되는 에너지는 약 얼마인가?", options: ["3.4 kcal/mol", "7.3 kcal/mol", "10.5 kcal/mol", "20 kcal/mol"], answer: "7.3 kcal/mol", isCalc: true },
  { id: 188, category: "생물", question: "효모가 무산소 상태에서 당을 분해하여 에탄올을 만드는 과정은?", options: ["젖산 발효", "알코올 발효", "산소 호흡", "동화 작용"], answer: "알코올 발효", isCalc: false },
  { id: 189, category: "생물", question: "유전자 조작 시 원하는 유전자를 운반하는 DNA를 무엇이라 하는가?", options: ["벡터(Vector)", "프라이머", "프로브", "코돈"], answer: "벡터(Vector)", isCalc: false },
  { id: 190, category: "생물", question: "사람의 정자 형성 과정에서 제1정모세포 1개가 만드는 정자의 수는?", options: ["1개", "2개", "4개", "8개"], answer: "4개", isCalc: true },
  { id: 191, category: "생물", question: "혈소판이 파괴되면서 방출되어 혈액 응고를 시작하는 효소는?", options: ["트롬빈", "트롬보카이네이스", "피브리노겐", "알부민"], answer: "트롬보카이네이스", isCalc: false },
  { id: 192, category: "생물", question: "산소가 부족할 때 근육에 쌓여 피로를 유발하는 물질은?", options: ["피루브산", "젖산", "이산화 탄소", "요소"], answer: "젖산", isCalc: false },
  { id: 193, category: "생물", question: "생체 시계 조절과 수면에 관여하는 송과샘 호르몬은?", options: ["멜라토닌", "세로토닌", "도파민", "가스트린"], answer: "멜라토닌", isCalc: false },
  { id: 194, category: "생물", question: "심장에서 온몸으로 나가는 혈액이 통과하는 가장 두꺼운 방은?", options: ["우심방", "우심실", "좌심방", "좌심실"], answer: "좌심실", isCalc: false },
  { id: 195, category: "생물", question: "식물이 밤에 기공을 닫고 잎 가장자리로 물방울을 내보내는 현상은?", options: ["일액 현상", "증산 작용", "삼투 현상", "모세관 현상"], answer: "일액 현상", isCalc: false },
  { id: 196, category: "생물", question: "인슐린은 이자의 어느 세포에서 분비되는가?", options: ["알파(α) 세포", "베타(β) 세포", "델타(δ) 세포", "F 세포"], answer: "베타(β) 세포", isCalc: false },
  { id: 197, category: "생물", question: "바이러스가 항생제로 죽지 않는 주된 이유는?", options: ["세포 구조가 없어서", "껍질이 단단해서", "크기가 작아서", "증식이 빨라서"], answer: "세포 구조가 없어서", isCalc: false },
  { id: 198, category: "생물", question: "DNA의 뉴클레오타이드에서 당의 종류는?", options: ["리보스", "디옥시리보스", "포도당", "설탕"], answer: "디옥시리보스", isCalc: false },
  { id: 199, category: "생물", question: "혈청 내에 있는 응집소와 적혈구의 응집원이 만나 결합하는 현상은?", options: ["용혈", "응집", "침전", "중화"], answer: "응집", isCalc: false },
  { id: 200, category: "생물", question: "생물학적 산소 요구량을 뜻하며 수질 오염의 지표가 되는 것은?", options: ["DO", "BOD", "COD", "pH"], answer: "BOD", isCalc: false }
];export const biology_Part5 = [
  { id: 201, category: "생물", question: "DNA 복제 시 지연 가닥에서 형성되는 짧은 DNA 단편들을 무엇이라 하는가?", options: ["프라이머", "오카자키 절편", "인트론", "엑손"], answer: "오카자키 절편", isCalc: false },
  { id: 202, category: "생물", question: "RNA 중합 효소가 결합하여 전사를 시작하는 DNA의 특정 부위는?", options: ["프로모터", "오퍼레이터", "조절 유전자", "구조 유전자"], answer: "프로모터", isCalc: false },
  { id: 203, category: "생물", question: "진핵세포의 mRNA 가공 과정에서 제거되는 비암호화 부위는?", options: ["엑손", "인트론", "폴리 A 꼬리", "캡"], answer: "인트론", isCalc: false },
  { id: 204, category: "생물", question: "단백질의 입체 구조가 열이나 pH에 의해 변해 기능을 잃는 현상은?", options: ["동화 작용", "변성", "중합", "활성화"], answer: "변성", isCalc: false },
  { id: 205, category: "생물", question: "젖당 오페론에서 억제 단백질이 결합하여 전사를 방해하는 부위는?", options: ["프로모터", "작동 부위(오퍼레이터)", "구조 유전자", "조절 유전자"], answer: "작동 부위(오퍼레이터)", isCalc: false },
  { id: 206, category: "생물", question: "세포막을 구성하는 인지질은 머리 부분은 친수성, 꼬리 부분은 ( )이다.", options: ["친수성", "소수성", "양쪽성", "극성"], answer: "소수성", isCalc: false },
  { id: 207, category: "생물", question: "콜레스테롤은 세포막에서 어떤 역할을 하는가?", options: ["에너지원", "유동성 조절", "단백질 합성", "산소 운반"], answer: "유동성 조절", isCalc: false },
  { id: 208, category: "생물", question: "미토콘드리아 내막이 안쪽으로 접혀 들어가 표면적을 넓힌 구조는?", options: ["스트로마", "크리스타", "틸라코이드", "그라나"], answer: "크리스타", isCalc: false },
  { id: 209, category: "생물", question: "식물 세포에서 세포벽을 형성하는 주성분인 다당류는?", options: ["녹말", "글리코젠", "셀룰로오스", "키틴"], answer: "셀룰로오스", isCalc: false },
  { id: 210, category: "생물", question: "감수 분열 중 유전적 다양성을 높이는 상동 염색체 간의 유전자 교환은?", options: ["교차", "비분리", "역위", "중복"], answer: "교차", isCalc: false },
  { id: 211, category: "생물", question: "세포 주기 조절에 실패하여 끊임없이 분열하는 세포는?", options: ["줄기 세포", "암세포", "생식 세포", "신경 세포"], answer: "암세포", isCalc: false },
  { id: 212, category: "생물", question: "중심설(Central Dogma)의 흐름으로 옳은 것은?", options: ["DNA→RNA→단백질", "RNA→DNA→단백질", "단백질→RNA→DNA", "DNA→단백질→RNA"], answer: "DNA→RNA→단백질", isCalc: false },
  { id: 213, category: "생물", question: "개체군 밀도가 높아질 때 개체군 성장을 억제하는 요인을 통칭하는 말은?", options: ["환경 저항", "환경 수용력", "생존 곡선", "피라미드"], answer: "환경 저항", isCalc: false },
  { id: 214, category: "생물", question: "특정 환경이 수용할 수 있는 개체군의 최대 크기는?", options: ["최대 밀도", "환경 수용력", "포화 상태", "개체군 성장률"], answer: "환경 수용력", isCalc: false },
  { id: 215, category: "생물", question: "두 종이 함께 살며 모두 이익을 얻는 상호 작용은?", options: ["상리 공생", "편리 공생", "기생", "경쟁"], answer: "상리 공생", isCalc: false },
  { id: 216, category: "생물", question: "질소 고정 세균인 뿌리혹박테리아와 콩과 식물의 관계는?", options: ["경쟁", "포식", "상리 공생", "기생"], answer: "상리 공생", isCalc: false },
  { id: 217, category: "생물", question: "대기 중의 탄소가 유기물로 바뀌어 생태계로 들어오는 주된 과정은?", options: ["호흡", "광합성", "연소", "부패"], answer: "광합성", isCalc: false },
  { id: 218, category: "생물", question: "생물 군집의 구성 요소 중 무기물을 유기물로 합성하는 것은?", options: ["생산자", "소비자", "분해자", "포식자"], answer: "생산자", isCalc: false },
  { id: 219, category: "생물", question: "에너지와 달리 생태계 내에서 계속 순환하는 것은?", options: ["열", "빛", "물질", "엔트로피"], answer: "물질", isCalc: false },
  { id: 220, category: "생물", question: "생물 다양성의 세 가지 요소는 유전적, 종, ( ) 다양성이다.", options: ["환경", "생태계", "지리적", "행동적"], answer: "생태계", isCalc: false },
  { id: 221, category: "생물", question: "인슐린 분비가 부족하거나 정상적으로 작용하지 않아 발생하는 질환은?", options: ["고혈압", "당뇨병", "빈혈", "구루병"], answer: "당뇨병", isCalc: false },
  { id: 222, category: "생물", question: "우리 몸의 1차 방어 체계에 해당하는 것은?", options: ["피부와 점막", "B 림프구", "T 림프구", "기억 세포"], answer: "피부와 점막", isCalc: false },
  { id: 223, category: "생물", question: "혈액 응고 과정에 직접 관여하는 혈액 성분은?", options: ["적혈구", "백혈구", "혈소판", "혈장 단백질"], answer: "혈소판", isCalc: false },
  { id: 224, category: "생물", question: "뉴런의 흥분 전도 시 나트륨 통로가 열리면 막전위는 어떻게 되는가?", options: ["상승한다", "하강한다", "변함없다", "0으로 고정된다"], answer: "상승한다", isCalc: false },
  { id: 225, category: "생물", question: "사람의 중추 신경계는 뇌와 ( )로 구성된다.", options: ["신경절", "척수", "말초 신경", "감각 기관"], answer: "척수", isCalc: false },
  { id: 226, category: "생물", question: "대뇌 피질의 겉질은 주로 어떤 색을 띠는가?", options: ["백색질", "회색질", "황색질", "적색질"], answer: "회색질", isCalc: false },
  { id: 227, category: "생물", question: "심장 박동과 소화 운동을 조절하는 신경계는?", options: ["자율 신경계", "체성 신경계", "감각 신경계", "중추 신경계"], answer: "자율 신경계", isCalc: false },
  { id: 228, category: "생물", question: "갑상샘 자극 호르몬(TSH)을 분비하는 기관은?", options: ["뇌하수체 전엽", "뇌하수체 후엽", "갑상샘", "시상하부"], answer: "뇌하수체 전엽", isCalc: false },
  { id: 229, category: "생물", question: "추운 환경에서 체온을 올리기 위해 티록신 분비량은 어떻게 되는가?", options: ["증가한다", "감소한다", "변함없다", "중단된다"], answer: "증가한다", isCalc: false },
  { id: 230, category: "생물", question: "동일한 항원이 두 번째 침입했을 때 항체를 대량 생산하는 면역 반응은?", options: ["1차 면역 반응", "2차 면역 반응", "선천 면역", "비특이적 방어"], answer: "2차 면역 반응", isCalc: false },
  { id: 231, category: "생물", question: "DNA에서 당-인산 골격 사이의 결합은?", options: ["수소 결합", "공유 결합", "이온 결합", "금속 결합"], answer: "공유 결합", isCalc: false },
  { id: 232, category: "생물", question: "DNA 염기 쌍 사이의 결합은?", options: ["수소 결합", "공유 결합", "이온 결합", "펩타이드 결합"], answer: "수소 결합", isCalc: false },
  { id: 233, category: "생물", question: "하나의 형질에 대해 대립 유전자가 3개 이상 존재하는 경우(예: ABO 혈액형)는?", options: ["다인자 유전", "복대립 유전", "중간 유전", "성 유전"], answer: "복대립 유전", isCalc: false },
  { id: 234, category: "생물", question: "XY 성염색체 체계에서 암컷의 유전자 구성은?", options: ["XX", "XY", "XO", "ZW"], answer: "XX", isCalc: false },
  { id: 235, category: "생물", question: "염색체의 구조 이상 중 염색체의 일부가 소실되는 현상은?", options: ["중복", "결실", "역위", "전좌"], answer: "결실", isCalc: false },
  { id: 236, category: "생물", question: "종의 분화 요인 중 지리적으로 격리되어 생기는 현상은?", options: ["생식적 격리", "지리적 격리", "행동적 격리", "시간적 격리"], answer: "지리적 격리", isCalc: false },
  { id: 237, category: "생물", question: "식물의 광합성 속도가 0인 것처럼 보이는 빛의 세기는?", options: ["보상점", "광포화점", "임계점", "빙점"], answer: "보상점", isCalc: false },
  { id: 238, category: "생물", question: "신체 내부 환경을 일정하게 유지하려는 성질은?", options: ["적응", "항상성", "대사", "진화"], answer: "항상성", isCalc: false },
  { id: 239, category: "생물", question: "세포 호흡의 TCA 회로가 일어나는 장소는?", options: ["미토콘드리아 기질", "세포질", "엽록체", "리보솜"], answer: "미토콘드리아 기질", isCalc: false },
  { id: 240, category: "생물", question: "단백질 합성 시 아미노산을 리보솜으로 운반하는 RNA는?", options: ["mRNA", "tRNA", "rRNA", "snRNA"], answer: "tRNA", isCalc: false },
  { id: 241, category: "생물", question: "DNA 중합 효소는 새로운 가닥을 어느 방향으로 합성하는가?", options: ["5' → 3'", "3' → 5'", "양방향", "무작위"], answer: "5' → 3'", isCalc: false },
  { id: 242, category: "생물", question: "생물계의 분류 중 동물과 식물의 공통점은?", options: ["진핵생물이다", "광합성을 한다", "세포벽이 있다", "운동성이 있다"], answer: "진핵생물이다", isCalc: false },
  { id: 243, category: "생물", question: "남조류(시아노박테리아)는 어떤 분류에 속하는가?", options: ["원핵생물", "진핵생물", "바이러스", "균류"], answer: "원핵생물", isCalc: false },
  { id: 244, category: "생물", question: "생태계의 에너지 피라미드에서 하위 단계에서 상위 단계로 갈수록 에너지는?", options: ["감소한다", "증가한다", "일정하다", "순환한다"], answer: "감소한다", isCalc: false },
  { id: 245, category: "생물", question: "DNA 지문 분석 시 DNA 조각을 크기에 따라 분리하는 기술은?", options: ["전기 영동", "PCR", "세포 융합", "핵 이식"], answer: "전기 영동", isCalc: false },
  { id: 246, category: "생물", question: "특정 형질이 세대를 거쳐 전달되는 과정을 나타낸 도표는?", options: ["가계도", "지도", "주기율표", "계통수"], answer: "가계도", isCalc: false },
  { id: 247, category: "생물", question: "세포막을 통한 물질 수송 중 농도 차이를 이용한 이동을 무엇이라 하는가?", options: ["수동 수송", "능동 수송", "엔도사이토시스", "엑소사이토시스"], answer: "수동 수송", isCalc: false },
  { id: 248, category: "생물", question: "동물 세포를 증류수(저장액)에 넣었을 때 세포가 터지는 현상은?", options: ["용혈 현상", "원형질 분리", "수축", "안정"], answer: "용혈 현상", isCalc: false },
  { id: 249, category: "생물", question: "효소가 최적 온도보다 높은 온도에서 기능을 잃는 주된 이유는?", options: ["기질 농도 감소", "단백질의 입체 구조 변형", "수분 증발", "활성화 에너지 증가"], answer: "단백질의 입체 구조 변형", isCalc: false },
  { id: 250, category: "생물", question: "하나의 mRNA에 여러 개의 리보솜이 결합하여 단백질을 합성하는 구조는?", options: ["폴리솜", "뉴클레오솜", "리소좀", "염색체"], answer: "폴리솜", isCalc: false }
];export const biology_Part6 = [
  { id: 251, category: "생물", question: "DNA의 특정 염기 서열을 인식하여 절단하는 '유전자 가위'로 불리는 효소 복합체는?", options: ["제한 효소", "CRISPR-Cas9", "DNA 연결 효소", "역전사 효소"], answer: "CRISPR-Cas9", isCalc: false },
  { id: 252, category: "생물", question: "성체 세포를 배아 단계의 미분화 상태로 되돌린 줄기 세포는?", options: ["배아 줄기 세포", "성체 줄기 세포", "유도 만능 줄기 세포(iPSC)", "암세포"], answer: "유도 만능 줄기 세포(iPSC)", isCalc: false },
  { id: 253, category: "생물", question: "RNA를 주형으로 하여 DNA를 합성하는 효소는?", options: ["DNA 중합 효소", "RNA 중합 효소", "역전사 효소", "헬리케이스"], answer: "역전사 효소", isCalc: false },
  { id: 254, category: "생물", question: "단백질의 입체 구조가 비정상적으로 변형되어 뇌 질환을 일으키는 감염체는?", options: ["바이러스", "박테리아", "프라이온(Prion)", "곰팡이"], answer: "프라이온(Prion)", isCalc: false },
  { id: 255, category: "생물", question: "세포 내에서 수명이 다한 소기관을 스스로 잡아먹어 제거하는 과정은?", options: ["자가 포식(Autophagy)", "세포 분열", "세포 융합", "세포 사멸"], answer: "자가 포식(Autophagy)", isCalc: false },
  { id: 256, category: "생물", question: "생물체의 유전 정보를 모두 해독하여 지도화하는 프로젝트는?", options: ["게놈 프로젝트", "단백질 프로젝트", "세포 프로젝트", "줄기 세포 프로젝트"], answer: "게놈 프로젝트", isCalc: false },
  { id: 257, category: "생물", question: "생물학적 분류에서 '강(Class)'의 바로 아래 단계는?", options: ["문", "목", "과", "속"], answer: "목", isCalc: false },
  { id: 258, category: "생물", question: "식물의 광합성 결과 생성된 최초의 3탄소 화합물은?", options: ["G3P(PGAL)", "포도당", "녹말", "설탕"], answer: "G3P(PGAL)", isCalc: false },
  { id: 259, category: "생물", question: "C4 식물(옥수수 등)이 건조한 환경에서 광합성 효율이 높은 이유는?", options: ["이산화 탄소 고정 장소 분리", "기공을 밤에만 염", "빛을 흡수하지 않음", "물이 필요 없음"], answer: "이산화 탄소 고정 장소 분리", isCalc: false },
  { id: 260, category: "생물", question: "CAM 식물(선인장 등)이 기공을 여는 시기는?", options: ["낮", "밤", "항상 열려 있음", "항상 닫혀 있음"], answer: "밤", isCalc: false },
  { id: 261, category: "생물", question: "신경계의 흥분 전달 시 시냅스 틈으로 방출되는 대표적인 억제성 신경 전달 물질은?", options: ["아세틸콜린", "도파민", "GABA", "노르에피네프린"], answer: "GABA", isCalc: false },
  { id: 262, category: "생물", question: "심장 박동을 빠르게 하고 혈압을 높이는 부신 수질 호르몬은?", options: ["에피네프린(아드레날린)", "코르티솔", "알도스테론", "인슐린"], answer: "에피네프린(아드레날린)", isCalc: false },
  { id: 263, category: "생물", question: "스트레스 상황에서 분비되어 혈당을 높이고 염증을 억제하는 호르몬은?", options: ["글루카곤", "코르티솔", "티록신", "옥시토신"], answer: "코르티솔", isCalc: false },
  { id: 264, category: "생물", question: "여성의 월경 주기 중 배란을 유도하는 결정적인 호르몬은?", options: ["에스트로겐", "프로게스테론", "황체 형성 호르몬(LH)", "여포 자극 호르몬(FSH)"], answer: "황체 형성 호르몬(LH)", isCalc: false },
  { id: 265, category: "생물", question: "임신 초기 유산을 방지하기 위해 황체를 유지시키는 호르몬(HCG)을 분비하는 곳은?", options: ["난소", "자궁", "태반", "뇌하수체"], answer: "태반", isCalc: false },
  { id: 266, category: "생물", question: "혈액 응고를 방지하기 위해 사용하는 간에서 생성되는 물질은?", options: ["히루딘", "헤파린", "와파린", "아스피린"], answer: "헤파린", isCalc: false },
  { id: 267, category: "생물", question: "사람의 망막에서 색깔을 구별하는 시각 세포는?", options: ["간상 세포", "원추 세포", "쌍극 세포", "신경절 세포"], answer: "원추 세포", isCalc: false },
  { id: 268, category: "생물", question: "명암 변화에 적응하여 어두운 곳에서 서서히 사물이 보이는 현상은?", options: ["명적응", "암적응", "색수차", "굴절"], answer: "암적응", isCalc: false },
  { id: 269, category: "생물", question: "우리 몸의 평형 감각 중 회전 감각을 담당하는 기관은?", options: ["전정 기관", "반고리관", "달팽이관", "유스타키오관"], answer: "반고리관", isCalc: false },
  { id: 270, category: "생물", question: "생물의 개체군 생장 곡선 중 환경 저항이 없을 때 나타나는 이론적 곡선 모양은?", options: ["S자형", "J자형", "L자형", "U자형"], answer: "J자형", isCalc: false },
  { id: 271, category: "생물", question: "군집 내에서 서로 다른 종이 자원을 나누어 사용하여 경쟁을 피하는 현상은?", options: ["분서(지위 분화)", "기생", "편리 공생", "포식"], answer: "분서(지위 분화)", isCalc: false },
  { id: 272, category: "생물", question: "호수에서 영양염류가 과다해져 플랑크톤이 급격히 늘어나는 현상은?", options: ["빈영양화", "부영양화", "산성화", "염류화"], answer: "부영양화", isCalc: false },
  { id: 273, category: "생물", question: "외래종이 유입되었을 때 생태계에 미치는 가장 큰 부정적 영향은?", options: ["종 다양성 감소", "먹이 그물 단순화", "토착종 멸종 위험", "위의 모든 것"], answer: "위의 모든 것", isCalc: false },
  { id: 274, category: "생물", question: "지구상에서 단위 면적당 생물 다양성이 가장 높은 곳은?", options: ["열대 우림", "사막", "툰드라", "초원"], answer: "열대 우림", isCalc: false },
  { id: 275, category: "생물", question: "생물의 특징 중 하나로, 체내의 화학 반응 전체를 일컫는 말은?", options: ["물질대사", "유전", "진화", "반응"], answer: "물질대사", isCalc: false },
  { id: 276, category: "생물", question: "유전 정보를 해독할 때, 개시 코돈(AUG)이 지정하는 아미노산은?", options: ["발린", "메티오닌", "라이신", "프롤린"], answer: "메티오닌", isCalc: false },
  { id: 277, category: "생물", question: "DNA 복제 시 이중 나선을 풀어주는 효소는?", options: ["폴리메레이스", "라이게이스", "헬리케이스", "뉴클레이스"], answer: "헬리케이스", isCalc: false },
  { id: 278, category: "생물", question: "원핵세포의 DNA 복제는 보통 몇 군데의 복제 원점에서 시작되는가?", options: ["1군데", "수십 군데", "수천 군데", "없음"], answer: "1군데", isCalc: true },
  { id: 279, category: "생물", question: "진핵생물의 유전자 발현 조절에서 DNA가 히스톤 단백질에 감긴 구조는?", options: ["리보솜", "뉴클레오솜", "플라스미드", "미세소관"], answer: "뉴클레오솜", isCalc: false },
  { id: 280, category: "생물", question: "세균이 외부의 DNA를 받아들여 형질이 변하는 현상은?", options: ["형질 전환", "형질 도입", "접합", "돌연변이"], answer: "형질 전환", isCalc: false },
  { id: 281, category: "생물", question: "박테리오파지를 매개로 세균 간의 유전자가 이동하는 현상은?", options: ["형질 전환", "형질 도입", "접합", "교차"], answer: "형질 도입", isCalc: false },
  { id: 282, category: "생물", question: "항생제 내성 유전자가 주로 포함되어 있는 세균의 작은 고리형 DNA는?", options: ["핵양체", "플라스미드", "미토콘드리아 DNA", "RNA"], answer: "플라스미드", isCalc: false },
  { id: 283, category: "생물", question: "사람의 게놈 중 실제로 단백질을 암호화하는 부위는 전체의 약 몇 %인가?", options: ["1.5~2%", "20%", "50%", "90%"], answer: "1.5~2%", isCalc: true },
  { id: 284, category: "생물", question: "세포 내 액포의 주요 기능이 아닌 것은?", options: ["수분 조절", "노폐물 저장", "단백질 합성", "형태 유지"], answer: "단백질 합성", isCalc: false },
  { id: 285, category: "생물", question: "근육 세포의 수축 단위인 근절(Sarcomere)을 구분하는 경계선은?", options: ["Z선", "M선", "H대", "A대"], answer: "Z선", isCalc: false },
  { id: 286, category: "생물", question: "세포 호흡 중 산소가 없을 때 피루브산이 아세트알데하이드를 거쳐 에탄올이 되는 과정은?", options: ["알코올 발효", "젖산 발효", "산소 호흡", "회로"], answer: "알코올 발효", isCalc: false },
  { id: 287, category: "생물", question: "엽록체의 스트로마에서 일어나는 탄소 고정 반응을 발견한 과학자는?", options: ["캘빈", "크렙스", "파스퇴르", "멘델"], answer: "캘빈", isCalc: false },
  { id: 288, category: "생물", question: "생물의 분류 계급 중 '문(Phylum)'의 바로 위 단계는?", options: ["계(Kingdom)", "강", "목", "역"], answer: "계(Kingdom)", isCalc: false },
  { id: 289, category: "생물", question: "종간 상호 작용 중 한쪽은 이익을 얻지만 다른 쪽은 이익도 손해도 없는 관계는?", options: ["상리 공생", "편리 공생", "기생", "편해 공생"], answer: "편리 공생", isCalc: false },
  { id: 290, category: "생물", question: "개체군 내에서 강한 개체가 먹이나 암컷을 독점하는 행동은?", options: ["순위제", "텃세", "리더제", "가족 생활"], answer: "텃세", isCalc: false },
  { id: 291, category: "생물", question: "동일한 지역에 살며 상호 작용하는 여러 개체군들의 집합은?", options: ["군집", "생태계", "생물권", "개체군"], answer: "군집", isCalc: false },
  { id: 292, category: "생물", question: "혈액 속의 이산화 탄소 농도가 높아지면 혈액의 pH는 어떻게 되는가?", options: ["낮아진다(산성)", "높아진다(알칼리성)", "변함없다", "7.4로 고정된다"], answer: "낮아진다(산성)", isCalc: false },
  { id: 293, category: "생물", question: "뇌의 시상하부에서 분비되어 뇌하수체 전엽을 자극하는 호르몬들을 통칭하여 ( )라 한다.", options: ["방출 호르몬(RH)", "억제 호르몬", "성선 호르몬", "성장 호르몬"], answer: "방출 호르몬(RH)", isCalc: false },
  { id: 294, category: "생물", question: "세포막의 단백질 중 특정 이온을 통과시키는 통로 역할을 하는 것은?", options: ["수용체 단백질", "수송 단백질(이온 통로)", "효소 단백질", "인식 단백질"], answer: "수송 단백질(이온 통로)", isCalc: false },
  { id: 295, category: "생물", question: "미토콘드리아와 엽록체가 과거 독립된 세균이었다가 세포 안으로 들어왔다는 가설은?", options: ["세포 내 공생설", "자연 발생설", "진화설", "다윈설"], answer: "세포 내 공생설", isCalc: false },
  { id: 296, category: "생물", question: "염색체에서 두 염색 분체가 연결되어 있는 잘록한 부분은?", options: ["동원체", "텔로미어", "중심체", "성상체"], answer: "동원체", isCalc: false },
  { id: 297, category: "생물", question: "효소의 활성 부위가 아닌 다른 곳에 결합하여 효소 기능을 억제하는 방식은?", options: ["경쟁적 저해", "비경쟁적 저해", "기질 특이성", "피드백 조절"], answer: "비경쟁적 저해", isCalc: false },
  { id: 298, category: "생물", question: "혈액 순환 중 심장에서 폐로 갔다가 다시 심장으로 돌아오는 경로는?", options: ["체순환", "폐순환", "림프 순환", "간순환"], answer: "폐순환", isCalc: false },
  { id: 299, category: "생물", question: "식물 세포가 물을 흡수하여 세포벽을 밀어내는 압력은?", options: ["삼투압", "팽압", "흡수력", "벽압"], answer: "팽압", isCalc: false },
  { id: 300, category: "생물", question: "생물의 유전 정보를 인위적으로 조작하여 인류에게 유용한 산물을 만드는 학문은?", options: ["생명 공학", "유전학", "세포학", "분류학"], answer: "생명 공학", isCalc: false }
];