 export const chemistry_Part1 = [
 { id: 1, category: "화학", question: "물질을 구성하는 가장 기본 단위 입자는?", options: ["분자", "원자", "이온", "전자"], answer: "원자", isCalc: false },
  { id: 2, category: "화학", question: "원자핵을 구성하는 두 가지 입자는?", options: ["전자와 양성자", "양성자와 중성자", "전자와 중성자", "쿼크와 렙톤"], answer: "양성자와 중성자", isCalc: false },
  { id: 3, category: "화학", question: "원자 번호는 원자핵 내의 무엇의 수와 같은가?", options: ["전자", "양성자", "중성자", "핵자"], answer: "양성자", isCalc: false },
  { id: 4, category: "화학", question: "질량수가 같고 원자 번호가 다른 원소들은 서로 무엇인가?", options: ["동위 원소", "동소체", "등압 원소", "이성질체"], answer: "등압 원소", isCalc: false },
  { id: 5, category: "화학", question: "주기율표에서 가로 줄을 무엇이라 하는가?", options: ["족", "주기", "구역", "블록"], answer: "주기", isCalc: false },
  { id: 6, category: "화학", question: "주기율표에서 세로 줄을 무엇이라 하는가?", options: ["족", "주기", "구역", "블록"], answer: "족", isCalc: false },
  { id: 7, category: "화학", question: "알칼리 금속은 주기율표의 몇 족에 해당하는가?", options: ["1족", "2족", "17족", "18족"], answer: "1족", isCalc: false },
  { id: 8, category: "화학", question: "할로겐 원소는 주기율표의 몇 족에 해당하는가?", options: ["1족", "2족", "17족", "18족"], answer: "17족", isCalc: false },
  { id: 9, category: "화학", question: "가장 반응성이 낮아 안정적인 18족 원소들은?", options: ["할로겐 원소", "비활성 기체", "전이 금속", "알칼리 토금속"], answer: "비활성 기체", isCalc: false },
  { id: 10, category: "화학", question: "분자 내에서 원자들이 전자를 공유하여 형성하는 결합은?", options: ["이온 결합", "공유 결합", "금속 결합", "수소 결합"], answer: "공유 결합", isCalc: false },
  { id: 11, category: "화학", question: "금속 원자와 비금속 원자 사이의 전하 이동으로 형성되는 결합은?", options: ["이온 결합", "공유 결합", "금속 결합", "배위 결합"], answer: "이온 결합", isCalc: false },
  { id: 12, category: "화학", question: "전자를 잃어 양전하를 띠게 된 입자는?", options: ["음이온", "양이온", "중성 원자", "분자"], answer: "양이온", isCalc: false },
  { id: 13, category: "화학", question: "물질의 양을 나타내는 기본 단위는?", options: ["kg", "L", "mol", "K"], answer: "mol", isCalc: false },
  { id: 14, category: "화학", question: "1몰에 포함된 입자의 수는? (아보가드로 수)", options: ["6.02x10²²", "6.02x10²³", "3.01x10²³", "1.6x10⁻¹⁹"], answer: "6.02x10²³", isCalc: false },
  { id: 15, category: "화학", question: "물(H₂O)의 분자량은? (H=1, O=16)", options: ["17", "18", "19", "20"], answer: "18", isCalc: true },
  { id: 16, category: "화학", question: "화학 반응 전후에 물질의 총 질량은 변하지 않는다는 법칙은?", options: ["일정 성분비 법칙", "배수 비례 법칙", "질량 보존 법칙", "기체 반응 법칙"], answer: "질량 보존 법칙", isCalc: false },
  { id: 17, category: "화학", question: "화합물을 구성하는 성분 원소 사이에는 일정한 질량비가 성립한다는 법칙은?", options: ["질량 보존 법칙", "일정 성분비 법칙", "배수 비례 법칙", "기체 반응 법칙"], answer: "일정 성분비 법칙", isCalc: false },
  { id: 18, category: "화학", question: "두 원소가 결합하여 여러 가지 화합물을 만들 때, 질량비가 간단한 정수비가 된다는 법칙은?", options: ["일정 성분비 법칙", "배수 비례 법칙", "질량 보존 법칙", "기체 반응 법칙"], answer: "배수 비례 법칙", isCalc: false },
  { id: 19, category: "화학", question: "기체들이 반응하여 기체가 생성될 때 부피 사이에는 간단한 정수비가 성립한다는 법칙은?", options: ["질량 보존 법칙", "일정 성분비 법칙", "기체 반응 법칙", "아보가드로 법칙"], answer: "기체 반응 법칙", isCalc: false },
  { id: 20, category: "화학", question: "같은 온도와 압력에서 모든 기체는 같은 부피 속에 같은 수의 분자를 가진다는 법칙은?", options: ["보일의 법칙", "샤를의 법칙", "아보가드로 법칙", "달턴의 법칙"], answer: "아보가드로 법칙", isCalc: false },
  { id: 21, category: "화학", question: "0°C, 1기압(STP)에서 기체 1몰의 부피는?", options: ["22.4 L", "24.5 L", "1.0 L", "10.0 L"], answer: "22.4 L", isCalc: false },
  { id: 22, category: "화학", question: "산의 정의 중 수소 이온(H⁺)을 내놓는 물질은?", options: ["아레니우스 산", "브뢴스테드-로우리 산", "루이스 산", "염기"], answer: "아레니우스 산", isCalc: false },
  { id: 23, category: "화학", question: "염기의 정의 중 수산화 이온(OH⁻)을 내놓는 물질은?", options: ["아레니우스 염기", "브뢴스테드-로우리 염기", "루이스 염기", "산"], answer: "아레니우스 염기", isCalc: false },
  { id: 24, category: "화학", question: "pH가 7보다 작은 용액은 무엇인가?", options: ["산성", "염기성", "중성", "알칼리성"], answer: "산성", isCalc: false },
  { id: 25, category: "화학", question: "산과 염기가 반응하여 물과 염을 생성하는 반응은?", options: ["산화 반응", "환원 반응", "중화 반응", "분해 반응"], answer: "중화 반응", isCalc: false },
  { id: 26, category: "화학", question: "전자를 잃는 반응을 무엇이라 하는가?", options: ["산화", "환원", "중화", "연소"], answer: "산화", isCalc: false },
  { id: 27, category: "화학", question: "전자를 얻는 반응을 무엇이라 하는가?", options: ["산화", "환원", "중화", "연소"], answer: "환원", isCalc: false },
  { id: 28, category: "화학", question: "산화수가 증가하는 반응은?", options: ["산화", "환원", "중화", "용해"], answer: "산화", isCalc: false },
  { id: 29, category: "화학", question: "산화수가 감소하는 반응은?", options: ["산화", "환원", "중화", "용해"], answer: "환원", isCalc: false },
  { id: 30, category: "화학", question: "화학 반응에서 반응 속도를 빠르게 하는 물질은?", options: ["반응물", "생성물", "촉매", "용매"], answer: "촉매", isCalc: false },
  { id: 31, category: "화학", question: "온도가 올라가면 화학 반응 속도는 어떻게 되는가?", options: ["느려진다", "빨라진다", "변함없다", "0이 된다"], answer: "빨라진다", isCalc: false },
  { id: 32, category: "화학", question: "반응물의 농도가 높아지면 화학 반응 속도는 어떻게 되는가?", options: ["느려진다", "빨라진다", "변함없다", "0이 된다"], answer: "빨라진다", isCalc: false },
  { id: 33, category: "화학", question: "반응 속도를 느리게 하는 촉매를 무엇이라 하는가?", options: ["정촉매", "부촉매", "효소", "친핵체"], answer: "부촉매", isCalc: false },
  { id: 34, category: "화학", question: "가역 반응에서 정반응 속도와 역반응 속도가 같아져 겉보기 변화가 없는 상태는?", options: ["정지 상태", "평형 상태", "임계 상태", "최대 상태"], answer: "평형 상태", isCalc: false },
  { id: 35, category: "화학", question: "평형 상태의 계에 스트레스를 가하면 스트레스를 줄이는 방향으로 평형이 이동한다는 원리는?", options: ["보일의 원리", "샤를의 원리", "르샤틀리에 원리", "파울리 원리"], answer: "르샤틀리에 원리", isCalc: false },
  { id: 36, category: "화학", question: "탄소 화합물을 중심적으로 다루는 화학 분야는?", options: ["무기화학", "유기화학", "분석화학", "물리화학"], answer: "유기화학", isCalc: false },
  { id: 37, category: "화학", question: "탄소와 수소로만 구성된 화합물은?", options: ["탄화수소", "알코올", "카복실산", "에테르"], answer: "탄화수소", isCalc: false },
  { id: 38, category: "화학", question: "분자식은 같지만 구조가 달라 성질이 다른 물질들은?", options: ["동위 원소", "동소체", "구조 이성질체", "입체 이성질체"], answer: "구조 이성질체", isCalc: false },
  { id: 39, category: "화학", question: "탄소-탄소 이중 결합을 가진 탄화수소는?", options: ["알케인", "알켄", "알카인", "방향족"], answer: "알켄", isCalc: false },
  { id: 40, category: "화학", question: "탄소-탄소 삼중 결합을 가진 탄화수소는?", options: ["알케인", "알켄", "알카인", "방향족"], answer: "알카인", isCalc: false },
  { id: 41, category: "화학", question: "고리형 탄화수소 중 벤젠 고리를 가진 것은?", options: ["지방족 탄화수소", "방향족 탄화수소", "포화 탄화수소", "알코올"], answer: "방향족 탄화수소", isCalc: false },
  { id: 42, category: "화학", question: "유기 화합물의 특징적인 성질을 결정하는 원자단은?", options: ["작용기", "측쇄", "고리", "탄소골격"], answer: "작용기", isCalc: false },
  { id: 43, category: "화학", question: "탄화수소의 수소가 -OH기로 치환된 화합물은?", options: ["알코올", "에테르", "알데하이드", "케톤"], answer: "알코올", isCalc: false },
  { id: 44, category: "화학", question: "화학 반응에서 에너지를 흡수하는 반응은?", options: ["발열 반응", "흡열 반응", "연소 반응", "산화 반응"], answer: "흡열 반응", isCalc: false },
  { id: 45, category: "화학", question: "화학 반응에서 에너지를 방출하는 반응은?", options: ["발열 반응", "흡열 반응", "분해 반응", "환원 반응"], answer: "발열 반응", isCalc: false },
  { id: 46, category: "화학", question: "원자가 전자가 들어갈 수 있는 오비탈의 최대 전자는?", options: ["2개", "4개", "6개", "8개"], answer: "2개", isCalc: true },
  { id: 47, category: "화학", question: "원자에서 가장 바깥 껍질에 있는 전자는?", options: ["내핵 전자", "원자가 전자", "핵자", "중성자"], answer: "원자가 전자", isCalc: false },
  { id: 48, category: "화학", question: "옥텟 규칙(Octet Rule)에 따라 안정해지기 위해 필요한 전자 수는?", options: ["2개", "4개", "6개", "8개"], answer: "8개", isCalc: false },
  { id: 49, category: "화학", question: "전기 음성도가 가장 큰 원소는?", options: ["산소(O)", "질소(N)", "플루오린(F)", "염소(Cl)"], answer: "플루오린(F)", isCalc: false },
  { id: 50, category: "화학", question: "혼합물을 끓는점 차이를 이용해 분리하는 방법은?", options: ["여과", "추출", "증류", "크로마토그래피"], answer: "증류", isCalc: false }
];export const chemistry_Part2 = [
  { id: 51, category: "화학", question: "전자를 발견하여 푸딩 모형을 제시한 과학자는?", options: ["돌턴", "톰슨", "러더퍼드", "보어"], answer: "톰슨", isCalc: false },
  { id: 52, category: "화학", question: "알파 입자 산란 실험을 통해 원자핵을 발견한 사람은?", options: ["톰슨", "러더퍼드", "보어", "채드윅"], answer: "러더퍼드", isCalc: false },
  { id: 53, category: "화학", question: "전자가 특정 궤도에서만 운동한다는 궤도 모형을 제시한 사람은?", options: ["톰슨", "보어", "뉴턴", "하이젠베르크"], answer: "보어", isCalc: false },
  { id: 54, category: "화학", question: "현대적 원자 모형에서 전자가 존재할 확률을 나타낸 것은?", options: ["전자 궤도", "오비탈(Orbital)", "에너지 준위", "양자수"], answer: "오비탈(Orbital)", isCalc: false },
  { id: 55, category: "화학", question: "s 오비탈은 어떤 모양인가?", options: ["아령 모양", "구 모양", "도넛 모양", "정육면체 모양"], answer: "구 모양", isCalc: false },
  { id: 56, category: "화학", question: "p 오비탈은 한 에너지 준위에 총 몇 개가 존재하는가?", options: ["1개", "2개", "3개", "5개"], answer: "3개", isCalc: false },
  { id: 57, category: "화학", question: "에너지가 가장 낮은 오비탈부터 전자가 채워진다는 원리는?", options: ["싸움 원리", "파울리 배타 원리", "훈트 규칙", "옥텟 규칙"], answer: "싸움 원리", isCalc: false },
  { id: 58, category: "화학", question: "한 오비탈에는 스핀 방향이 반대인 전자가 최대 2개까지만 들어간다는 원리는?", options: ["싸움 원리", "파울리 배타 원리", "훈트 규칙", "불확정성 원리"], answer: "파울리 배타 원리", isCalc: false },
  { id: 59, category: "화학", question: "에너지가 같은 오비탈에 전자가 채워질 때 홀전자 수가 최대가 되도록 채워진다는 규칙은?", options: ["싸움 원리", "파울리 배타 원리", "훈트 규칙", "아보가드로 법칙"], answer: "훈트 규칙", isCalc: false },
  { id: 60, category: "화학", question: "원자에서 전자를 한 개 떼어내는 데 필요한 최소 에너지는?", options: ["전자 친화도", "이온화 에너지", "전기 음성도", "격자 에너지"], answer: "이온화 에너지", isCalc: false },
  { id: 61, category: "화학", question: "원자가 전자를 끌어당기는 상대적인 세기를 수치로 나타낸 것은?", options: ["전자 친화도", "전기 음성도", "이온화 에너지", "유효 핵전하"], answer: "전기 음성도", isCalc: false },
  { id: 62, category: "화학", question: "이온 결합 물질의 특징이 아닌 것은?", options: ["녹는점이 높다", "고체 상태에서 전기 전도성이 있다", "수용액 상태에서 전기 전도성이 있다", "충격을 주면 쉽게 부서진다"], answer: "고체 상태에서 전기 전도성이 있다", isCalc: false },
  { id: 63, category: "화학", question: "금속 결합에서 금속 원자 사이를 자유롭게 이동하는 전자는?", options: ["원자가 전자", "핵전자", "자유 전자", "공유 전자"], answer: "자유 전자", isCalc: false },
  { id: 64, category: "화학", question: "공유 전자쌍을 한 원자가 일방적으로 제공하여 형성되는 결합은?", options: ["배위 결합", "이온 결합", "금속 결합", "수소 결합"], answer: "배위 결합", isCalc: false },
  { id: 65, category: "화학", question: "분자 내 전자 분포가 치우쳐 전하를 띠게 되는 분자는?", options: ["극성 분자", "무극성 분자", "이온 분자", "배위 화합물"], answer: "극성 분자", isCalc: false },
  { id: 66, category: "화학", question: "메테인(CH₄) 분자의 기하학적 모양은?", options: ["직선형", "정사면체형", "평면 삼각형", "굽은형"], answer: "정사면체형", isCalc: false },
  { id: 67, category: "화학", question: "물(H₂O) 분자의 중심 원자 주위 전자쌍 배치는 굽은형이다. 결합각은 약 몇 도인가?", options: ["180도", "120도", "109.5도", "104.5도"], answer: "104.5도", isCalc: true },
  { id: 68, category: "화학", question: "이산화 탄소(CO₂)의 분자 모양은?", options: ["굽은형", "삼각뿔형", "직선형", "평면 삼각형"], answer: "직선형", isCalc: false },
  { id: 69, category: "화학", question: "질소(N₂) 분자에는 몇 중 결합이 존재하는가?", options: ["단일 결합", "이중 결합", "삼중 결합", "사중 결합"], answer: "삼중 결합", isCalc: false },
  { id: 70, category: "화학", question: "용액 1L 속에 녹아 있는 용질의 몰수를 나타낸 농도는?", options: ["몰랄 농도", "몰 농도", "퍼센트 농도", "ppm 농도"], answer: "몰 농도", isCalc: false },
  { id: 71, category: "화학", question: "용액의 농도 단위 중 온도 변화에 영향을 받지 않는 것은?", options: ["몰 농도", "몰랄 농도", "노르말 농도", "부피 백분율"], answer: "몰랄 농도", isCalc: false },
  { id: 72, category: "화학", question: "용질이 용매에 녹을 때 발생하는 열을 무엇이라 하는가?", options: ["반응열", "중화열", "용해열", "연소열"], answer: "용해열", isCalc: false },
  { id: 73, category: "화학", question: "온도가 일정할 때 기체의 용해도는 압력에 비례한다는 법칙은?", options: ["헨리의 법칙", "라울의 법칙", "보일의 법칙", "그레이엄의 법칙"], answer: "헨리의 법칙", isCalc: false },
  { id: 74, category: "화학", question: "비휘발성 용질이 녹아 있는 용액의 증기 압력이 낮아지는 현상은?", options: ["끓는점 오름", "어는점 내림", "증기 압력 내림", "삼투압"], answer: "증기 압력 내림", isCalc: false },
  { id: 75, category: "화학", question: "용액의 총괄성에 속하지 않는 현상은?", options: ["어는점 내림", "삼투압", "용해 속도", "끓는점 오름"], answer: "용해 속도", isCalc: false },
  { id: 76, category: "화학", question: "반투과성 막을 통해 용매가 농도가 낮은 쪽에서 높은 쪽으로 이동하는 현상은?", options: ["확산", "삼투", "여과", "추출"], answer: "삼투", isCalc: false },
  { id: 77, category: "화학", question: "헤스의 법칙은 무엇이 보존됨을 이용하는가?", options: ["질량", "엔탈피(에너지)", "부피", "엔트로피"], answer: "엔탈피(에너지)", isCalc: false },
  { id: 78, category: "화학", question: "반응 경로에 상관없이 반응 전후의 총 열량 변화는 일정하다는 법칙은?", options: ["헤스의 법칙", "라부아지에 법칙", "게이뤼삭 법칙", "샤를 법칙"], answer: "헤스의 법칙", isCalc: false },
  { id: 79, category: "화학", question: "활성화 에너지가 낮아지면 반응 속도는 어떻게 되는가?", options: ["느려진다", "빨라진다", "변함없다", "0이 된다"], answer: "빨라진다", isCalc: false },
  { id: 80, category: "화학", question: "전기 에너지를 이용하여 비자발적인 화학 반응을 일으키는 장치는?", options: ["화학 전지", "전해 전지(전기 분해)", "축전기", "연료 전지"], answer: "전해 전지(전기 분해)", isCalc: false },
  { id: 81, category: "화학", question: "다이아몬드와 흑연은 탄소의 무엇인가?", options: ["동위 원소", "동소체", "이성질체", "혼합물"], answer: "동소체", isCalc: false },
  { id: 82, category: "화학", question: "나프탈렌이 고체에서 바로 기체로 변하는 현상은?", options: ["승화", "기화", "액화", "융해"], answer: "승화", isCalc: false },
  { id: 83, category: "화학", question: "원자 내부에서 전자가 발견될 확률이 0인 지점이나 평면을 무엇이라 하는가?", options: ["마디(Node)", "핵", "안정권", "배타 영역"], answer: "마디(Node)", isCalc: false },
  { id: 84, category: "화학", question: "화학 결합 중 F, O, N과 결합한 수소 원자가 이웃한 분자와 만드는 강한 인력은?", options: ["반데르발스 힘", "수소 결합", "이온 결합", "금속 결합"], answer: "수소 결합", isCalc: false },
  { id: 85, category: "화학", question: "물 분자 한 개는 최대 몇 개의 수소 결합을 형성할 수 있는가?", options: ["1개", "2개", "3개", "4개"], answer: "4개", isCalc: true },
  { id: 86, category: "화학", question: "드라이아이스의 주성분은?", options: ["고체 산소", "고체 질소", "고체 이산화 탄소", "고체 메테인"], answer: "고체 이산화 탄소", isCalc: false },
  { id: 87, category: "화학", question: "화합물을 나타내는 가장 간단한 정수비의 식은?", options: ["분자식", "실험식", "구조식", "시성식"], answer: "실험식", isCalc: false },
  { id: 88, category: "화학", question: "포도당(C₆H₁₂O₆)의 실험식은?", options: ["CH₂O", "CHO", "C₂H₄O₂", "C₆H₁₂O₆"], answer: "CH₂O", isCalc: true },
  { id: 89, category: "화학", question: "금속이 산소와 반응하여 녹이 슬거나 부식되는 반응은?", options: ["산화", "환원", "복분해", "중화"], answer: "산화", isCalc: false },
  { id: 90, category: "화학", question: "산화-환원 반응에서 자신은 환원되면서 다른 물질을 산화시키는 물질은?", options: ["산화제", "환원제", "촉매", "지시약"], answer: "산화제", isCalc: false },
  { id: 91, category: "화학", question: "수소 이온 농도를 나타내는 pH 지수를 처음 제안한 사람은?", options: ["쇠렌센", "아레니우스", "루이스", "라부아지에"], answer: "쇠렌센", isCalc: false },
  { id: 92, category: "화학", question: "용액에 산이나 염기를 가해도 pH 변화가 크게 나타나지 않는 용액은?", options: ["표준 용액", "완충 용액", "포화 용액", "콜로이드 용액"], answer: "완충 용액", isCalc: false },
  { id: 93, category: "화학", question: "금속의 이온화 경향이 클수록 전자를 잃기 ( ). 빈칸은?", options: ["쉽다", "어렵다"], answer: "쉽다", isCalc: false },
  { id: 94, category: "화학", question: "다니엘 전지에서 아연 판은 전자를 잃고 이온이 된다. 이때 아연 판은 어느 극인가?", options: ["(+)극", "(-)극"], answer: "(-)극", isCalc: false },
  { id: 95, category: "화학", question: "전기 분해에서 (-)극으로 이동하여 환원되는 이온은?", options: ["양이온", "음이온", "중성 분자", "전자"], answer: "양이온", isCalc: false },
  { id: 96, category: "화학", question: "암모니아를 대량 생산하는 공정의 이름은?", options: ["하버-보슈법", "접촉법", "솔베이법", "오스트발트법"], answer: "하버-보슈법", isCalc: false },
  { id: 97, category: "화학", question: "공유 전자쌍 사이의 반발을 최소화하는 방향으로 분자 모양이 결정된다는 이론은?", options: ["VSEPR 이론", "VBT 이론", "MOT 이론", "CFT 이론"], answer: "VSEPR 이론", isCalc: false },
  { id: 98, category: "화학", question: "중심 원자가 3개의 원자와 결합하고 비공유 전자쌍이 없을 때의 결합각은?", options: ["90도", "109.5도", "120도", "180도"], answer: "120도", isCalc: true },
  { id: 99, category: "화학", question: "반응 속도 상수 k는 무엇에 의해서만 변하는가?", options: ["농도", "압력", "표면적", "온도"], answer: "온도", isCalc: false },
  { id: 100, category: "화학", question: "방사성 동위 원소의 붕괴는 대개 몇 차 반응인가?", options: ["0차 반응", "1차 반응", "2차 반응", "3차 반응"], answer: "1차 반응", isCalc: false }
];export const chemistry_Part3 = [
  { id: 101, category: "화학", question: "이상 기체 상태 방정식 PV=nRT에서 R이 의미하는 것은?", options: ["기체 상수", "볼츠만 상수", "플랑크 상수", "아보가드로 수"], answer: "기체 상수", isCalc: false },
  { id: 102, category: "화학", question: "혼합 기체의 전체 압력은 각 성분 기체의 부분 압력의 합과 같다는 법칙은?", options: ["보일의 법칙", "돌턴의 부분 압력 법칙", "그레이엄의 법칙", "헨리의 법칙"], answer: "돌턴의 부분 압력 법칙", isCalc: false },
  { id: 103, category: "화학", question: "기체의 확산 속도는 분자량의 제곱근에 반비례한다는 법칙은?", options: ["샤를의 법칙", "그레이엄의 법칙", "아보가드로 법칙", "보일의 법칙"], answer: "그레이엄의 법칙", isCalc: false },
  { id: 104, category: "화학", question: "실제 기체가 이상 기체처럼 행동하기 위한 조건은?", options: ["고온, 고압", "저온, 저압", "고온, 저압", "저온, 고압"], answer: "고온, 저압", isCalc: false },
  { id: 105, category: "화학", question: "분자 사이에 작용하는 모든 인력을 통칭하여 무엇이라 하는가?", options: ["공유 결합력", "반데르발스 힘", "이온 결합력", "금속 결합력"], answer: "반데르발스 힘", isCalc: false },
  { id: 106, category: "화학", question: "액체 표면에서 분자들이 인력을 이기고 기체로 변하는 현상은?", options: ["끓음", "증발", "응축", "융해"], answer: "증발", isCalc: false },
  { id: 107, category: "화학", question: "액체의 증기 압력이 외부 압력과 같아져 내부에서도 기화가 일어나는 온도는?", options: ["어는점", "끓는점", "임계점", "녹는점"], answer: "끓는점", isCalc: false },
  { id: 108, category: "화학", question: "액체 내부의 분자가 표면적을 최소화하려는 힘은?", options: ["모세관 현상", "표면 장력", "점성", "부력"], answer: "표면 장력", isCalc: false },
  { id: 109, category: "화학", question: "고체 입자들이 규칙적으로 배열되어 있는 고체를 무엇이라 하는가?", options: ["결정성 고체", "비결정성 고체", "유리", "플라스틱"], answer: "결정성 고체", isCalc: false },
  { id: 110, category: "화학", question: "드라이아이스나 아이오딘처럼 분자가 격자점을 차지하는 결정은?", options: ["이온 결정", "분자 결정", "공유 결정", "금속 결정"], answer: "분자 결정", isCalc: false },
  { id: 111, category: "화학", question: "다이아몬드나 석영처럼 모든 원자가 공유 결합으로 연결된 결정은?", options: ["분자 결정", "공유 결정(원자 결정)", "이온 결정", "금속 결정"], answer: "공유 결정(원자 결정)", isCalc: false },
  { id: 112, category: "화학", question: "용액의 농도 중 용매 1kg에 녹아 있는 용질의 몰수는?", options: ["몰 농도", "몰랄 농도", "퍼센트 농도", "몰 분율"], answer: "몰랄 농도", isCalc: true },
  { id: 113, category: "화학", question: "비휘발성 용질이 녹은 용액의 끓는점이 순수한 용매보다 높아지는 현상은?", options: ["끓는점 오름", "어는점 내림", "삼투압", "증기 압력 내림"], answer: "끓는점 오름", isCalc: false },
  { id: 114, category: "화학", question: "겨울철 도로에 제설제를 뿌려 눈을 녹이는 원리와 관계 깊은 것은?", options: ["끓는점 오름", "어는점 내림", "기체 용해도", "확산"], answer: "어는점 내림", isCalc: false },
  { id: 115, category: "화학", question: "식물의 뿌리에서 물을 흡수하는 원리는?", options: ["증류", "삼투", "추출", "여과"], answer: "삼투", isCalc: false },
  { id: 116, category: "화학", question: "용질 입자의 크기가 1~1000nm 정도로 커서 빛을 산란시키는 혼합물은?", options: ["참용액", "콜로이드 용액", "서스펜션", "포화 용액"], answer: "콜로이드 용액", isCalc: false },
  { id: 117, category: "화학", question: "콜로이드 입자가 빛을 산란시켜 빛의 통로가 밝게 보이는 현상은?", options: ["틴들 현상", "브라운 운동", "투석", "엉김"], answer: "틴들 현상", isCalc: false },
  { id: 118, category: "화학", question: "콜로이드 입자가 용매 분자와 충돌하여 불규칙하게 움직이는 현상은?", options: ["틴들 현상", "브라운 운동", "전기 이동", "염석"], answer: "브라운 운동", isCalc: false },
  { id: 119, category: "화학", question: "열역학에서 계와 외계 사이의 에너지 출입을 포함한 총 에너지는?", options: ["엔탈피", "엔트로피", "자유 에너지", "내부 에너지"], answer: "엔탈피", isCalc: false },
  { id: 120, category: "화학", question: "자연계의 변화는 항상 전체 ( )가 증가하는 방향으로 일어난다. 빈칸은?", options: ["엔탈피", "엔트로피", "밀도", "농도"], answer: "엔트로피", isCalc: false },
  { id: 121, category: "화학", question: "일정한 온도와 압력에서 반응의 자발성을 결정하는 기준은?", options: ["엔탈피 변화", "깁스 자유 에너지 변화", "엔트로피 변화", "온도 변화"], answer: "깁스 자유 에너지 변화", isCalc: false },
  { id: 122, category: "화학", question: "ΔG < 0 인 반응은 어떤 반응인가?", options: ["자발적 반응", "비자발적 반응", "평형 상태", "반응하지 않음"], answer: "자발적 반응", isCalc: false },
  { id: 123, category: "화학", question: "화학 평형 상수는 온도에 따라 변한다. (참/거짓)", options: ["참", "거짓"], answer: "참", isCalc: false },
  { id: 124, category: "화학", question: "브뢴스테드-로우리 정의에서 산으로부터 수소 이온이 빠져나간 형태는?", options: ["짝산", "짝염기", "강산", "약염기"], answer: "짝염기", isCalc: false },
  { id: 125, category: "화학", question: "물과 같이 상황에 따라 산으로도, 염기로도 작용하는 물질은?", options: ["중성 물질", "양쪽성 물질", "지시약", "완충액"], answer: "양쪽성 물질", isCalc: false },
  { id: 126, category: "화학", question: "25°C 물의 이온 곱 상수(Kw) 값은?", options: ["1.0 x 10⁻⁷", "1.0 x 10⁻¹⁴", "7.0", "14.0"], answer: "1.0 x 10⁻¹⁴", isCalc: true },
  { id: 127, category: "화학", question: "강산과 약염기가 중화 반응을 하여 생성된 염의 수용액은 어떤 액성을 띠는가?", options: ["산성", "중성", "염기성", "알칼리성"], answer: "산성", isCalc: false },
  { id: 128, category: "화학", question: "산-염기 적정에서 중화점을 확인하기 위해 사용하는 물질은?", options: ["촉매", "용매", "지시약", "흡착제"], answer: "지시약", isCalc: false },
  { id: 129, category: "화학", question: "페놀프탈레인 용액이 염기성에서 나타내는 색은?", options: ["무색", "노란색", "붉은색", "파란색"], answer: "붉은색", isCalc: false },
  { id: 130, category: "화학", question: "메틸 오렌지 지시약이 산성에서 나타내는 색은?", options: ["노란색", "붉은색", "파란색", "무색"], answer: "붉은색", isCalc: false },
  { id: 131, category: "화학", question: "전자를 잘 내놓아 상대방을 환원시키기 쉬운 금속의 성질은?", options: ["이온화 경향", "전기 음성도", "전자 친화도", "친화력"], answer: "이온화 경향", isCalc: false },
  { id: 132, category: "화학", question: "화학 전지에서 산화 반응이 일어나는 전극은?", options: ["(+)극", "(-)극"], answer: "(-)극", isCalc: false },
  { id: 133, category: "화학", question: "화학 전지에서 환원 반응이 일어나는 전극은?", options: ["(+)극", "(-)극"], answer: "(+)극", isCalc: false },
  { id: 134, category: "화학", question: "두 전극 사이의 전위차를 무엇이라 하는가?", options: ["전류", "기전력(전지 전압)", "저항", "전하량"], answer: "기전력(전지 전압)", isCalc: false },
  { id: 135, category: "화학", question: "기준이 되는 수소 전극의 표준 환원 전위 값은?", options: ["0 V", "1 V", "-1 V", "1.23 V"], answer: "0 V", isCalc: false },
  { id: 136, category: "화학", question: "충전하여 다시 사용할 수 있는 전지를 무엇이라 하는가?", options: ["1차 전지", "2차 전지", "연료 전지", "건전지"], answer: "2차 전지", isCalc: false },
  { id: 137, category: "화학", question: "수소와 산소의 화학 반응을 통해 직접 전기 에너지를 얻는 전지는?", options: ["납축전지", "리튬 이온 전지", "연료 전지", "수은 전지"], answer: "연료 전지", isCalc: false },
  { id: 138, category: "화학", question: "금속 표면에 다른 금속을 얇게 입히는 전기 분해의 응용은?", options: ["제련", "도금", "에칭", "합금"], answer: "도금", isCalc: false },
  { id: 139, category: "화학", question: "화학 반응의 차수는 실험을 통해서만 결정할 수 있다. (참/거짓)", options: ["참", "거짓"], answer: "참", isCalc: false },
  { id: 140, category: "화학", question: "반응 속도가 농도에 비례하는 반응은 몇 차 반응인가?", options: ["0차", "1차", "2차", "3차"], answer: "1차", isCalc: false },
  { id: 141, category: "화학", question: "가장 간단한 유기 화합물인 메테인의 분자식은?", options: ["CH₄", "C₂H₆", "C₃H₈", "CO₂"], answer: "CH₄", isCalc: false },
  { id: 142, category: "화학", question: "포화 탄화수소인 알케인의 일반식은?", options: ["CnH2n", "CnH2n+2", "CnH2n-2", "CnHn"], answer: "CnH2n+2", isCalc: true },
  { id: 143, category: "화학", question: "에테인의 탄소 사이 결합은 어떤 결합인가?", options: ["단일 결합", "이중 결합", "삼중 결합", "공유 안 함"], answer: "단일 결합", isCalc: false },
  { id: 144, category: "화학", question: "에틸렌(에텐)의 탄소 사이 결합은 어떤 결합인가?", options: ["단일 결합", "이중 결합", "삼중 결합", "이온 결합"], answer: "이중 결합", isCalc: false },
  { id: 145, category: "화학", question: "아세틸렌(에타인)의 탄소 사이 결합은 어떤 결합인가?", options: ["단일 결합", "이중 결합", "삼중 결합", "배위 결합"], answer: "삼중 결합", isCalc: false },
  { id: 146, category: "화학", question: "알코올의 작용기 이름은?", options: ["카보닐기", "하이드록시기", "카복실기", "아미노기"], answer: "하이드록시기", isCalc: false },
  { id: 147, category: "화학", question: "식초의 주성분인 유기산은?", options: ["포름산", "아세트산", "시트르산", "젖산"], answer: "아세트산", isCalc: false },
  { id: 148, category: "화학", question: "아세트산의 작용기 이름은?", options: ["알데하이드기", "케톤기", "카복실기", "에테르기"], answer: "카복실기", isCalc: false },
  { id: 149, category: "화학", question: "유기 화합물 중 은거울 반응을 일으키는 작용기는?", options: ["알코올", "알데하이드", "에스테르", "아민"], answer: "알데하이드", isCalc: false },
  { id: 150, category: "화학", question: "과일 향기가 나며 향료로 쓰이는 화합물 부류는?", options: ["에테르", "에스테르", "알데하이드", "케톤"], answer: "에스테르", isCalc: false }
];export const chemistry_Part4 = [
  { id: 151, category: "화학", question: "주양자수(n)가 3인 전자 껍질에는 총 몇 개의 오비탈이 존재하는가?", options: ["3개", "6개", "9개", "18개"], answer: "9개", isCalc: true },
  { id: 152, category: "화학", question: "자기 양자수(ml)는 오비탈의 무엇을 결정하는가?", options: ["에너지 준위", "모양", "공간적 방향", "스핀 방향"], answer: "공간적 방향", isCalc: false },
  { id: 153, category: "화학", question: "분자 간 힘이 가장 강하여 끓는점이 가장 높을 것으로 예상되는 물질은?", options: ["CH₄", "NH₃", "HCl", "H₂"], answer: "NH₃", isCalc: false },
  { id: 154, category: "화학", question: "표면 장력이 큰 액체의 특징으로 옳은 것은?", options: ["분자 간 인력이 강하다", "휘발성이 크다", "증기 압력이 높다", "온도가 높을수록 커진다"], answer: "분자 간 인력이 강하다", isCalc: false },
  { id: 155, category: "화학", question: "비결정성 고체의 예로 적절한 것은?", options: ["NaCl", "유리", "다이아몬드", "드라이아이스"], answer: "유리", isCalc: false },
  { id: 156, category: "화학", question: "10% 포도당 수용액 200g에 녹아 있는 포도당의 질량은?", options: ["10g", "20g", "100g", "200g"], answer: "20g", isCalc: true },
  { id: 157, category: "화학", question: "가역 반응에서 생성물의 농도 지수승의 곱을 반응물의 농도 지수승의 곱으로 나눈 값은?", options: ["반응 속도", "평형 상수", "활성화 에너지", "엔탈피"], answer: "평형 상수", isCalc: false },
  { id: 158, category: "화학", question: "발열 반응에서 온도를 높이면 평형은 어느 방향으로 이동하는가?", options: ["정반응 방향", "역반응 방향", "이동하지 않는다", "무작위"], answer: "역반응 방향", isCalc: false },
  { id: 159, category: "화학", question: "루이스 산의 정의로 옳은 것은?", options: ["H+를 내놓는 물질", "OH-를 내놓는 물질", "비공유 전자쌍을 받는 물질", "전자쌍을 기여하는 물질"], answer: "비공유 전자쌍을 받는 물질", isCalc: false },
  { id: 160, category: "화학", question: "강산의 짝염기는 어떤 성질을 띠는가?", options: ["강한 염기성", "매우 약한 염기성", "중성", "강한 산성"], answer: "매우 약한 염기성", isCalc: false },
  { id: 161, category: "화학", question: "산화수가 0인 원소 상태의 질소(N₂)에서 질소의 산화수는?", options: ["-3", "0", "+3", "+5"], answer: "0", isCalc: true },
  { id: 162, category: "화학", question: "과망가니즈산 칼륨(KMnO₄)에서 Mn의 산화수는?", options: ["+2", "+4", "+6", "+7"], answer: "+7", isCalc: true },
  { id: 163, category: "화학", question: "표준 환원 전위가 클수록 전자를 얻어 환원되기 쉽다. (참/거짓)", options: ["참", "거짓"], answer: "참", isCalc: false },
  { id: 164, category: "화학", question: "납축전지의 방전 시 (-)극에서 일어나는 변화는?", options: ["Pb가 PbSO₄로 산화", "PbO₂가 PbSO₄로 환원", "Pb가 PbO₂로 산화", "H₂SO₄가 생성"], answer: "Pb가 PbSO₄로 산화", isCalc: false },
  { id: 165, category: "화학", question: "물의 전기 분해 시 (+)극에서 발생하는 기체는?", options: ["수소", "산소", "질소", "염소"], answer: "산소", isCalc: false },
  { id: 166, category: "화학", question: "알루미늄을 제련할 때 산화 알루미늄의 녹는점을 낮추기 위해 사용하는 물질은?", options: ["석회석", "빙정석", "코크스", "형석"], answer: "빙정석", isCalc: false },
  { id: 167, category: "화학", question: "반응 속도식 v = k[A]²에서 반응 차수는?", options: ["0차", "1차", "2차", "3차"], answer: "2차", isCalc: true },
  { id: 168, category: "화학", question: "효소는 생체 내에서 어떤 역할을 하는 촉매인가?", options: ["정촉매", "부촉매", "용매", "억제제"], answer: "정촉매", isCalc: false },
  { id: 169, category: "화학", question: "탄소 수가 같은 알케인 중 끓는점이 가장 낮은 구조는?", options: ["직쇄형", "가지가 많은 형태", "고리형", "모두 같다"], answer: "가지가 많은 형태", isCalc: false },
  { id: 170, category: "화학", question: "시클로알케인의 일반식은?", options: ["CnH2n+2", "CnH2n", "CnH2n-2", "CnHn"], answer: "CnH2n", isCalc: true },
  { id: 171, category: "화학", question: "벤젠 분자 내의 탄소-탄소 결합 길이는 모두 같다. (참/거짓)", options: ["참", "거짓"], answer: "참", isCalc: false },
  { id: 172, category: "화학", question: "알코올을 산화시켜 알데하이드를 거쳐 최종적으로 생성되는 것은?", options: ["케톤", "에테르", "카복실산", "에스테르"], answer: "카복실산", isCalc: false },
  { id: 173, category: "화학", question: "메탄올을 섭취했을 때 체내에서 생성되는 독성 물질은?", options: ["아세트알데하이드", "폼알데하이드", "아세톤", "폼산"], answer: "폼알데하이드", isCalc: false },
  { id: 174, category: "화학", question: "두 분자의 알코올에서 물이 빠져나가며 형성되는 화합물은?", options: ["에테르", "에스테르", "케톤", "알데하이드"], answer: "에테르", isCalc: false },
  { id: 175, category: "화학", question: "아세톤의 분류에 해당하는 것은?", options: ["알데하이드", "케톤", "카복실산", "아민"], answer: "케톤", isCalc: false },
  { id: 176, category: "화학", question: "카복실산과 알코올이 반응하여 물이 빠지며 생성되는 것은?", options: ["에테르", "에스테르", "아미드", "니트로화합물"], answer: "에스테르", isCalc: false },
  { id: 177, category: "화학", question: "단백질의 기본 단위인 아미노산에 반드시 포함된 두 작용기는?", options: ["하이드록시기, 카복실기", "아미노기, 카복실기", "아미노기, 알데하이드기", "케톤기, 에테르기"], answer: "아미노기, 카복실기", isCalc: false },
  { id: 178, category: "화학", question: "포도당과 과당은 서로 어떤 관계인가?", options: ["동소체", "동위 원소", "구조 이성질체", "기하 이성질체"], answer: "구조 이성질체", isCalc: false },
  { id: 179, category: "화학", question: "단당류 두 개가 결합하여 만들어진 당(예: 설탕)은?", options: ["다당류", "이당류", "삼당류", "고분자"], answer: "이당류", isCalc: false },
  { id: 180, category: "화학", question: "비누의 세척 원리에서 기름과 친한 부분을 무엇이라 하는가?", options: ["친수성", "친유성", "양쪽성", "극성"], answer: "친유성", isCalc: false },
  { id: 181, category: "화학", question: "합성 고분자 화합물인 나일론의 결합 방식은?", options: ["에스테르 결합", "아미드 결합", "에테르 결합", "이온 결합"], answer: "아미드 결합", isCalc: false },
  { id: 182, category: "화학", question: "열을 가하면 모양이 변하고 다시 녹는 플라스틱의 성질은?", options: ["열경화성", "열가소성", "탄성", "전성"], answer: "열가소성", isCalc: false },
  { id: 183, category: "화학", question: "고무의 탄성을 높이기 위해 유황을 첨가하는 공정은?", options: ["가황", "중합", "축합", "치환"], answer: "가황", isCalc: false },
  { id: 184, category: "화학", question: "핵산(DNA, RNA)의 구성 단위는?", options: ["아미노산", "뉴클레오타이드", "지방산", "글리세롤"], answer: "뉴클레오타이드", isCalc: false },
  { id: 185, category: "화학", question: "혈액 내 완충 체계의 주성분은?", options: ["HCl/NaCl", "H₂CO₃/HCO₃⁻", "NaOH/Na₂CO₃", "NH₃/NH₄Cl"], answer: "H₂CO₃/HCO₃⁻", isCalc: false },
  { id: 186, category: "화학", question: "배위 화합물에서 중심 금속 이온에 전자쌍을 제공하는 분자나 이온은?", options: ["리간드", "촉매", "킬레이트", "착이온"], answer: "리간드", isCalc: false },
  { id: 187, category: "화학", question: "메테인의 결합을 설명하기 위한 혼성 오비탈은?", options: ["sp", "sp²", "sp³", "dsp²"], answer: "sp³", isCalc: false },
  { id: 188, category: "화학", question: "이중 결합이나 삼중 결합에서 옆으로 겹쳐진 결합은?", options: ["시그마 결합", "파이 결합", "델타 결합", "수소 결합"], answer: "파이 결합", isCalc: false },
  { id: 189, category: "화학", question: "전이 금속 화합물이 다양한 색깔을 띠는 주된 원인은?", options: ["s-p 전이", "d-d 전자 전이", "핵의 진동", "전자 쌍 생성"], answer: "d-d 전자 전이", isCalc: false },
  { id: 190, category: "화학", question: "용액의 어는점이 낮아지는 정도는 용질의 종류와 관계가 없다. (참/거짓)", options: ["참", "거짓"], answer: "참", isCalc: false },
  { id: 191, category: "화학", question: "흑연이 전기를 통하는 이유는 자유롭게 이동하는 ( )가 있기 때문이다.", options: ["전자", "양성자", "중성자", "이온"], answer: "전자", isCalc: false },
  { id: 192, category: "화학", question: "기체 입자의 평균 운동 에너지는 무엇에만 비례하는가?", options: ["압력", "부피", "절대 온도", "분자량"], answer: "절대 온도", isCalc: false },
  { id: 193, category: "화학", question: "금속 결정에서 원자들이 체심에 하나 위치하는 구조는?", options: ["면심 입방 구조", "육방 조밀 구조", "체심 입방 구조", "단순 입방 구조"], answer: "체심 입방 구조", isCalc: false },
  { id: 194, category: "화학", question: "삼투압을 구하는 공식은?", options: ["CRT", "PV", "nRT", "mRT"], answer: "CRT", isCalc: true },
  { id: 195, category: "화학", question: "반응지수(Q)가 평형상수(K)보다 크면 반응은 역반응으로 진행된다. (참/거짓)", options: ["참", "거짓"], answer: "참", isCalc: false },
  { id: 196, category: "화학", question: "물(H₂O)의 자동 이온화 반응은 온도 상승 시 평형이 정반응 쪽으로 이동한다. (참/거짓)", options: ["참", "거짓"], answer: "참", isCalc: false },
  { id: 197, category: "화학", question: "염다리(Salt bridge)의 주요 역할은?", options: ["전류 증폭", "전기적 중성 유지", "온도 조절", "전극 보호"], answer: "전기적 중성 유지", isCalc: false },
  { id: 198, category: "화학", question: "반응 속도 상수와 온도의 관계를 나타내는 식은?", options: ["아레니우스 식", "네른스트 식", "깁스 식", "헨더슨 식"], answer: "아레니우스 식", isCalc: false },
  { id: 199, category: "화학", question: "풀러렌(C₆0)의 모양은?", options: ["원통형", "판상형", "축구공 모양", "정사면체"], answer: "축구공 모양", isCalc: false },
  { id: 200, category: "화학", question: "알켄에 수소를 첨가하는 반응은 어떤 반응인가?", options: ["치환 반응", "첨가 반응", "제거 반응", "축합 반응"], answer: "첨가 반응", isCalc: false }
];export const chemistry_Part5 = [
  { id: 201, category: "화학", question: "화합물을 구성하는 원소들의 질량 백분율을 통해 구한 가장 간단한 화학식은?", options: ["분자식", "실험식", "구조식", "시성식"], answer: "실험식", isCalc: false },
  { id: 202, category: "화학", question: "용액 속에 녹아 있는 이온을 침전시켜 성분을 확인하는 분석법은?", options: ["정성 분석", "정량 분석", "크로마토그래피", "전기 이동"], answer: "정성 분석", isCalc: false },
  { id: 203, category: "화학", question: "시료 성분이 고정상과 이동상 사이의 친화력 차이로 분리되는 방법은?", options: ["증류", "여과", "크로마토그래피", "추출"], answer: "크로마토그래피", isCalc: false },
  { id: 204, category: "화학", question: "염화 은(AgCl) 침전물의 색깔은?", options: ["노란색", "검은색", "흰색", "푸른색"], answer: "흰색", isCalc: false },
  { id: 205, category: "화학", question: "알칼리 금속의 불꽃 반응 색 중 리튬(Li)의 색깔은?", options: ["노란색", "보라색", "빨간색", "주황색"], answer: "빨간색", isCalc: false },
  { id: 206, category: "화학", question: "황산 구리(II) 수용액이 푸른색을 띠는 이유는 어떤 이온 때문인가?", options: ["SO₄²⁻", "Cu²⁺", "H⁺", "OH⁻"], answer: "Cu²⁺", isCalc: false },
  { id: 207, category: "화학", question: "전이 금속의 d 오비탈이 리간드에 의해 에너지 준위가 갈라지는 이론은?", options: ["원자가 결합 이론", "결정장 이론", "분자 오비탈 이론", "VSEPR 이론"], answer: "결정장 이론", isCalc: false },
  { id: 208, category: "화학", question: "착이온에서 리간드가 중심 금속과 결합할 때 제공하는 것은?", options: ["양성자", "전자쌍", "중성자", "원자핵"], answer: "전자쌍", isCalc: false },
  { id: 209, category: "화학", question: "한 리간드가 두 개 이상의 배위 결합을 형성하는 현상을 무엇이라 하는가?", options: ["킬레이트 효과", "틴들 현상", "도플러 효과", "공명 현상"], answer: "킬레이트 효과", isCalc: false },
  { id: 210, category: "화학", question: "헤모글로빈의 중심에 있는 전이 금속 이온은?", options: ["마그네슘 이온", "철 이온", "구리 이온", "아연 이온"], answer: "철 이온", isCalc: false },
  { id: 211, category: "화학", question: "엽록소의 중심에 있는 금속 이온은?", options: ["철 이온", "마그네슘 이온", "칼슘 이온", "망가니즈 이온"], answer: "마그네슘 이온", isCalc: false },
  { id: 212, category: "화학", question: "가장 강한 산성도를 나타내는 pH 값은?", options: ["0", "7", "10", "14"], answer: "0", isCalc: true },
  { id: 213, category: "화학", question: "아세트산과 에탄올이 반응하여 생성되는 에스테르의 이름은?", options: ["아세트산 에틸", "폼산 메틸", "에틸 에테르", "아세트알데하이드"], answer: "아세트산 에틸", isCalc: false },
  { id: 214, category: "화학", question: "벤젠 고리에서 수소 하나가 -OH기로 치환된 화합물은?", options: ["벤알데하이드", "페놀", "톨루엔", "아닐린"], answer: "페놀", isCalc: false },
  { id: 215, category: "화학", question: "니트로벤젠을 환원시켜 얻으며 염료의 원료로 쓰이는 물질은?", options: ["페놀", "아닐린", "벤조산", "스티렌"], answer: "아닐린", isCalc: false },
  { id: 216, category: "화학", question: "유기 화학에서 'R-O-R'의 구조를 가진 화합물은?", options: ["에스테르", "케톤", "에테르", "알코올"], answer: "에테르", isCalc: false },
  { id: 217, category: "화학", question: "지방의 주성분으로 지방산과 결합하는 삼가 알코올은?", options: ["에탄올", "글리세롤", "메탄올", "에틸렌글리콜"], answer: "글리세롤", isCalc: false },
  { id: 218, category: "화학", question: "단백질이 변성될 때 파괴되지 않는 결합은?", options: ["수소 결합", "펩타이드 결합", "이온 결합", "소수성 상호작용"], answer: "펩타이드 결합", isCalc: false },
  { id: 219, category: "화학", question: "DNA의 염기 쌍 중 구아닌(G)과 항상 결합하는 염기는?", options: ["아데닌(A)", "티민(T)", "사이토신(C)", "우라실(U)"], answer: "사이토신(C)", isCalc: false },
  { id: 220, category: "화학", question: "RNA에만 존재하고 DNA에는 없는 염기는?", options: ["아데닌", "구아닌", "사이토신", "우라실"], answer: "우라실", isCalc: false },
  { id: 221, category: "화학", question: "화학 반응의 자발성을 나타내는 ΔG = ΔH - TΔS 식의 이름은?", options: ["헤스 법칙", "깁스-헬름홀츠 식", "아레니우스 식", "라울의 법칙"], answer: "깁스-헬름홀츠 식", isCalc: false },
  { id: 222, category: "화학", question: "표준 상태에서 원소로부터 화합물 1몰이 생성될 때의 엔탈피 변화는?", options: ["연소 엔탈피", "생성 엔탈피", "해리 엔탈피", "중화 엔탈피"], answer: "생성 엔탈피", isCalc: false },
  { id: 223, category: "화학", question: "용액의 증기 압력이 낮아지면 끓는점은 어떻게 되는가?", options: ["낮아진다", "높아진다", "변함없다", "0이 된다"], answer: "높아진다", isCalc: false },
  { id: 224, category: "화학", question: "이상 기체 상태 방정식에서 기체 상수 R의 단위에 포함되지 않는 것은?", options: ["atm", "L", "mol", "gram"], answer: "gram", isCalc: false },
  { id: 225, category: "화학", question: "전기 음성도 차이가 매우 큰 두 원소 사이의 결합은 주로 어떤 결합인가?", options: ["이온 결합", "무극성 공유 결합", "금속 결합", "수소 결합"], answer: "이온 결합", isCalc: false },
  { id: 226, category: "화학", question: "공유 전자쌍이 한쪽 원자로 치환되어 극성을 띠는 결합은?", options: ["무극성 공유 결합", "극성 공유 결합", "배위 결합", "이온 결합"], answer: "극성 공유 결합", isCalc: false },
  { id: 227, category: "화학", question: "중심 원자에 비공유 전자쌍이 있으면 분자의 모양은 대칭이 깨지기 쉽다. (참/거짓)", options: ["참", "거짓"], answer: "참", isCalc: false },
  { id: 228, category: "화학", question: "NF₃ 분자는 극성 분자인가 무극성 분자인가?", options: ["극성 분자", "무극성 분자"], answer: "극성 분자", isCalc: false },
  { id: 229, category: "화학", question: "BF₃ 분자는 평면 삼각형 구조를 가지며 무극성이다. (참/거짓)", options: ["참", "거짓"], answer: "참", isCalc: false },
  { id: 230, category: "화학", question: "물의 밀도가 얼음보다 큰 이유는 무엇 때문인가?", options: ["수소 결합에 의한 빈 공간", "이온 결합", "자유 전자", "분산력"], answer: "수소 결합에 의한 빈 공간", isCalc: false },
  { id: 231, category: "화학", question: "분자량이 비슷한 경우 끓는점이 가장 높은 화합물 부류는?", options: ["알케인", "에테르", "알코올", "알데하이드"], answer: "알코올", isCalc: false },
  { id: 232, category: "화학", question: "수용액에서 이온화도가 커서 수소 이온을 많이 내놓는 산은?", options: ["강산", "약산", "강염기", "약염기"], answer: "강산", isCalc: false },
  { id: 233, category: "화학", question: "용해도 곱 상수(Ksp)가 작을수록 침전이 잘 형성된다. (참/거짓)", options: ["참", "거짓"], answer: "참", isCalc: false },
  { id: 234, category: "화학", question: "산-염기 적정에서 지시약의 색이 변하는 지점은?", options: ["당량점", "종말점", "반응점", "임계점"], answer: "종말점", isCalc: false },
  { id: 235, category: "화학", question: "이론적으로 산의 당량과 염기의 당량이 정확히 같은 지점은?", options: ["당량점", "종말점", "중화점", "평형점"], answer: "당량점", isCalc: false },
  { id: 236, category: "화학", question: "강염기와 약산의 중화 적정 시 당량점에서의 pH 범위는?", options: ["pH < 7", "pH = 7", "pH > 7", "pH = 0"], answer: "pH > 7", isCalc: false },
  { id: 237, category: "화학", question: "산화수가 감소하는 것은 전자를 얻는 과정이다. (참/거짓)", options: ["참", "거짓"], answer: "참", isCalc: false },
  { id: 238, category: "화학", question: "연소 반응은 항상 어떤 반응의 일종인가?", options: ["산화-환원 반응", "중화 반응", "침전 반응", "치환 반응"], answer: "산화-환원 반응", isCalc: false },
  { id: 239, category: "화학", question: "전기 전도성이 있는 액체 상태의 화합물을 전극을 통해 분해하는 것은?", options: ["전기 분해", "화학 전지", "증류", "승화"], answer: "전기 분해", isCalc: false },
  { id: 240, category: "화학", question: "전기 분해 시 흐른 전하량과 석출되는 물질의 양 사이의 관계를 밝힌 법칙은?", options: ["패러데이 법칙", "옴의 법칙", "뉴턴의 법칙", "라부아지에 법칙"], answer: "패러데이 법칙", isCalc: false },
  { id: 241, category: "화학", question: "1차 알코올을 산화하면 처음에 무엇이 되는가?", options: ["케톤", "에테르", "알데하이드", "카복실산"], answer: "알데하이드", isCalc: false },
  { id: 242, category: "화학", question: "2차 알코올을 산화하면 무엇이 되는가?", options: ["알데하이드", "케톤", "카복실산", "에스테르"], answer: "케톤", isCalc: false },
  { id: 243, category: "화학", question: "3차 알코올은 쉽게 산화되지 않는다. (참/거짓)", options: ["참", "거짓"], answer: "참", isCalc: false },
  { id: 244, category: "화학", question: "카복실산과 아민이 반응하여 물이 빠지면서 형성되는 결합은?", options: ["에스테르 결합", "아미드 결합", "에테르 결합", "글리코사이드 결합"], answer: "아미드 결합", isCalc: false },
  { id: 245, category: "화학", question: "포도당의 선형 구조에서 고리 구조로 변할 때 생성되는 작용기는?", options: ["헤미아세탈", "케톤", "에테르", "에스테르"], answer: "헤미아세탈", isCalc: false },
  { id: 246, category: "화학", question: "거울상 이성질체를 갖기 위해 탄소 원자에 결합된 4개의 원자단은 모두 ( )야 한다.", options: ["같아", "달라", "무거워", "가벼워"], answer: "달라", isCalc: false },
  { id: 247, category: "화학", question: "카이랄(Chiral) 중심 탄소를 가진 분자는 광학 활성을 나타낸다. (참/거짓)", options: ["참", "거짓"], answer: "참", isCalc: false },
  { id: 248, category: "화학", question: "용액에서 농도에 따른 빛의 흡수 정도를 나타내는 법칙은?", options: ["비어-람베르트 법칙", "헨리 법칙", "라울 법칙", "헤스 법칙"], answer: "비어-람베르트 법칙", isCalc: false },
  { id: 249, category: "화학", question: "원자 스펙트럼이 불연속적인 선으로 나타나는 것은 에너지의 ( ) 때문이다.", options: ["연속성", "양자화", "소멸", "증폭"], answer: "양자화", isCalc: false },
  { id: 250, category: "화학", question: "화학 평형 상태에서 정반응 속도는 0이다. (참/거짓)", options: ["참", "거짓"], answer: "거짓", isCalc: false }
];export const chemistry_Part6 = [
  { id: 251, category: "화학", question: "분자 오비탈 이론(MOT)에서 결합성 오비탈은 반결합성 오비탈보다 에너지가 ( ).", options: ["높다", "낮다", "같다", "0이다"], answer: "낮다", isCalc: false },
  { id: 252, category: "화학", question: "산소 분자(O₂)가 자성을 띠는 이유는 무엇 때문인가?", options: ["홀전자 존재", "모든 전자 쌍을 이룸", "수소 결합", "금속 결합"], answer: "홀전자 존재", isCalc: false },
  { id: 253, category: "화학", question: "표준 환원 전위가 (-)값이 큰 금속일수록 산화되기가 ( ).", options: ["쉽다", "어렵다"], answer: "쉽다", isCalc: false },
  { id: 254, category: "화학", question: "비자발적인 반응을 강제로 일으키는 전기 분해에서 (-)극의 반응은?", options: ["산화 반응", "환원 반응", "중화 반응", "연소 반응"], answer: "환원 반응", isCalc: false },
  { id: 255, category: "화학", question: "반응 속도가 농도의 제곱에 비례하면 몇 차 반응인가?", options: ["0차", "1차", "2차", "3차"], answer: "2차", isCalc: true },
  { id: 256, category: "화학", question: "반응의 반감기가 초기 농도에 반비례하는 반응 차수는?", options: ["0차", "1차", "2차", "3차"], answer: "2차", isCalc: true },
  { id: 257, category: "화학", question: "중심 원자에 결합된 리간드를 다른 리간드로 바꾸는 반응은?", options: ["치환 반응", "첨가 반응", "제거 반응", "재배열 반응"], answer: "치환 반응", isCalc: false },
  { id: 258, category: "화학", question: "착이온의 기하 구조 중 배위수가 6일 때의 모양은?", options: ["정사면체", "평면 사각형", "정팔면체", "직선형"], answer: "정팔면체", isCalc: false },
  { id: 259, category: "화학", question: "광학 이성질체를 구분할 때 사용하는 빛의 성질은?", options: ["평면 편광", "회절", "굴절", "산란"], answer: "평면 편광", isCalc: false },
  { id: 260, category: "화학", question: "나프탈렌 2개를 이어 붙인 것과 같은 구조의 방향족 화합물은?", options: ["안트라센", "나프탈렌", "안트라퀴논", "벤젠"], answer: "나프탈렌", isCalc: false },
  { id: 261, category: "화학", question: "알데하이드를 확인하는 반응으로 은이 석출되는 반응은?", options: ["요오드포름 반응", "은거울 반응", "뷰렛 반응", "크산토프로테인 반응"], answer: "은거울 반응", isCalc: false },
  { id: 262, category: "화학", question: "펩타이드 결합을 확인하기 위해 사용하는 시약은?", options: ["베네딕트 용액", "뷰렛 시약", "요오드 용액", "닌히드린 용액"], answer: "뷰렛 시약", isCalc: false },
  { id: 263, category: "화학", question: "단당류인 포도당과 과당이 결합한 이당류는?", options: ["엿당", "설탕", "젖당", "셀룰로오스"], answer: "설탕", isCalc: false },
  { id: 264, category: "화학", question: "녹말을 검출할 때 사용하는 요오드-요오드화 칼륨 용액의 색 변화는?", options: ["청람색", "선홍색", "황록색", "보라색"], answer: "청람색", isCalc: false },
  { id: 265, category: "화학", question: "비누화 반응은 유지(지방)를 무엇과 반응시키는 것인가?", options: ["산", "강염기", "알코올", "물"], answer: "강염기", isCalc: false },
  { id: 266, category: "화학", question: "합성 세제가 비누보다 유리한 점은 센물에서도 세척력이 좋다는 것이다. (참/거짓)", options: ["참", "거짓"], answer: "참", isCalc: false },
  { id: 267, category: "화학", question: "폴리에틸렌(PE)은 어떤 중합 반응으로 생성되는가?", options: ["축합 중합", "첨가 중합", "개환 중합", "공중합"], answer: "첨가 중합", isCalc: false },
  { id: 268, category: "화학", question: "페트병의 원료인 PET는 에스테르 결합이 반복되는 고분자이다. (참/거짓)", options: ["참", "거짓"], answer: "참", isCalc: false },
  { id: 269, category: "화학", question: "분자량이 매우 큰 고분자 화합물은 끓는점이 일정하지 않다. (참/거짓)", options: ["참", "거짓"], answer: "참", isCalc: false },
  { id: 270, category: "화학", question: "원자핵이 분열하거나 합쳐질 때 발생하는 에너지를 이용하는 화학 분야는?", options: ["유기화학", "핵화학", "분석화학", "생화학"], answer: "핵화학", isCalc: false },
  { id: 271, category: "화학", question: "질량수가 큰 핵이 중성자를 흡수하여 두 개의 작은 핵으로 나뉘는 것은?", options: ["핵융합", "핵분열", "알파 붕괴", "베타 붕괴"], answer: "핵분열", isCalc: false },
  { id: 272, category: "화학", question: "가벼운 원자핵들이 합쳐져 더 무거운 핵이 되는 반응은?", options: ["핵분열", "핵융합", "감마 붕괴", "전자 포획"], answer: "핵융합", isCalc: false },
  { id: 273, category: "화학", question: "핵분열 연쇄 반응을 조절하기 위해 원자로에서 중성자를 흡수하는 장치는?", options: ["냉각재", "감속재", "제어봉", "반사재"], answer: "제어봉", isCalc: false },
  { id: 274, category: "화학", question: "방사성 탄소 연대 측정법에 주로 사용되는 동위 원소는?", options: ["C-12", "C-13", "C-14", "N-14"], answer: "C-14", isCalc: false },
  { id: 275, category: "화학", question: "전기 전도성이 구리보다 뛰어나고 강도가 강한 평면 탄소 신소재는?", options: ["풀러렌", "탄소 나노튜브", "그래핀", "실리콘"], answer: "그래핀", isCalc: false },
  { id: 276, category: "화학", question: "특정 온도 이하에서 저항이 0이 되는 물질은?", options: ["반도체", "초전도체", "절연체", "강자성체"], answer: "초전도체", isCalc: false },
  { id: 277, category: "화학", question: "액정(LCD)은 액체와 ( )의 중간 성질을 가진다.", options: ["기체", "고체", "플라스마", "중성자"], answer: "고체", isCalc: false },
  { id: 278, category: "화학", question: "나노 기술은 물질을 ( )m 수준에서 다루는 기술이다.", options: ["10⁻⁶", "10⁻⁹", "10⁻¹²", "10⁻³"], answer: "10⁻⁹", isCalc: true },
  { id: 279, category: "화학", question: "환경 오염을 줄이고 자원을 아끼는 방향의 화학을 무엇이라 하는가?", options: ["녹색 화학", "청색 화학", "물리 화학", "공업 화학"], answer: "녹색 화학", isCalc: false },
  { id: 280, category: "화학", question: "지구 온난화의 주범으로 지목되는 온실가스는?", options: ["산소", "이산화 탄소", "질소", "아르곤"], answer: "이산화 탄소", isCalc: false },
  { id: 281, category: "화학", question: "오존층을 파괴하는 대표적인 물질인 프레온 가스의 화학명은?", options: ["CFC", "DDT", "PVC", "TNT"], answer: "CFC", isCalc: false },
  { id: 282, category: "화학", question: "산성비의 원인이 되는 주요 산성 산화물은?", options: ["SOx, NOx", "CO₂, H₂O", "CH₄, NH₃", "He, Ne"], answer: "SOx, NOx", isCalc: false },
  { id: 283, category: "화학", question: "기체 상수 R의 값(0.082)은 단위가 L·atm/(mol·K)일 때이다. (참/거짓)", options: ["참", "거짓"], answer: "참", isCalc: true },
  { id: 284, category: "화학", question: "용질이 용해될 때 엔트로피가 감소하는 경우도 있다. (참/거짓)", options: ["참", "거짓"], answer: "참", isCalc: false },
  { id: 285, category: "화학", question: "네른스트 식은 무엇과 전지 전위 사이의 관계를 나타내는가?", options: ["온도", "농도(이온 농도)", "압력", "표면적"], answer: "농도(이온 농도)", isCalc: false },
  { id: 286, category: "화학", question: "반응 속도 결정 단계는 여러 단계 반응 중 가장 ( ) 단계이다.", options: ["빠른", "느린", "중간인", "복잡한"], answer: "느린", isCalc: false },
  { id: 287, category: "화학", question: "활성화 에너지가 0보다 작은 반응은 존재할 수 없다. (참/거짓)", options: ["참", "거짓"], answer: "참", isCalc: false },
  { id: 288, category: "화학", question: "반데르발스 방정식은 실제 기체의 ( )과 부피를 보정한다.", options: ["질량", "인력", "색깔", "밀도"], answer: "인력", isCalc: false },
  { id: 289, category: "화학", question: "콜로이드 용액에 전극을 넣었을 때 입자가 한쪽 전극으로 이동하는 것은?", options: ["전기 분해", "전기 이동", "투석", "엉김"], answer: "전기 이동", isCalc: false },
  { id: 290, category: "화학", question: "수산화 알루미늄과 같이 산과 염기 모두와 반응하는 물질은?", options: ["중성 물질", "양쪽성 물질", "표준 물질", "완충 물질"], answer: "양쪽성 물질", isCalc: false },
  { id: 291, category: "화학", question: "물질의 상태 변화 중 열을 가장 많이 방출하는 과정은?", options: ["기화", "액화", "승화(기->고)", "융해"], answer: "승화(기->고)", isCalc: false },
  { id: 292, category: "화학", question: "공유 결정인 이산화 규소(SiO₂)의 일반적인 명칭은?", options: ["소금", "석영(수정)", "드라이아이스", "가성소다"], answer: "석영(수정)", isCalc: false },
  { id: 293, category: "화학", question: "금속의 연성과 전성을 설명하는 데 가장 적합한 모델은?", options: ["전자 바다 모델", "옥텟 규칙", "공유 결합 모델", "VSEPR 모델"], answer: "전자 바다 모델", isCalc: false },
  { id: 294, category: "화학", question: "표준 수소 전극의 반쪽 반응식에서 기체 수소의 압력 기준은?", options: ["0.5 atm", "1 atm", "2 atm", "10 atm"], answer: "1 atm", isCalc: false },
  { id: 295, category: "화학", question: "아미노산이 이온화되어 전하의 합이 0이 되는 pH를 무엇이라 하는가?", options: ["중화점", "등전점", "당량점", "임계점"], answer: "등전점", isCalc: false },
  { id: 296, category: "화학", question: "알칼리 토금속은 주기율표의 몇 족인가?", options: ["1족", "2족", "13족", "14족"], answer: "2족", isCalc: false },
  { id: 297, category: "화학", question: "란타넘족과 악티늄족은 주기율표의 어느 블록에 속하는가?", options: ["s-블록", "p-블록", "d-블록", "f-블록"], answer: "f-블록", isCalc: false },
  { id: 298, category: "화학", question: "빛의 파장이 길수록 에너지(E=hf)는 어떻게 되는가?", options: ["커진다", "작아진다", "변함없다", "0이 된다"], answer: "작아진다", isCalc: true },
  { id: 299, category: "화학", question: "화학 결합의 에너지가 방출될 때 주위 온도는 어떻게 되는가?", options: ["내려간다", "올라간다", "변함없다", "알 수 없다"], answer: "올라간다", isCalc: false },
  { id: 300, category: "화학", question: "현대 화학의 아버지로 불리며 질량 보존 법칙을 확립한 과학자는?", options: ["보일", "라부아지에", "아보가드로", "달턴"], answer: "라부아지에", isCalc: false }
];