export const earthScience_Part1 = [
  { id: 1, category: "지구과학", question: "지구 내부 구조 중 부피가 가장 큰 층은?", options: ["지각", "맨틀", "외핵", "내핵"], answer: "맨틀", isCalc: false },
  { id: 2, category: "지구과학", question: "지구 내부 구조 중 유일하게 액체 상태로 추정되는 층은?", options: ["지각", "맨틀", "외핵", "내핵"], answer: "외핵", isCalc: false },
  { id: 3, category: "지구과학", question: "대륙 이동설을 처음으로 주장한 과학자는?", options: ["베게너", "홈스", "헤스", "윌슨"], answer: "베게너", isCalc: false },
  { id: 4, category: "지구과학", question: "과거에 모든 대륙이 하나로 합쳐져 있었던 거대 대륙의 이름은?", options: ["판게아", "로디니아", "고드와나", "로라시아"], answer: "판게아", isCalc: false },
  { id: 5, category: "지구과학", question: "맨틀 내의 열대류가 지각 변동의 원인이라고 설명하는 이론은?", options: ["대륙 이동설", "맨틀 대류설", "해저 확장설", "판 구조론"], answer: "맨틀 대류설", isCalc: false },
  { id: 6, category: "지구과학", question: "해령을 중심으로 해저 지각이 양옆으로 넓어진다는 이론은?", options: ["해저 확장설", "대륙 이동설", "수축설", "빙하설"], answer: "해저 확장설", isCalc: false },
  { id: 7, category: "지구과학", question: "지구 겉부분이 여러 개의 판으로 이루어져 이동한다는 현대의 이론은?", options: ["판 구조론", "맨틀 대류설", "해구 이동설", "지향사설"], answer: "판 구조론", isCalc: false },
  { id: 8, category: "지구과학", question: "두 판이 서로 멀어지는 경계로 새로운 지각이 생성되는 곳은?", options: ["발산형 경계", "수렴형 경계", "보존형 경계", "충돌형 경계"], answer: "발산형 경계", isCalc: false },
  { id: 9, category: "지구과학", question: "두 판이 서로 어긋나게 이동하며 지각이 생성되거나 소멸되지 않는 경계는?", options: ["해구", "변환 단층", "습곡 산맥", "열곡대"], answer: "변환 단층", isCalc: false },
  { id: 10, category: "지구과학", question: "밀도가 큰 해양판이 대륙판 아래로 파고들어 지각이 소멸되는 곳은?", options: ["해령", "해구", "열곡", "습곡"], answer: "해구", isCalc: false },
  { id: 11, category: "지구과학", question: "마그마가 지하 깊은 곳에서 천천히 식어 굳어진 암석은?", options: ["화산암", "심성암", "퇴적암", "변성암"], answer: "심성암", isCalc: false },
  { id: 12, category: "지구과학", question: "화강암은 다음 중 어느 암석에 해당하는가?", options: ["화산암", "심성암", "유기적 퇴적암", "엽리암"], answer: "심성암", isCalc: false },
  { id: 13, category: "지구과학", question: "화산암의 대표적인 예로, 우리나라 제주도에 많이 분포하는 암석은?", options: ["현무암", "화강암", "편마암", "석회암"], answer: "현무암", isCalc: false },
  { id: 14, category: "지구과학", question: "풍화 침식된 쇄설물이나 생물의 유해 등이 쌓여 만들어진 암석은?", options: ["화성암", "퇴적암", "변성암", "심성암"], answer: "퇴적암", isCalc: false },
  { id: 15, category: "지구과학", question: "퇴적암에서 나타나는 줄무늬 구조를 무엇이라 하는가?", options: ["엽리", "층리", "절리", "단층"], answer: "층리", isCalc: false },
  { id: 16, category: "지구과학", question: "기존의 암석이 높은 열과 압력을 받아 성질이 변한 암석은?", options: ["화성암", "퇴적암", "변성암", "수성암"], answer: "변성암", isCalc: false },
  { id: 17, category: "지구과학", question: "변성암에서 압력 방향에 수직으로 나타나는 줄무늬 구조는?", options: ["층리", "엽리", "절리", "사층리"], answer: "엽리", isCalc: false },
  { id: 18, category: "지구과학", question: "석회암이 변성 작용을 받아 만들어진 암석은?", options: ["대리암", "편마암", "규암", "점판암"], answer: "대리암", isCalc: false },
  { id: 19, category: "지구과학", question: "지각을 구성하는 8대 원소 중 가장 많은 양을 차지하는 원소는?", options: ["규소", "철", "산소", "알루미늄"], answer: "산소", isCalc: false },
  { id: 20, category: "지구과학", question: "광물의 단단한 정도를 비교하는 척도는?", options: ["조흔색", "굳기(모스 굳기계)", "결정형", "비중"], answer: "굳기(모스 굳기계)", isCalc: false },
  { id: 21, category: "지구과학", question: "모스 굳기계에서 가장 단단한(굳기 10) 광물은?", options: ["석영", "방해석", "금강석(다이아몬드)", "활석"], answer: "금강석(다이아몬드)", isCalc: false },
  { id: 22, category: "지구과학", question: "염산과 반응하여 이산화 탄소 기체를 발생시키는 광물은?", options: ["석영", "방해석", "흑운모", "장석"], answer: "방해석", isCalc: false },
  { id: 23, category: "지구과학", question: "지진이 발생한 근원 지점을 무엇이라 하는가?", options: ["진앙", "진원", "단층면", "지진대"], answer: "진원", isCalc: false },
  { id: 24, category: "지구과학", question: "지진파 중 속도가 가장 빠르며 고체, 액체, 기체를 모두 통과하는 파는?", options: ["P파", "S파", "L파", "M파"], answer: "P파", isCalc: false },
  { id: 25, category: "지구과학", question: "지진파 중 속도는 느리지만 피해가 크며 고체만 통과하는 파는?", options: ["P파", "S파", "L파", "가시광선"], answer: "S파", isCalc: false },
  { id: 26, category: "지구과학", question: "지진의 절대적인 에너지 양을 나타내는 단위는?", options: ["진도", "규모", "데시벨", "헤르츠"], answer: "규모", isCalc: false },
  { id: 27, category: "지구과학", question: "관측 지점에서 느낀 흔들림의 정도나 피해 정도를 나타내는 단위는?", options: ["규모", "진도", "마하", "노트"], answer: "진도", isCalc: false },
  { id: 28, category: "지구과학", question: "지층이 양옆에서 미는 힘(횡압력)을 받아 물결 모양으로 휘어진 구조는?", options: ["단층", "습곡", "부정합", "절리"], answer: "습곡", isCalc: false },
  { id: 29, category: "지구과학", question: "지층이 끊어져 어긋나 있는 구조를 무엇이라 하는가?", options: ["습곡", "단층", "부정합", "베니오프대"], answer: "단층", isCalc: false },
  { id: 30, category: "지구과학", question: "상반이 하반보다 위로 밀려 올라간 단층은?", options: ["정단층", "역단층", "주향 이동 단층", "수평 단층"], answer: "역단층", isCalc: false },
  { id: 31, category: "지구과학", question: "퇴적이 중단되었다가 긴 시간이 흐른 뒤 다시 쌓여 상하 지층이 큰 시간 간격을 갖는 구조는?", options: ["정합", "부정합", "층리", "엽리"], answer: "부정합", isCalc: false },
  { id: 32, category: "지구과학", question: "화산 가스의 성분 중 가장 많은 비중을 차지하는 것은?", options: ["이산화 탄소", "이산화 황", "수증기", "질소"], answer: "수증기", isCalc: false },
  { id: 33, category: "지구과학", question: "점성이 크고 유동성이 작은 마그마가 굳어 만들어진 종 모양의 화산은?", options: ["순상 화산", "종상 화산", "성층 화산", "칼데라"], answer: "종상 화산", isCalc: false },
  { id: 34, category: "지구과학", question: "화산 폭발 후 화구의 함몰로 만들어진 거대한 와지는?", options: ["분화구", "칼데라", "열곡", "해구"], answer: "칼데라", isCalc: false },
  { id: 35, category: "지구과학", question: "대륙 지각과 해양 지각 중 두께가 더 두꺼운 쪽은?", options: ["대륙 지각", "해양 지각"], answer: "대륙 지각", isCalc: false },
  { id: 36, category: "지구과학", question: "대륙 지각과 해양 지각 중 밀도가 더 큰 쪽은?", options: ["대륙 지각", "해양 지각"], answer: "해양 지각", isCalc: false },
  { id: 37, category: "지구과학", question: "지각과 맨틀의 경계면을 무엇이라 하는가?", options: ["모호면", "구텐베르크면", "레만면", "불연속면"], answer: "모호면", isCalc: false },
  { id: 38, category: "지구과학", question: "맨틀과 외핵의 경계면은?", options: ["모호면", "구텐베르크면", "레만면", "지각면"], answer: "구텐베르크면", isCalc: false },
  { id: 39, category: "지구과학", question: "지구 자기장이 형성되는 원인으로 추정되는 것은 외핵의 ( ) 운동이다.", options: ["대류", "회전", "전도", "복사"], answer: "대류", isCalc: false },
  { id: 40, category: "지구과학", question: "해양 지각의 연령은 해령에서 멀어질수록 어떻게 되는가?", options: ["젊어진다", "많아진다", "변함없다", "일정하다"], answer: "많아진다", isCalc: true },
  { id: 41, category: "지구과학", question: "지구의 나이는 약 얼마인가?", options: ["4.6만 년", "460만 년", "4.6억 년", "46억 년"], answer: "46억 년", isCalc: true },
  { id: 42, category: "지구과학", question: "과거 지질 시대에 살았던 생물의 유해나 흔적은?", options: ["화석", "암석", "광물", "퇴적물"], answer: "화석", isCalc: false },
  { id: 43, category: "지구과학", question: "특정 시대를 대표하며 생존 기간이 짧고 분포 면적이 넓은 화석은?", options: ["시상 화석", "표준 화석", "흔적 화석", "미화석"], answer: "표준 화석", isCalc: false },
  { id: 44, category: "지구과학", question: "삼엽충은 어느 지질 시대를 대표하는 표준 화석인가?", options: ["선캄브리아 시대", "고생대", "중생대", "신생대"], answer: "고생대", isCalc: false },
  { id: 45, category: "지구과학", question: "공룡과 암모나이트가 번성했던 지질 시대는?", options: ["고생대", "중생대", "신생대", "현세"], answer: "중생대", isCalc: false },
  { id: 46, category: "지구과학", question: "당시의 환경(온도, 습도 등)을 알려주는 화석은?", options: ["표준 화석", "시상 화석", "몰드", "캐스트"], answer: "시상 화석", isCalc: false },
  { id: 47, category: "지구과학", question: "산호 화석이 발견된 지층의 과거 환경은?", options: ["깊고 차가운 바다", "따뜻하고 얕은 바다", "깊은 산속", "강 하구"], answer: "따뜻하고 얕은 바다", isCalc: false },
  { id: 48, category: "지구과학", question: "지각 변동 중 판의 내부에서 마그마가 상승하여 화산 활동이 일어나는 곳은?", options: ["열점", "해령", "해구", "변환 단층"], answer: "열점", isCalc: false },
  { id: 49, category: "지구과학", question: "히말라야 산맥은 어떤 판의 경계에서 만들어졌는가?", options: ["발산형 경계", "대륙-대륙 수렴형 경계", "보존형 경계", "해양-해양 수렴형 경계"], answer: "대륙-대륙 수렴형 경계", isCalc: false },
  { id: 50, category: "지구과학", question: "지질 시대 중 가장 긴 시간을 차지하는 시기는?", options: ["고생대", "중생대", "신생대", "선캄브리아 시대"], answer: "선캄브리아 시대", isCalc: true }
];export const earthScience_Part2 = [
  { id: 51, category: "지구과학", question: "대기권 중 고도가 높아질수록 기온이 하강하며 기상 현상이 나타나는 층은?", options: ["대류권", "성층권", "중간권", "열권"], answer: "대류권", isCalc: false },
  { id: 52, category: "지구과학", question: "대기권 중 오존층이 존재하여 자외선을 흡수하는 층은?", options: ["대류권", "성층권", "중간권", "열권"], answer: "성층권", isCalc: false },
  { id: 53, category: "지구과학", question: "대기 중 가장 많은 부피를 차지하는 기체는?", options: ["산소", "이산화 탄소", "질소", "아르곤"], answer: "질소", isCalc: false },
  { id: 54, category: "지구과학", question: "태양 복사 에너지는 지구에 도달하고, 지구 복사 에너지는 대기에 흡수되어 지표 온도를 높이는 현상은?", options: ["지구 온난화", "온실 효과", "엘니뇨", "열섬 현상"], answer: "온실 효과", isCalc: false },
  { id: 55, category: "지구과학", question: "공기 속에 포함된 수증기의 양이 최대치에 도달한 상태를 무엇이라 하는가?", options: ["불포화 상태", "포화 상태", "과포화 상태", "이슬점"], answer: "포화 상태", isCalc: false },
  { id: 56, category: "지구과학", question: "수증기가 응결하기 시작하는 온도를 무엇이라 하는가?", options: ["끓는점", "어는점", "이슬점", "임계점"], answer: "이슬점", isCalc: false },
  { id: 57, category: "지구과학", question: "공기 덩어리가 상승하면서 단열 팽창하여 기온이 내려가는 현상은?", options: ["단열 변화", "복사 냉각", "전도", "대류"], answer: "단열 변화", isCalc: false },
  { id: 58, category: "지구과학", question: "구름 입자가 병합되거나 얼음 알갱이에 수증기가 달라붙어 무거워져 내리는 현상은?", options: ["안개", "비(강수)", "이슬", "서리"], answer: "비(강수)", isCalc: false },
  { id: 59, category: "지구과학", question: "바람은 기압이 ( ) 곳에서 ( ) 곳으로 분다. 빈칸 순서는?", options: ["높은, 낮은", "낮은, 높은", "중간인, 낮은", "일정한, 높은"], answer: "높은, 낮은", isCalc: false },
  { id: 60, category: "지구과학", question: "지구 자전에 의해 운동하는 물체의 방향이 휘어지는 가상의 힘은?", options: ["중력", "전향력(코리올리 힘)", "원심력", "마찰력"], answer: "전향력(코리올리 힘)", isCalc: false },
  { id: 61, category: "지구과학", question: "북반구 저기압에서는 바람이 어떤 방향으로 불어 들어오는가?", options: ["시계 방향", "반시계 방향", "직선 방향", "위쪽 방향"], answer: "반시계 방향", isCalc: false },
  { id: 62, category: "지구과학", question: "넓은 지역에 걸쳐 온도와 습도가 일정한 거대한 공기 덩어리는?", options: ["전선", "기단", "저기압", "태풍"], answer: "기단", isCalc: false },
  { id: 63, category: "지구과학", question: "우리나라의 초여름에 영서 지방에 높새바람을 일으키는 기단은?", options: ["시베리아 기단", "북태평양 기단", "오호츠크해 기단", "양쯔강 기단"], answer: "오호츠크해 기단", isCalc: false },
  { id: 64, category: "지구과학", question: "성질이 다른 두 기단이 만나 형성된 경계면이 지표와 만나는 선은?", options: ["기압선", "전선", "등온선", "해안선"], answer: "전선", isCalc: false },
  { id: 65, category: "지구과학", question: "찬 기단이 따뜻한 기단 밑으로 파고들며 형성되는 전선은?", options: ["온난 전선", "한랭 전선", "정체 전선", "폐색 전선"], answer: "한랭 전선", isCalc: false },
  { id: 66, category: "지구과학", question: "여름철 우리나라 부근에서 두 기단의 세력이 비슷하여 오래 머무는 전선은?", options: ["한랭 전선", "온난 전선", "정체 전선(장마 전선)", "폐색 전선"], answer: "정체 전선(장마 전선)", isCalc: false },
  { id: 67, category: "지구과학", question: "중위도 지역에서 서쪽에서 동쪽으로 부는 상층의 강한 바람은?", options: ["무역풍", "편서풍", "극동풍", "계절풍"], answer: "편서풍", isCalc: false },
  { id: 68, category: "지구과학", question: "열대 해상에서 발생하여 중위도로 이동하는 강한 저기압은?", options: ["태풍(열대 저기압)", "온대 저기압", "토네이도", "이동성 고기압"], answer: "태풍(열대 저기압)", isCalc: false },
  { id: 69, category: "지구과학", question: "해수의 성분 중 가장 많은 비중을 차지하는 염류는?", options: ["염화 마그네슘", "염화 나트륨", "황산 칼슘", "황산 마그네슘"], answer: "염화 나트륨", isCalc: false },
  { id: 70, category: "지구과학", question: "해수 1kg에 녹아 있는 염류의 총량을 g 단위로 나타낸 것은?", options: ["밀도", "염도(염분)", "농도", "비중"], answer: "염도(염분)", isCalc: false },
  { id: 71, category: "지구과학", question: "전 세계 바다에서 염류들 사이의 질량비는 일정하다는 법칙은?", options: ["염분 일정 성분비의 법칙", "질량 보존의 법칙", "에너지 보존의 법칙", "정비례의 법칙"], answer: "염분 일정 성분비의 법칙", isCalc: false },
  { id: 72, category: "지구과학", question: "해수 온도가 수심에 따라 급격히 낮아지는 층은?", options: ["혼합층", "수온 약층", "심해층", "해저층"], answer: "수온 약층", isCalc: false },
  { id: 73, category: "지구과학", question: "바람의 영향으로 해수의 온도가 일정하게 유지되는 표층 구간은?", options: ["혼합층", "수온 약층", "심해층", "열권"], answer: "혼합층", isCalc: false },
  { id: 74, category: "지구과학", question: "동태평양 적도 부근의 수온이 평상시보다 높아지는 현상은?", options: ["라니냐", "엘니뇨", "용승", "침강"], answer: "엘니뇨", isCalc: false },
  { id: 75, category: "지구과학", question: "달과 태양의 인력에 의해 해수면의 높이가 주기적으로 변하는 현상은?", options: ["조석", "해류", "파도", "쓰나미"], answer: "조석", isCalc: false },
  { id: 76, category: "지구과학", question: "해수면이 가장 높아졌을 때를 무엇이라 하는가?", options: ["간조", "만조", "사리", "조금"], answer: "만조", isCalc: false },
  { id: 77, category: "지구과학", question: "조차(만조와 간조의 차이)가 가장 크게 나타나는 시기는?", options: ["사리", "조금", "상현", "하현"], answer: "사리", isCalc: false },
  { id: 78, category: "지구과학", question: "별까지의 거리를 측정하는 방법으로, 지구가 궤도 양끝에 있을 때 별을 본 각도의 절반은?", options: ["연주 시차", "광도", "겉보기 등급", "절대 등급"], answer: "연주 시차", isCalc: false },
  { id: 79, category: "지구과학", question: "연주 시차가 1초(\")인 별까지의 거리를 무엇이라 하는가?", options: ["1광년", "1AU", "1파섹(pc)", "10pc"], answer: "1파섹(pc)", isCalc: true },
  { id: 80, category: "지구과학", question: "별의 밝기를 등급으로 나타낼 때, 숫자가 작을수록 밝기는?", options: ["밝다", "어둡다", "일정하다", "알 수 없다"], answer: "밝다", isCalc: false },
  { id: 81, category: "지구과학", question: "별을 모든 별을 10pc 거리에 두었다고 가정했을 때의 밝기 등급은?", options: ["겉보기 등급", "절대 등급", "실제 등급", "광도 등급"], answer: "절대 등급", isCalc: false },
  { id: 82, category: "지구과학", question: "별의 색깔이 붉은색일수록 표면 온도는 어떠한가?", options: ["높다", "낮다", "중간이다", "매우 높다"], answer: "낮다", isCalc: false },
  { id: 83, category: "지구과학", question: "우리 은하의 모양은?", options: ["타원 은하", "불규칙 은하", "막대 나선 은하", "정상 나선 은하"], answer: "막대 나선 은하", isCalc: false },
  { id: 84, category: "지구과학", question: "우주가 한 점(고온 고압)에서 폭발하여 시작되었다는 이론은?", options: ["정상 우주론", "빅뱅 우주론", "수축 우주론", "다중 우주론"], answer: "빅뱅 우주론", isCalc: false },
  { id: 85, category: "지구과학", question: "먼 은하일수록 우리로부터 더 빨리 멀어진다는 법칙은?", options: ["케플러 법칙", "허블 법칙", "뉴턴 법칙", "도플러 효과"], answer: "허블 법칙", isCalc: false },
  { id: 86, category: "지구과학", question: "태양계 행성 중 밀도가 가장 크고 크기가 작은 행성 집단은?", options: ["목성형 행성", "지구형 행성", "왜소 행성", "소행성"], answer: "지구형 행성", isCalc: false },
  { id: 87, category: "지구과학", question: "태양 표면에서 주변보다 온도가 낮아 검게 보이는 부분은?", options: ["쌀알 무늬", "흑점", "채층", "코로나"], answer: "흑점", isCalc: false },
  { id: 88, category: "지구과학", question: "태양 대기의 가장 바깥층으로 개기 일식 때 관측되는 고온의 층은?", options: ["채층", "광구", "코로나", "홍염"], answer: "코로나", isCalc: false },
  { id: 89, category: "지구과학", question: "달의 위상 변화 중 태양-달-지구 순으로 일직선이 되어 달이 안 보이는 때는?", options: ["삭", "망(보름달)", "상현", "하현"], answer: "삭", isCalc: false },
  { id: 90, category: "지구과학", question: "지구의 그림자에 달이 가려지는 현상은?", options: ["일식", "월식", "식현상", "통과"], answer: "월식", isCalc: false },
  { id: 91, category: "지구과학", question: "지각 평형설 중 산맥처럼 높은 곳은 뿌리가 깊다는 설은?", options: ["프래트설", "에어리설", "맨틀 대류설", "빙하설"], answer: "에어리설", isCalc: false },
  { id: 92, category: "지구과학", question: "암석 내부의 방사성 원소가 붕괴하여 처음 양의 절반이 되는 시간은?", options: ["반감기", "전성기", "냉각기", "수명"], answer: "반감기", isCalc: true },
  { id: 93, category: "지구과학", question: "지구 대기가 우주로 나가는 복사 에너지를 가두어 기온을 올리는 기체는?", options: ["온실 기체", "희귀 기체", "불활성 기체", "산소"], answer: "온실 기체", isCalc: false },
  { id: 94, category: "지구과학", question: "서안 경계류(쿠로시오 해류 등)의 특징은?", options: ["폭이 넓고 느리다", "폭이 좁고 빠르다", "수온이 낮다", "용존 산소가 많다"], answer: "폭이 좁고 빠르다", isCalc: false },
  { id: 95, category: "지구과학", question: "지구 자전축의 기울기는 약 몇 도인가?", options: ["0도", "23.5도", "45도", "90도"], answer: "23.5도", isCalc: true },
  { id: 96, category: "지구과학", question: "북반구에서 낮의 길이가 가장 긴 날은?", options: ["춘분", "하지", "추분", "동지"], answer: "하지", isCalc: false },
  { id: 97, category: "지구과학", question: "별의 일주 운동은 지구의 ( ) 때문에 나타나는 현상이다.", options: ["공전", "자전", "세차 운동", "개동"], answer: "자전", isCalc: false },
  { id: 98, category: "지구과학", question: "주계열성 단계의 별이 에너지를 생성하는 방식은?", options: ["수소 핵융합", "헬륨 핵융합", "중력 수축", "화학 반응"], answer: "수소 핵융합", isCalc: false },
  { id: 99, category: "지구과학", question: "태양 정도 질량의 별이 진화의 마지막 단계에서 형성하는 것은?", options: ["중성자별", "블랙홀", "백색 왜성", "적색 거성"], answer: "백색 왜성", isCalc: false },
  { id: 100, category: "지구과학", question: "질량이 매우 큰 별이 폭발하며 일생을 마감하는 현상은?", options: ["신성", "초신성 폭발", "성운 형성", "행성상 성운"], answer: "초신성 폭발", isCalc: false }
];export const earthScience_Part3 = [
  { id: 101, category: "지구과학", question: "지구 전체 구성 원소 중 가장 많은 질량을 차지하는 것은?", options: ["철", "산소", "규소", "마그네슘"], answer: "철", isCalc: false },
  { id: 102, category: "지구과학", question: "지각 전체 구성 원소 중 두 번째로 많은 원소는?", options: ["산소", "규소", "알루미늄", "철"], answer: "규소", isCalc: false },
  { id: 103, category: "지구과학", question: "암석이 풍화되어 식물이 자랄 수 있는 흙이 된 상태는?", options: ["기암", "토양", "퇴적물", "광물"], answer: "토양", isCalc: false },
  { id: 104, category: "지구과학", question: "지표면에서 물의 증발이나 얼음의 쐐기 작용에 의해 암석이 부서지는 풍화는?", options: ["화학적 풍화", "기계적 풍화", "생물학적 풍화", "열적 풍화"], answer: "기계적 풍화", isCalc: false },
  { id: 105, category: "지구과학", question: "석회동굴이 형성되는 것은 주로 어떤 풍화 작용의 결과인가?", options: ["기계적 풍화", "화학적 풍화", "빙하 작용", "바람 작용"], answer: "화학적 풍화", isCalc: false },
  { id: 106, category: "지구과학", question: "V자곡을 형성하는 주요 원인은?", options: ["바람", "지하수", "하천의 침식", "빙하"], answer: "하천의 침식", isCalc: false },
  { id: 107, category: "지구과학", question: "U자곡(빙식곡)을 형성하는 주요 원인은?", options: ["하천", "해수", "빙하", "바람"], answer: "빙하", isCalc: false },
  { id: 108, category: "지구과학", question: "강물이 바다와 만나는 곳에 퇴적물이 쌓여 만들어진 지형은?", options: ["선상지", "우각호", "삼각주", "곡류"], answer: "삼각주", isCalc: false },
  { id: 109, category: "지구과학", question: "해안가에서 파도의 침식 작용으로 만들어진 절벽은?", options: ["해식애", "해식 대지", "사주", "해안 사구"], answer: "해식애", isCalc: false },
  { id: 110, category: "지구과학", question: "바람에 날린 모래가 쌓여 만들어진 언덕은?", options: ["사구", "석호", "해식동", "파식대"], answer: "사구", isCalc: false },
  { id: 111, category: "지구과학", question: "지하수 속에 녹아있는 이산화 탄소가 석회암을 녹여 만든 지형은?", options: ["카르스트 지형", "빙하 지형", "건조 지형", "화산 지형"], answer: "카르스트 지형", isCalc: false },
  { id: 112, category: "지구과학", question: "대류권 상단과 성층권 하단 사이의 경계면은?", options: ["대류권 계면", "성층권 계면", "중간권 계면", "지표면"], answer: "대류권 계면", isCalc: false },
  { id: 113, category: "지구과학", question: "열권에서 전리된 입자들이 지자기장에 이끌려 빛을 내는 현상은?", options: ["오로라", "무지개", "유성", "노을"], answer: "오로라", isCalc: false },
  { id: 114, category: "지구과학", question: "지구의 알베도(반사율)는 약 몇 %인가?", options: ["10%", "30%", "50%", "70%"], answer: "30%", isCalc: true },
  { id: 115, category: "지구과학", question: "위도별 에너지 불균형을 해소하기 위해 에너지를 수송하는 두 주체는?", options: ["대기와 해수", "지각과 맨틀", "태양과 달", "구름과 비"], answer: "대기와 해수", isCalc: false },
  { id: 116, category: "지구과학", question: "공기 중의 수증기가 물방울로 변하는 온도를 무엇이라 하는가?", options: ["이슬점", "빙점", "어는점", "비등점"], answer: "이슬점", isCalc: false },
  { id: 117, category: "지구과학", question: "상승 기류가 강할 때 수직으로 높게 발달하는 구름은?", options: ["적운형 구름", "층운형 구름", "권운", "고층운"], answer: "적운형 구름", isCalc: false },
  { id: 118, category: "지구과학", question: "기압이 주변보다 낮아 공기가 모여들며 상승하는 곳은?", options: ["고기압", "저기압", "등압선", "정체 전선"], answer: "저기압", isCalc: false },
  { id: 119, category: "지구과학", question: "겨울철 우리나라 기상에 큰 영향을 주는 '서고동저'형 기압 배치를 만드는 기단은?", options: ["시베리아 기단", "북태평양 기단", "양쯔강 기단", "적도 기단"], answer: "시베리아 기단", isCalc: false },
  { id: 120, category: "지구과학", question: "대륙과 해양의 비열 차이로 인해 1년을 주기로 방향이 바뀌는 바람은?", options: ["해륙풍", "계절풍", "산곡풍", "높새바람"], answer: "계절풍", isCalc: false },
  { id: 121, category: "지구과학", question: "온대 저기압의 중심에서 남서쪽으로 뻗어 나오는 전선은?", options: ["온난 전선", "한랭 전선", "폐색 전선", "정체 전선"], answer: "한랭 전선", isCalc: false },
  { id: 122, category: "지구과학", question: "한랭 전선이 통과한 후의 기온 변화는?", options: ["높아진다", "낮아진다", "변함없다", "일정해진다"], answer: "낮아진다", isCalc: false },
  { id: 123, category: "지구과학", question: "태풍의 중심부로 바람이 약하고 맑은 구역은?", options: ["태풍의 눈", "위험 반원", "안전 반원", "열곡"], answer: "태풍의 눈", isCalc: false },
  { id: 124, category: "지구과학", question: "해수의 깊이를 측정하기 위해 음파를 쏘아 돌아오는 시간을 재는 방법은?", options: ["음향 측심법", "레이더 측정", "삼각 측량", "GPS"], answer: "음향 측심법", isCalc: true },
  { id: 125, category: "지구과학", question: "대륙 주변의 수심 200m 이내의 얕고 완만한 경사면은?", options: ["대륙붕", "대륙 사면", "대륙대", "심해저 평원"], answer: "대륙붕", isCalc: false },
  { id: 126, category: "지구과학", question: "해수 순환 중 수온과 염분(밀도) 차이에 의해 발생하는 심층 순환은?", options: ["풍성 순환", "열염 순환", "조석 순환", "표층 순환"], answer: "열염 순환", isCalc: false },
  { id: 127, category: "지구과학", question: "태양계에서 태양을 중심으로 행성이 타원 궤도로 돈다는 법칙은?", options: ["케플러 제1법칙", "케플러 제2법칙", "뉴턴의 법칙", "허블의 법칙"], answer: "케플러 제1법칙", isCalc: false },
  { id: 128, category: "지구과학", question: "망원경의 성능 중 두 물체를 구분할 수 있는 능력은?", options: ["배율", "분해능", "집광력", "시야"], answer: "분해능", isCalc: false },
  { id: 129, category: "지구과학", question: "태양의 광구에서 대류 현상 때문에 나타나는 쌀알 같은 무늬는?", options: ["흑점", "쌀알 무늬", "코로나", "홍염"], answer: "쌀알 무늬", isCalc: false },
  { id: 130, category: "지구과학", question: "별의 등급이 5등급 차이 나면 밝기는 몇 배 차이 나는가?", options: ["5배", "10배", "50배", "100배"], answer: "100배", isCalc: true },
  { id: 131, category: "지구과학", question: "H-R도에서 왼쪽 상단으로 갈수록 별의 특징은?", options: ["크고 차갑다", "작고 뜨겁다", "크고 뜨겁다", "작고 차갑다"], answer: "크고 뜨겁다", isCalc: false },
  { id: 132, category: "지구과학", question: "태양계 행성 중 고리가 가장 뚜렷하고 밀도가 물보다 작은 행성은?", options: ["목성", "토성", "천왕성", "해왕성"], answer: "토성", isCalc: false },
  { id: 133, category: "지구과학", question: "금성의 대기가 매우 뜨거운(약 470도) 주된 이유는?", options: ["태양과 가까워서", "이산화 탄소에 의한 온실 효과", "화산 활동", "자기장이 없어서"], answer: "이산화 탄소에 의한 온실 효과", isCalc: false },
  { id: 134, category: "지구과학", question: "화성에서 발견된 태양계 최대 규모의 화산 이름은?", options: ["올림푸스 산", "에베레스트", "한라산", "에트나 산"], answer: "올림푸스 산", isCalc: false },
  { id: 135, category: "지구과학", question: "달의 앞면과 뒷면이 항상 같은 이유는 자전 주기와 ( ) 주기가 같기 때문이다.", options: ["공전", "세차", "공전 궤도", "자전축"], answer: "공전", isCalc: false },
  { id: 136, category: "지구과학", question: "지각 변동 중 지층이 쌓이는 순서대로 시간의 흐름을 판단하는 법칙은?", options: ["지층 누중의 법칙", "동물군 천이의 법칙", "부정합의 법칙", "관입의 법칙"], answer: "지층 누중의 법칙", isCalc: false },
  { id: 137, category: "지구과학", question: "지구 내부 에너지의 근원은 무엇인가?", options: ["태양 에너지", "방사성 원소의 붕괴열", "조력 에너지", "풍력 에너지"], answer: "방사성 원소의 붕괴열", isCalc: false },
  { id: 138, category: "지구과학", question: "지진파의 속도가 불연속적으로 변하는 층을 발견하여 지구 내부를 구분한 방법은?", options: ["직접 시추", "화산 분출물 조사", "지진파 분석", "중력 측정"], answer: "지진파 분석", isCalc: false },
  { id: 139, category: "지구과학", question: "성층권의 오존 농도가 낮아지는 '오존홀'이 주로 나타나는 지역은?", options: ["적도", "중위도", "남극 상공", "유럽"], answer: "남극 상공", isCalc: false },
  { id: 140, category: "지구과학", question: "해안에서 육지 쪽으로 부는 바람인 '해풍'이 부는 시간대는?", options: ["낮", "밤", "새벽", "저녁"], answer: "낮", isCalc: false },
  { id: 141, category: "지구과학", question: "구름이 없는 맑은 날 밤에 지표면이 차갑게 식는 현상은?", options: ["복사 냉각", "단열 팽창", "기온 역전", "전도"], answer: "복사 냉각", isCalc: false },
  { id: 142, category: "지구과학", question: "바닷물이 수직으로 솟구쳐 올라오는 현상으로 좋은 어장을 형성하는 것은?", options: ["용승", "침강", "해류", "밀물"], answer: "용승", isCalc: false },
  { id: 143, category: "지구과학", question: "별의 절대 등급과 겉보기 등급을 비교하여 알 수 있는 정보는?", options: ["별의 온도", "별의 거리", "별의 크기", "별의 수명"], answer: "별의 거리", isCalc: true },
  { id: 144, category: "지구과학", question: "우리 은하 중심부에서 수천억 개의 별이 모여 있는 곳은?", options: ["은하핵", "나선팔", "헤일로", "성단"], answer: "은하핵", isCalc: false },
  { id: 145, category: "지구과학", question: "태양풍으로부터 지구를 보호해 주는 막은?", options: ["오존층", "자기권(밴앨런대)", "성층권", "대류권"], answer: "자기권(밴앨런대)", isCalc: false },
  { id: 146, category: "지구과학", question: "우리나라 황사 현상의 주요 발원지는?", options: ["남극", "북태평양", "몽골 및 중국 내륙", "일본"], answer: "몽골 및 중국 내륙", isCalc: false },
  { id: 147, category: "지구과학", question: "지구 공전 궤도면과 황도가 만나는 두 지점 중 해가 짧아지기 시작하는 시점은?", options: ["하지", "동지", "추분", "춘분"], answer: "추분", isCalc: false },
  { id: 148, category: "지구과학", question: "천구상에서 태양이 지나는 길을 무엇이라 하는가?", options: ["적도", "황도", "백도", "지평선"], answer: "황도", isCalc: false },
  { id: 149, category: "지구과학", question: "수치 예보 모델을 사용하여 날씨를 예측하는 현대의 방법은?", options: ["관천망기", "일기 예보", "기상 관측", "통계 분석"], answer: "일기 예보", isCalc: false },
  { id: 150, category: "지구과학", question: "지구 온난화로 인해 해수면이 상승하는 주된 원인 중 하나는 해수의 ( )이다.", options: ["증발", "열팽창", "밀도 증가", "결빙"], answer: "열팽창", isCalc: false }
];export const earthScience_Part4 = [
  { id: 151, category: "지구과학", question: "지각의 밀도 차이에 의해 지각이 맨틀 위에 떠 있다는 원리는?", options: ["지각 평형설", "판 구조론", "대륙 이동설", "해저 확장설"], answer: "지각 평형설", isCalc: false },
  { id: 152, category: "지구과학", question: "마그마의 냉각 속도가 매우 빨라 결정이 만들어지지 못한 암석의 조직은?", options: ["조립질", "세립질", "유리질", "반상 조직"], answer: "유리질", isCalc: false },
  { id: 153, category: "지구과학", question: "화강암질 마그마가 굳어서 형성된 대륙 지각의 주성분 암석은?", options: ["현무암", "화강암", "안산암", "반암"], answer: "화강암", isCalc: false },
  { id: 154, category: "지구과학", question: "퇴적암 중 자갈이 주성분인 암석은?", options: ["이암", "사암", "역암", "셰일"], answer: "역암", isCalc: false },
  { id: 155, category: "지구과학", question: "화석 중 지층이 쌓인 순서를 알려주는 것은?", options: ["표준 화석", "시상 화석", "미화석", "흔적 화석"], answer: "표준 화석", isCalc: false },
  { id: 156, category: "지구과학", question: "중생대의 바다를 대표하는 표준 화석은?", options: ["삼엽충", "암모나이트", "필석", "화폐석"], answer: "암모나이트", isCalc: false },
  { id: 157, category: "지구과학", question: "신생대를 대표하는 거대한 포유류 화석은?", options: ["공룡", "매머드", "삼엽충", "시조새"], answer: "매머드", isCalc: false },
  { id: 158, category: "지구과학", question: "지각 변동 중 지층이 수평으로 쌓인다는 법칙은?", options: ["수평 퇴적의 법칙", "지층 누중의 법칙", "관입의 법칙", "부정합의 법칙"], answer: "수평 퇴적의 법칙", isCalc: false },
  { id: 159, category: "지구과학", question: "심성암에서 마그마의 냉각 시 수축으로 인해 발생하는 기둥 모양의 틈은?", options: ["판상 절리", "주상 절리", "습곡", "단층"], answer: "주상 절리", isCalc: false },
  { id: 160, category: "지구과학", question: "해저 지형 중 수심이 가장 깊은 곳은?", options: ["해령", "해구", "해산", "대륙 사면"], answer: "해구", isCalc: false },
  { id: 161, category: "지구과학", question: "공기 중 수증기가 직접 얼음 알갱이로 변하는 현상은?", options: ["증발", "응결", "승화", "융해"], answer: "승화", isCalc: false },
  { id: 162, category: "지구과학", question: "안개 중 따뜻하고 습한 공기가 차가운 지표면 위로 이동할 때 생기는 안개는?", options: ["복사 안개", "이류 안개", "활승 안개", "증기 안개"], answer: "이류 안개", isCalc: false },
  { id: 163, category: "지구과학", question: "구름의 생성 과정 중 공기 덩어리가 산을 타고 오를 때 발생하는 것은?", options: ["지형성 강우", "전선성 강우", "대류성 강우", "태풍성 강우"], answer: "지형성 강우", isCalc: false },
  { id: 164, category: "지구과학", question: "상층 대기에서 기압 차이에 의해 등압선과 평행하게 부는 바람은?", options: ["지균풍", "경도풍", "지상풍", "곡풍"], answer: "지균풍", isCalc: false },
  { id: 165, category: "지구과학", question: "위도 0~30도 사이에서 부는 항상풍은?", options: ["무역풍", "편서풍", "극동풍", "계절풍"], answer: "무역풍", isCalc: false },
  { id: 166, category: "지구과학", question: "북반구 태풍의 이동 경로 중 오른쪽 부분으로 바람이 강한 곳은?", options: ["안전 반원", "위험 반원", "가항 반원", "정체 구역"], answer: "위험 반원", isCalc: false },
  { id: 167, category: "지구과학", question: "우리나라 주변 해류 중 난류의 근원이 되는 해류는?", options: ["쿠로시오 해류", "리만 해류", "북한 한류", "황해 난류"], answer: "쿠로시오 해류", isCalc: false },
  { id: 168, category: "지구과학", question: "해수의 염분이 낮아지는 요인이 아닌 것은?", options: ["강수량 증가", "빙하의 융해", "강물의 유입", "해수의 결빙"], answer: "해수의 결빙", isCalc: false },
  { id: 169, category: "지구과학", question: "태양계 행성 중 자전축이 거의 누운 채로 자전하는 행성은?", options: ["목성", "토성", "천왕성", "해왕성"], answer: "천왕성", isCalc: false },
  { id: 170, category: "지구과학", question: "태양계의 소행성들이 주로 모여 있는 궤도는 어느 행성들 사이인가?", options: ["지구와 화성", "화성과 목성", "목성과 토성", "금성과 지구"], answer: "화성과 목성", isCalc: false },
  { id: 171, category: "지구과학", question: "달의 지형 중 어둡고 평탄하게 보이는 부분은?", options: ["달의 바다", "달의 고지", "크레이터", "테라"], answer: "달의 바다", isCalc: false },
  { id: 172, category: "지구과학", question: "별의 시차를 측정하여 거리를 잴 수 있는 최대 한계 거리는 약 얼마인가?", options: ["10pc", "100pc", "1000pc", "10000pc"], answer: "100pc", isCalc: true },
  { id: 173, category: "지구과학", question: "우주 배경 복사를 예측하고 발견한 이론은?", options: ["빅뱅 우주론", "정상 우주론", "팽창 우주론", "정적 우주론"], answer: "빅뱅 우주론", isCalc: false },
  { id: 174, category: "지구과학", question: "별의 진화 과정 중 에너지가 고갈되어 팽창하며 표면 온도가 낮아진 단계는?", options: ["주계열성", "적색 거성", "백색 왜성", "성운"], answer: "적색 거성", isCalc: false },
  { id: 175, category: "지구과학", question: "지구 자전의 증거로 푸코가 사용한 도구는?", options: ["망원경", "진자", "해시계", "나침반"], answer: "진자", isCalc: false },
  { id: 176, category: "지구과학", question: "지표 부근의 공기가 냉각되어 수증기가 응결하여 떠 있는 현상은?", options: ["안개", "구름", "이슬", "서리"], answer: "안개", isCalc: false },
  { id: 177, category: "지구과학", question: "대기 중 이산화 탄소 농도가 가장 높게 관측되는 계절은?", options: ["봄", "여름", "가을", "겨울"], answer: "겨울", isCalc: false },
  { id: 178, category: "지구과학", question: "지각 내에서 마그마가 뚫고 들어가는 현상은?", options: ["분출", "관입", "침식", "풍화"], answer: "관입", isCalc: false },
  { id: 179, category: "지구과학", question: "변성암의 한 종류로 이질 암석이 높은 열을 받아 만들어진 것은?", options: ["호른펠스", "대리암", "규암", "편마암"], answer: "호른펠스", isCalc: false },
  { id: 180, category: "지구과학", question: "바닷물이 증발하여 형성된 퇴적암은?", options: ["암염", "석회암", "셰일", "사암"], answer: "암염", isCalc: false },
  { id: 181, category: "지구과학", question: "지구 내부 에너지 중 가장 큰 비중을 차지하는 것은?", options: ["조력", "지열(방사성 붕괴열)", "태양", "풍력"], answer: "지열(방사성 붕괴열)", isCalc: false },
  { id: 182, category: "지구과학", question: "지진파 중 전파 속도가 가장 느린 파는?", options: ["P파", "S파", "L파", "M파"], answer: "L파", isCalc: false },
  { id: 183, category: "지구과학", question: "지진의 진원과 진앙 사이의 수직 거리는?", options: ["진원 깊이", "진앙 거리", "진원 거리", "진앙 고도"], answer: "진원 깊이", isCalc: false },
  { id: 184, category: "지구과학", question: "두 대륙판이 충돌하여 거대한 산맥을 형성하는 예는?", options: ["안데스 산맥", "히말라야 산맥", "일본 열도", "산안드레아스 단층"], answer: "히말라야 산맥", isCalc: false },
  { id: 185, category: "지구과학", question: "해령의 열곡과 수직인 방향으로 발달하는 단층은?", options: ["정단층", "역단층", "변환 단층", "습곡 단층"], answer: "변환 단층", isCalc: false },
  { id: 186, category: "지구과학", question: "대기 대순환 중 적도 부근에서 상승하여 위도 30도에서 하강하는 순환은?", options: ["해들리 순환", "페렐 순환", "극 순환", "워커 순환"], answer: "해들리 순환", isCalc: false },
  { id: 187, category: "지구과학", question: "지구 온난화의 주요 원인인 기체는?", options: ["산소", "이산화 탄소", "아르곤", "헬륨"], answer: "이산화 탄소", isCalc: false },
  { id: 188, category: "지구과학", question: "해수가 빛을 흡수하여 깊이에 따라 수온이 낮아지는 현상은?", options: ["복사", "전도", "대류", "흡수"], answer: "복사", isCalc: false },
  { id: 189, category: "지구과학", question: "우리나라 동해안에 나타나는 찬 해류는?", options: ["북한 한류", "동한 난류", "쿠로시오 해류", "황해 난류"], answer: "북한 한류", isCalc: false },
  { id: 190, category: "지구과학", question: "천구의 적도와 황도가 만나는 두 점 중 해가 길어지기 시작하는 점은?", options: ["춘분점", "추분점", "하지점", "동지점"], answer: "춘분점", isCalc: false },
  { id: 191, category: "지구과학", question: "지구에서 관측할 때 행성이 배경 별자리 사이를 서에서 동으로 이동하는 현상은?", options: ["순행", "역행", "유", "충"], answer: "순행", isCalc: false },
  { id: 192, category: "지구과학", question: "외행성이 지구를 사이에 두고 태양의 반대편에 있을 때를 무엇이라 하는가?", options: ["합", "충", "구", "외합"], answer: "충", isCalc: false },
  { id: 193, category: "지구과학", question: "별의 스크럼 스펙트럼에서 검은색 선으로 나타나는 것은?", options: ["방출선", "흡수선", "연속 스펙트럼", "무지개"], answer: "흡수선", isCalc: false },
  { id: 194, category: "지구과학", question: "은하들이 서로 멀어지는 현상을 통해 알 수 있는 사실은?", options: ["우주 수축", "우주 팽창", "우주 정지", "우주 회전"], answer: "우주 팽창", isCalc: false },
  { id: 195, category: "지구과학", question: "태양의 중심부에서 에너지가 생성되는 반응은?", options: ["핵분열", "핵융합", "연소", "중력 수축"], answer: "핵융합", isCalc: false },
  { id: 196, category: "지구과학", question: "기압이 같은 지점을 연결한 선은?", options: ["등압선", "등온선", "등고선", "등심선"], answer: "등압선", isCalc: false },
  { id: 197, category: "지구과학", question: "바람의 세기가 가장 강한 곳은 등압선의 간격이 어떠할 때인가?", options: ["넓을 때", "좁을 때", "일정할 때", "없을 때"], answer: "좁을 때", isCalc: false },
  { id: 198, category: "지구과학", question: "지질 시대 중 원시 생명체가 처음 탄생한 시기는?", options: ["선캄브리아 시대", "고생대", "중생대", "신생대"], answer: "선캄브리아 시대", isCalc: false },
  { id: 199, category: "지구과학", question: "현재 우리가 살고 있는 지질 시대의 기(Period)는?", options: ["제4기", "백악기", "석탄기", "캄브리아기"], answer: "제4기", isCalc: false },
  { id: 200, category: "지구과학", question: "지구 대기 중 자외선을 차단해주는 층은?", options: ["오존층", "전리층", "대류권", "열권"], answer: "오존층", isCalc: false }
];export const earthScience_Part5 = [
  { id: 201, category: "지구과학", question: "지구 내부를 탐사하는 방법 중 가장 확실하지만 깊이의 한계가 있는 방법은?", options: ["지진파 분석", "직접 시추", "운석 연구", "중력 측정"], answer: "직접 시추", isCalc: false },
  { id: 202, category: "지구과학", question: "판을 이동시키는 근본적인 힘의 원천은?", options: ["맨틀 대류", "지구 자전", "달의 인력", "해류"], answer: "맨틀 대류", isCalc: false },
  { id: 203, category: "지구과학", question: "해령에서 멀어질수록 해저 퇴적물의 두께는 어떻게 되는가?", options: ["얇아진다", "두꺼워진다", "변함없다", "없어진다"], answer: "두꺼워진다", isCalc: true },
  { id: 204, category: "지구과학", question: "두 판이 충돌할 때 산맥이 생기는 현상을 무엇이라 하는가?", options: ["조산 운동", "조륙 운동", "풍화 작용", "침식 작용"], answer: "조산 운동", isCalc: false },
  { id: 205, category: "지구과학", question: "화석화 작용 중 생물의 형태가 암석에 찍혀 남은 구조는?", options: ["몰드", "캐스트", "치환", "탄화"], answer: "몰드", isCalc: false },
  { id: 206, category: "지구과학", question: "고생대 말에 대륙들이 하나로 뭉치며 발생한 생물 대멸종의 원인 중 하나는?", options: ["판게아 형성", "빙하기 종결", "산소 증가", "운석 충돌"], answer: "판게아 형성", isCalc: false },
  { id: 207, category: "지구과학", question: "암석의 절대 연령을 측정하기 위해 사용하는 원소는?", options: ["안정 원소", "방사성 동위 원소", "비활성 기체", "금속 원소"], answer: "방사성 동위 원소", isCalc: false },
  { id: 208, category: "지구과학", question: "지각의 변동을 일으키는 에너지원 중 태양 에너지가 관여하는 것은?", options: ["지진", "화산", "풍화와 침식", "판 이동"], answer: "풍화와 침식", isCalc: false },
  { id: 209, category: "지구과학", question: "우리나라 독도와 울릉도를 형성한 주요 암석은?", options: ["화강암", "현무암(화산암)", "석회암", "셰일"], answer: "현무암(화산암)", isCalc: false },
  { id: 210, category: "지구과학", question: "건조한 지역에서 물이 증발하여 지표면에 염분이 쌓이는 현상은?", options: ["염류화", "산성화", "부영양화", "용해"], answer: "염류화", isCalc: false },
  { id: 211, category: "지구과학", question: "대류권에서 위로 올라갈수록 기온이 내려가는 이유는 ( ) 에너지에서 멀어지기 때문이다.", options: ["태양 복사", "지구 복사", "잠열", "전도"], answer: "지구 복사", isCalc: false },
  { id: 212, category: "지구과학", question: "성층권에서 위로 올라갈수록 기온이 올라가는 주된 이유는?", options: ["자외선 흡수", "태양과 가까움", "온실 효과", "대류 현상"], answer: "자외선 흡수", isCalc: false },
  { id: 213, category: "지구과학", question: "공기 중의 실제 수증기량과 그 온도에서의 포화 수증기량의 비를 무엇이라 하는가?", options: ["절대 습도", "상대 습도", "이슬점", "혼합비"], answer: "상대 습도", isCalc: true },
  { id: 214, category: "지구과학", question: "맑은 날 상대 습도가 가장 낮은 시간대는?", options: ["해 뜰 무렵", "정오(12시)", "오후 2~3시", "한밤중"], answer: "오후 2~3시", isCalc: true },
  { id: 215, category: "지구과학", question: "높은 산을 넘어온 공기가 건조하고 뜨거워지는 현상은?", options: ["푄 현상(높새바람)", "엘니뇨", "라니냐", "해륙풍"], answer: "푄 현상(높새바람)", isCalc: false },
  { id: 216, category: "지구과학", question: "구름 입자가 형성될 때 응결을 돕는 작은 입자들은?", options: ["응결핵", "수증기", "물방울", "얼음"], answer: "응결핵", isCalc: false },
  { id: 217, category: "지구과학", question: "저기압 중심에서 공기가 상승하면 단열 냉각에 의해 ( )이 형성된다.", options: ["구름", "안개", "서리", "이슬"], answer: "구름", isCalc: false },
  { id: 218, category: "지구과학", question: "우리나라 봄철에 자주 발생하는 건조하고 따뜻한 기압은?", options: ["이동성 고기압", "정체성 고기압", "온대 저기압", "열대 저기압"], answer: "이동성 고기압", isCalc: false },
  { id: 219, category: "지구과학", question: "북반구에서 전향력은 물체의 운동 방향에 대해 어느 쪽으로 작용하는가?", options: ["왼쪽 90도", "오른쪽 90도", "반대 방향", "진행 방향"], answer: "오른쪽 90도", isCalc: false },
  { id: 220, category: "지구과학", question: "해수의 심층 순환을 일으키는 가장 큰 원인은?", options: ["바람", "수온과 염분의 밀도 차", "지구 자전", "달의 인력"], answer: "수온과 염분의 밀도 차", isCalc: false },
  { id: 221, category: "지구과학", question: "북태평양의 거대한 해류 순환 중 하나인 것은?", options: ["아열대 순환", "한대 순환", "적도 순환", "심해 순환"], answer: "아열대 순환", isCalc: false },
  { id: 222, category: "지구과학", question: "지구가 태양 주위를 공전하기 때문에 나타나는 별의 위치 변화는?", options: ["일주 운동", "연주 운동", "세차 운동", "자전 운동"], answer: "연주 운동", isCalc: false },
  { id: 223, category: "지구과학", question: "태양이 황도상에서 가장 남쪽에 위치할 때의 절기는?", options: ["하지", "동지", "춘분", "추분"], answer: "동지", isCalc: false },
  { id: 224, category: "지구과학", question: "관측자로부터 별까지의 거리가 2배 멀어지면 별의 밝기는 몇 배가 되는가?", options: ["1/2배", "1/4배", "2배", "4배"], answer: "1/4배", isCalc: true },
  { id: 225, category: "지구과학", question: "별의 온도를 결정하는 가장 중요한 색깔 지표는?", options: ["별의 크기", "별의 색깔", "별의 거리", "별의 질량"], answer: "별의 색깔", isCalc: false },
  { id: 226, category: "지구과학", question: "우리 은하의 지름은 약 얼마인가?", options: ["1,000광년", "10,000광년", "100,000광년", "1,000,000광년"], answer: "100,000광년", isCalc: true },
  { id: 227, category: "지구과학", question: "은하의 스펙트럼이 붉은색 쪽으로 치우치는 현상은?", options: ["청색 편이", "적색 편이", "도플러 효과 없음", "회절"], answer: "적색 편이", isCalc: false },
  { id: 228, category: "지구과학", question: "태양계 외곽에서 혜성의 고향으로 알려진 거대한 얼음 덩어리 집단은?", options: ["오르트 구름", "카이퍼 벨트", "소행성대", "나선팔"], answer: "오르트 구름", isCalc: false },
  { id: 229, category: "지구과학", question: "지구 대기 중 이산화 탄소를 흡수하여 저장하는 가장 큰 창고는?", options: ["삼림", "바다(해수)", "빙하", "토양"], answer: "바다(해수)", isCalc: false },
  { id: 230, category: "지구과학", question: "지구 복사 에너지 중 대기에 흡수되었다가 다시 지표로 돌아오는 복사는?", options: ["대기 역복사", "직접 복사", "우주 복사", "단파 복사"], answer: "대기 역복사", isCalc: false },
  { id: 231, category: "지구과학", question: "조력 에너지를 이용해 전기를 생산하는 발전 방식은?", options: ["조력 발전", "파력 발전", "풍력 발전", "지열 발전"], answer: "조력 발전", isCalc: false },
  { id: 232, category: "지구과학", question: "지각을 구성하는 암석의 순환 과정 중 풍화와 침식을 거치는 단계는?", options: ["퇴적물 형성", "마그마 형성", "변성 작용", "냉각"], answer: "퇴적물 형성", isCalc: false },
  { id: 233, category: "지구과학", question: "대륙 지각의 평균 두께는 약 얼마인가?", options: ["5km", "35km", "100km", "2900km"], answer: "35km", isCalc: true },
  { id: 234, category: "지구과학", question: "지구 내부에서 밀도가 가장 높은 구간은?", options: ["지각", "맨틀", "외핵", "내핵"], answer: "내핵", isCalc: false },
  { id: 235, category: "지구과학", question: "판의 경계 중 산안드레아스 단층과 같은 곳은?", options: ["발산형", "수렴형", "보존형", "충돌형"], answer: "보존형", isCalc: false },
  { id: 236, category: "지구과학", question: "해양판이 소멸되는 해구에서 발생하는 지진의 특징은?", options: ["천발 지진만 발생", "심발 지진까지 발생", "지진이 없음", "지표면에서만 발생"], answer: "심발 지진까지 발생", isCalc: false },
  { id: 237, category: "지구과학", question: "지하 깊은 곳에서 생성된 암석이 지표로 노출될 때 압력 감소로 갈라지는 것은?", options: ["판상 절리", "주상 절리", "단층", "정합"], answer: "판상 절리", isCalc: false },
  { id: 238, category: "지구과학", question: "암석 속에 포함된 철 성분이 산소와 반응하여 붉게 변하는 풍화는?", options: ["산화 작용", "용해 작용", "가수 분해", "쐐기 작용"], answer: "산화 작용", isCalc: false },
  { id: 239, category: "지구과학", question: "대기권 중 공기가 가장 희박하고 오로라가 나타나는 곳은?", options: ["열권", "중간권", "성층권", "대류권"], answer: "열권", isCalc: false },
  { id: 240, category: "지구과학", question: "지구의 기온 분포를 위도별로 결정하는 가장 큰 요인은?", options: ["태양 고도각", "해류의 흐름", "지표의 반사율", "구름의 양"], answer: "태양 고도각", isCalc: false },
  { id: 241, category: "지구과학", question: "포화 수증기량 곡선에서 현재 기온의 수증기량이 곡선 아래에 있으면?", options: ["불포화", "포화", "과포화", "이슬점"], answer: "불포화", isCalc: false },
  { id: 242, category: "지구과학", question: "구름 입자가 서로 충돌하여 커져서 비가 내린다는 이론은?", options: ["병합설", "빙정설", "단열설", "복사설"], answer: "병합설", isCalc: false },
  { id: 243, category: "지구과학", question: "우리나라에서 주로 여름철에 발생하는 집중 호우의 원인은?", options: ["강한 상승 기류와 적란운", "한랭 전선의 느린 이동", "이동성 고기압", "시베리아 기단"], answer: "강한 상승 기류와 적란운", isCalc: false },
  { id: 244, category: "지구과학", question: "태풍이 육지에 상륙하면 세력이 약해지는 주된 이유는?", options: ["수증기 공급 중단과 마찰", "기온 하강", "전향력 소실", "기압 상승"], answer: "수증기 공급 중단과 마찰", isCalc: false },
  { id: 245, category: "지구과학", question: "해수의 표층 온도가 가장 높은 위도 대는?", options: ["적도 부근", "위도 30도", "위도 60도", "극 지방"], answer: "적도 부근", isCalc: false },
  { id: 246, category: "지구과학", question: "망원경에서 빛을 모으는 능력을 무엇이라 하는가?", options: ["배율", "집광력", "분해능", "시야"], answer: "집광력", isCalc: false },
  { id: 247, category: "지구과학", question: "태양계 행성 중 가장 크기가 크고 줄무늬와 대적점이 있는 행성은?", options: ["목성", "토성", "천왕성", "해왕성"], answer: "목성", isCalc: false },
  { id: 248, category: "지구과학", question: "우주가 팽창함에 따라 은하 사이의 거리는 어떻게 되는가?", options: ["멀어진다", "가까워진다", "일정하다", "회전한다"], answer: "멀어진다", isCalc: false },
  { id: 249, category: "지구과학", question: "지구 환경 오염 중 산성비의 주된 원인 물질은?", options: ["질소 산화물과 황 산화물", "이산화 탄소", "메테인", "산소"], answer: "질소 산화물과 황 산화물", isCalc: false },
  { id: 250, category: "지구과학", question: "지구의 세차 운동 때문에 변하는 것은?", options: ["자전축의 방향", "공전 궤도 모양", "자전 속도", "지구의 크기"], answer: "자전축의 방향", isCalc: false }
];export const earthScience_Part6 = [
  { id: 251, category: "지구과학", question: "지각의 변동을 연구할 때 사용하는 지자기 줄무늬의 대칭적 배열은 무엇의 증거인가?", options: ["해저 확장설", "대륙 이동설", "수축설", "지각 평형설"], answer: "해저 확장설", isCalc: false },
  { id: 252, category: "지구과학", question: "하와이 열도의 화산들이 일렬로 배열된 이유는 판이 ( ) 위를 이동하기 때문이다.", options: ["열점", "해구", "해령", "변환 단층"], answer: "열점", isCalc: false },
  { id: 253, category: "지구과학", question: "변성암 중 편마암에서 나타나는 굵은 줄무늬 구조는?", options: ["편리", "편마 구조", "층리", "절리"], answer: "편마 구조", isCalc: false },
  { id: 254, category: "지구과학", question: "지층의 상대 연령을 결정하는 기본 법칙이 아닌 것은?", options: ["지층 누중의 법칙", "관입의 법칙", "질량 보존의 법칙", "동물군 천이의 법칙"], answer: "질량 보존의 법칙", isCalc: false },
  { id: 255, category: "지구과학", question: "지구상에 산소가 풍부해진 결정적인 계기는?", options: ["광합성 생물(남세균)의 출현", "화산 폭발", "빙하기", "오존층 파괴"], answer: "광합성 생물(남세균)의 출현", isCalc: false },
  { id: 256, category: "지구과학", question: "중생대 말 거대 생태계 멸종의 유력한 원인으로 꼽히는 것은?", options: ["운석 충돌", "홍수", "지진", "산소 고갈"], answer: "운석 충돌", isCalc: false },
  { id: 257, category: "지구과학", question: "대기 중 수증기가 응결할 때 주위로 방출하는 열 에너지는?", options: ["현열", "잠열(숨은열)", "복사열", "전도열"], answer: "잠열(숨은열)", isCalc: false },
  { id: 258, category: "지구과학", question: "이슬점과 기온이 같아지면 상대 습도는 몇 %인가?", options: ["0%", "50%", "100%", "200%"], answer: "100%", isCalc: true },
  { id: 259, category: "지구과학", question: "중위도 지역의 구름에서 눈이 만들어지는 원리를 설명하는 이론은?", options: ["빙정설", "병합설", "단열설", "냉각설"], answer: "빙정설", isCalc: false },
  { id: 260, category: "지구과학", question: "일기도에서 'H'는 무엇을 의미하는가?", options: ["고기압", "저기압", "습도", "폭염"], answer: "고기압", isCalc: false },
  { id: 261, category: "지구과학", question: "해안풍 중 밤에 육지에서 바다로 부는 바람은?", options: ["해풍", "육풍", "산풍", "곡풍"], answer: "육풍", isCalc: false },
  { id: 262, category: "지구과학", question: "엘니뇨 현상이 발생하면 무역풍의 세기는 어떻게 되는가?", options: ["강해진다", "약해진다", "일정하다", "없어진다"], answer: "약해진다", isCalc: false },
  { id: 263, category: "지구과학", question: "지구 자전축의 기울기가 커지면 계절 변화(여름과 겨울의 차이)는?", options: ["커진다", "작아진다", "변함없다", "없어진다"], answer: "커진다", isCalc: true },
  { id: 264, category: "지구과학", question: "태양계 행성 중 표면에 운석 구덩이가 많아 달과 가장 비슷해 보이는 행성은?", options: ["수성", "금성", "화성", "목성"], answer: "수성", isCalc: false },
  { id: 265, category: "지구과학", question: "별의 탄생 장소로 가스와 먼지가 밀집된 곳은?", options: ["블랙홀", "성운", "성단", "은하"], answer: "성운", isCalc: false },
  { id: 266, category: "지구과학", question: "질량이 태양보다 수십 배 큰 별의 마지막 진화 형태는?", options: ["백색 왜성", "블랙홀", "적색 왜성", "갈색 왜성"], answer: "블랙홀", isCalc: false },
  { id: 267, category: "지구과학", question: "지구에서 관측한 별의 연주 시차가 0.1초일 때 별까지의 거리는?", options: ["1pc", "10pc", "100pc", "0.1pc"], answer: "10pc", isCalc: true },
  { id: 268, category: "지구과학", question: "은하의 후퇴 속도는 거리에 비례한다는 상수 이름은?", options: ["허블 상수", "뉴턴 상수", "플랑크 상수", "중력 상수"], answer: "허블 상수", isCalc: false },
  { id: 269, category: "지구과학", question: "지구 온난화로 빙하가 녹으면 지구의 반사율(알베도)은 어떻게 되는가?", options: ["낮아진다", "높아진다", "일정하다", "0이 된다"], answer: "낮아진다", isCalc: false },
  { id: 270, category: "지구과학", question: "지표의 암석 중 석회암이 빗물에 녹아 만들어진 지형의 이름은?", options: ["카르스트", "구조 평야", "화산 지형", "빙하 지형"], answer: "카르스트", isCalc: false },
  { id: 271, category: "지구과학", question: "대륙 지각의 하부 경계인 모호면을 발견한 방법은?", options: ["지진파 속도 변화 분석", "시추", "열류량 측정", "암석 밀도 계산"], answer: "지진파 속도 변화 분석", isCalc: false },
  { id: 272, category: "지구과학", question: "판의 발산형 경계인 동아프리카 ( )는 대륙이 쪼개지는 곳이다.", options: ["해구", "열곡대", "습곡", "단층"], answer: "열곡대", isCalc: false },
  { id: 273, category: "지구과학", question: "화석화 과정 중 유기물이 탄소 성분만 남게 되는 작용은?", options: ["탄화 작용", "치환 작용", "재결정 작용", "용해 작용"], answer: "탄화 작용", isCalc: false },
  { id: 274, category: "지구과학", question: "고생대를 크게 6개의 기로 나눌 때 가장 먼저 시작되는 기는?", options: ["캄브리아기", "석탄기", "페름기", "데본기"], answer: "캄브리아기", isCalc: false },
  { id: 275, category: "지구과학", question: "암석 내부의 방사성 탄소(C-14)를 이용해 연대를 측정할 수 있는 최대 한계는 약 얼마인가?", options: ["5만 년", "5억 년", "50억 년", "100억 년"], answer: "5만 년", isCalc: true },
  { id: 276, category: "지구과학", question: "대기 중 산소 농도가 현재 수준에 도달하여 육상 생물이 출현한 시기는?", options: ["고생대", "중생대", "신생대", "선캄브리아"], answer: "고생대", isCalc: false },
  { id: 277, category: "지구과학", question: "구름의 높이가 2km 이하인 하층운에 속하는 구름은?", options: ["층운", "권운", "고층운", "권층운"], answer: "층운", isCalc: false },
  { id: 278, category: "지구과학", question: "공기 덩어리가 상승할 때 주위 기압이 낮아져 부피가 커지는 현상은?", options: ["단열 팽창", "단열 압축", "복사", "전도"], answer: "단열 팽창", isCalc: false },
  { id: 279, category: "지구과학", question: "기온 역전층이 형성되면 대기는 어떻게 되는가?", options: ["매우 안정된다", "불안정해진다", "대류가 활발해진다", "눈이 내린다"], answer: "매우 안정된다", isCalc: false },
  { id: 280, category: "지구과학", question: "우리나라의 장마철에 형성되는 기단 사이의 경계는?", options: ["정체 전선", "한랭 전선", "온난 전선", "폐색 전선"], answer: "정체 전선", isCalc: false },
  { id: 281, category: "지구과학", question: "태풍이 북상할 때 북반구에서 진행 방향의 왼쪽을 무엇이라 하는가?", options: ["안전 반원", "위험 반원", "강풍 구역", "눈"], answer: "안전 반원", isCalc: false },
  { id: 282, category: "지구과학", question: "해류 중 위도 30~60도 사이에서 편서풍의 영향으로 동쪽으로 흐르는 해류는?", options: ["북중도 해류", "북태평양 해류", "멕시코 만류", "쿠로시오 해류"], answer: "북태평양 해류", isCalc: false },
  { id: 283, category: "지구과학", question: "달의 인력에 의해 발생하는 지구의 자전축 흔들림은?", options: ["세차 운동", "장동 운동", "일주 운동", "공전 운동"], answer: "장동 운동", isCalc: false },
  { id: 284, category: "지구과학", question: "별의 겉보기 등급이 1등급인 별은 6등급인 별보다 몇 배 밝은가?", options: ["10배", "100배", "5배", "1000배"], answer: "100배", isCalc: true },
  { id: 285, category: "지구과학", question: "태양의 표면 활동이 활발할 때 지구에서 나타나는 무선 통신 장애 현상은?", options: ["델린저 현상", "오로라", "개기 일식", "홍염"], answer: "델린저 현상", isCalc: false },
  { id: 286, category: "지구과학", question: "우리 은하와 가장 가까운 거리에 있는 이웃 은하의 이름은?", options: ["안드로메다 은하", "마젤란 은하", "솜브레로 은하", "바람개비 은하"], answer: "안드로메다 은하", isCalc: false },
  { id: 287, category: "지구과학", question: "우주의 나이는 현재 약 몇 년으로 추정되는가?", options: ["46억 년", "138억 년", "200억 년", "1000억 년"], answer: "138억 년", isCalc: true },
  { id: 288, category: "지구과학", question: "지구 복사 에너지는 주로 어떤 파장대인가?", options: ["가시광선", "자외선", "적외선", "X선"], answer: "적외선", isCalc: false },
  { id: 289, category: "지구과학", question: "해수면 온도 상승으로 인해 발생하는 기상 이변 중 동태평양이 차가워지는 현상은?", options: ["라니냐", "엘니뇨", "태풍", "사막화"], answer: "라니냐", isCalc: false },
  { id: 290, category: "지구과학", question: "지구의 자기권에서 방사능 입자가 도넛 모양으로 갇혀 있는 구역은?", options: ["밴앨런대", "오존층", "전리층", "대류권 계면"], answer: "밴앨런대", isCalc: false },
  { id: 291, category: "지구과학", question: "화성암 중 규산 함량이 낮아 색이 어둡고 밀도가 큰 암석군은?", options: ["염기성암", "산성암", "중성암", "심성암"], answer: "염기성암", isCalc: false },
  { id: 292, category: "지구과학", question: "지각 변동 중 땅이 솟아오르는 현상을 무엇이라 하는가?", options: ["융기", "침강", "관입", "포획"], answer: "융기", isCalc: false },
  { id: 293, category: "지구과학", question: "공기 중의 수증기가 지표면 물체에 얼어붙은 것은?", options: ["서리", "이슬", "안개", "비"], answer: "서리", isCalc: false },
  { id: 294, category: "지구과학", question: "태풍의 에너지원은 무엇인가?", options: ["태양 직접열", "수증기의 응결 잠열", "지구 내부 에너지", "마찰열"], answer: "수증기의 응결 잠열", isCalc: false },
  { id: 295, category: "지구과학", question: "지하수의 수면 높이를 무엇이라 하는가?", options: ["지표면", "지하수면", "투수층", "불투수층"], answer: "지하수면", isCalc: false },
  { id: 296, category: "지구과학", question: "태양계 행성 중 가장 밀도가 낮은 행성은?", options: ["목성", "토성", "천왕성", "해왕성"], answer: "토성", isCalc: false },
  { id: 297, category: "지구과학", question: "별의 탄생 초기 단계로 아직 핵융합이 시작되지 않은 별은?", options: ["원시별", "주계열성", "거성", "왜성"], answer: "원시별", isCalc: false },
  { id: 298, category: "지구과학", question: "지구의 공전 궤도가 원에서 타원으로 변하는 주기를 연구한 이론은?", options: ["밀란코비치 주기", "빅뱅 이론", "판 구조론", "상대성 이론"], answer: "밀란코비치 주기", isCalc: false },
  { id: 299, category: "지구과학", question: "대기 오염 물질이 비구름에 섞여 내리는 현상을 통칭하는 말은?", options: ["습성 침적", "건성 침적", "확산", "희석"], answer: "습성 침적", isCalc: false },
  { id: 300, category: "지구과학", question: "지구 전체 시스템을 구성하는 5가지 권역이 아닌 것은?", options: ["기권", "수권", "지권", "우주권"], answer: "우주권", isCalc: false }
];