export const physics_Part1 = [
  { id: 1, category: "물리", question: "변위(Displacement)의 정의로 옳은 것은?", options: ["이동한 총 거리", "위치의 변화량", "속력과 시간의 곱", "가속도의 시간 변화율"], answer: "위치의 변화량", isCalc: false },
  { id: 2, category: "물리", question: "가속도가 0일 때 물체의 상태는?", options: ["정지 상태", "등속 직선 운동", "정지 또는 등속 직선 운동", "자유 낙하 운동"], answer: "정지 또는 등속 직선 운동", isCalc: false },
  { id: 3, category: "물리", question: "F=ma는 뉴턴의 운동 제몇 법칙인가?", options: ["제1법칙", "제2법칙", "제3법칙", "제4법칙"], answer: "제2법칙", isCalc: false },
  { id: 4, category: "물리", question: "작용-반작용 법칙의 예가 아닌 것은?", options: ["노를 저어 배가 나아감", "로켓의 발사", "벽을 밀면 나도 밀려남", "달리는 버스가 급정거 시 몸이 쏠림"], answer: "달리는 버스가 급정거 시 몸이 쏠림", isCalc: false },
  { id: 5, category: "물리", question: "중력 가속도 g의 대략적인 값은? (단위: m/s²)", options: ["1.6", "3.14", "9.8", "12"], answer: "9.8", isCalc: true },
  { id: 6, category: "물리", question: "운동 에너지 공식은?", options: ["mgh", "mv", "1/2 mv²", "F·s"], answer: "1/2 mv²", isCalc: false },
  { id: 7, category: "물리", question: "위치 에너지(중력) 공식은?", options: ["mgh", "mv", "1/2 mv²", "ma"], answer: "mgh", isCalc: false },
  { id: 8, category: "물리", question: "운동량(Momentum)의 정의는?", options: ["mv", "ma", "Ft", "1/2 mv²"], answer: "mv", isCalc: false },
  { id: 9, category: "물리", question: "충격량(Impulse)은 무엇의 변화량과 같은가?", options: ["가속도", "에너지", "운동량", "힘"], answer: "운동량", isCalc: false },
  { id: 10, category: "물리", question: "에너지 보존 법칙에 따라 고립계의 총 에너지는 변하지 않는다. (참/거짓)", options: ["참", "거짓"], answer: "참", isCalc: false },
  { id: 11, category: "물리", question: "마찰이 없는 평면에서 질량 2kg 물체에 10N의 힘을 가하면 가속도는?", options: ["2 m/s²", "5 m/s²", "10 m/s²", "20 m/s²"], answer: "5 m/s²", isCalc: true },
  { id: 12, category: "물리", question: "자유 낙하 하는 물체의 속력은 시간에 비례하여 증가한다. (참/거짓)", options: ["참", "거짓"], answer: "참", isCalc: false },
  { id: 13, category: "물리", question: "일(Work)의 단위로 옳은 것은?", options: ["Watt", "Newton", "Joule", "Pascal"], answer: "Joule", isCalc: false },
  { id: 14, category: "물리", question: "일률(Power)의 단위로 옳은 것은?", options: ["Watt", "Joule", "Newton", "Ampere"], answer: "Watt", isCalc: false },
  { id: 15, category: "물리", question: "탄성력의 크기가 변형된 길이에 비례한다는 법칙은?", options: ["옴의 법칙", "훅의 법칙", "파스칼의 법칙", "보일의 법칙"], answer: "훅의 법칙", isCalc: false },
  { id: 16, category: "물리", question: "회전 운동에서 힘에 대응하는 물리량은?", options: ["관성 모멘트", "각운동량", "토크(돌림힘)", "각속도"], answer: "토크(돌림힘)", isCalc: false },
  { id: 17, category: "물리", question: "물체가 원운동을 유지하게 하는 중심 방향의 힘은?", options: ["원심력", "구심력", "마찰력", "전향력"], answer: "구심력", isCalc: false },
  { id: 18, category: "물리", question: "케플러 제1법칙에 따르면 행성은 태양을 한 초점으로 하는 어떤 궤도를 도는가?", options: ["원", "타원", "포물선", "쌍곡선"], answer: "타원", isCalc: false },
  { id: 19, category: "물리", question: "만유인력의 크기는 거리의 제곱에 비례한다. (참/거짓)", options: ["참", "거짓"], answer: "거짓", isCalc: false },
  { id: 20, category: "물리", question: "밀도의 정의는?", options: ["무게/부피", "질량/부피", "부피/질량", "질량*부피"], answer: "질량/부피", isCalc: false },
  { id: 21, category: "물리", question: "액체나 기체 속 물체가 받는 상향 힘은?", options: ["부력", "중력", "장력", "응력"], answer: "부력", isCalc: false },
  { id: 22, category: "물리", question: "유체의 속력이 빨라지면 압력이 낮아진다는 원리는?", options: ["아르키메데스 원리", "파스칼 원리", "베르누이 원리", "렌츠의 법칙"], answer: "베르누이 원리", isCalc: false },
  { id: 23, category: "물리", question: "절대 온도의 단위는?", options: ["Celsius", "Fahrenheit", "Kelvin", "Rankine"], answer: "Kelvin", isCalc: false },
  { id: 24, category: "물리", question: "열역학 제0법칙은 무엇에 관한 법칙인가?", options: ["에너지 보존", "엔트로피 증가", "열평형", "절대 영도"], answer: "열평형", isCalc: false },
  { id: 25, category: "물리", question: "열역학 제1법칙은 에너지 보존 법칙의 일종이다. (참/거짓)", options: ["참", "거짓"], answer: "참", isCalc: false },
  { id: 26, category: "물리", question: "고립계에서 엔트로피는 항상 증가하거나 일정하다는 법칙은?", options: ["열역학 0법칙", "열역학 1법칙", "열역학 2법칙", "열역학 3법칙"], answer: "열역학 2법칙", isCalc: false },
  { id: 27, category: "물리", question: "비열이 클수록 같은 열량을 가했을 때 온도 변화가 작다. (참/거짓)", options: ["참", "거짓"], answer: "참", isCalc: false },
  { id: 28, category: "물리", question: "매질의 진동 방향과 파동의 진행 방향이 수직인 파동은?", options: ["종파", "횡파", "평면파", "구면파"], answer: "횡파", isCalc: false },
  { id: 29, category: "물리", question: "소리(음파)는 대표적인 종파이다. (참/거짓)", options: ["참", "거짓"], answer: "참", isCalc: false },
  { id: 30, category: "물리", question: "파동의 속력 v, 주파수 f, 파장 λ의 관계식은?", options: ["v = fλ", "v = f/λ", "v = λ/f", "v = f+λ"], answer: "v = fλ", isCalc: false },
  { id: 31, category: "물리", question: "빛의 굴절 현상이 일어나는 주된 원인은?", options: ["빛의 회절", "매질에 따른 속력 차이", "빛의 반사", "빛의 산란"], answer: "매질에 따른 속력 차이", isCalc: false },
  { id: 32, category: "물리", question: "볼록 렌즈는 빛을 모으는 성질이 있다. (참/거짓)", options: ["참", "거짓"], answer: "참", isCalc: false },
  { id: 33, category: "물리", question: "전하량의 단위는?", options: ["Volt", "Ampere", "Coulomb", "Ohm"], answer: "Coulomb", isCalc: false },
  { id: 34, category: "물리", question: "V = IR은 어떤 법칙인가?", options: ["쿨롱의 법칙", "옴의 법칙", "패러데이 법칙", "앙페르 법칙"], answer: "옴의 법칙", isCalc: false },
  { id: 35, category: "물리", question: "저항을 직렬로 연결하면 전체 저항값은 증가한다. (참/거짓)", options: ["참", "거짓"], answer: "참", isCalc: false },
  { id: 36, category: "물리", question: "전기 에너지의 단위가 아닌 것은?", options: ["Joule", "Wh", "cal", "Watt"], answer: "Watt", isCalc: false },
  { id: 37, category: "물리", question: "자기장의 방향을 결정하는 법칙은?", options: ["오른나사 법칙", "플레밍의 왼손 법칙", "렌츠의 법칙", "가우스 법칙"], answer: "오른나사 법칙", isCalc: false },
  { id: 38, category: "물리", question: "유도 기전력의 방향은 자속의 변화를 방해하는 방향이라는 법칙은?", options: ["앙페르 법칙", "렌츠의 법칙", "패러데이 법칙", "쿨롱의 법칙"], answer: "렌츠의 법칙", isCalc: false },
  { id: 40, category: "물리", question: "빛의 입자성을 보여주는 대표적인 현상은?", options: ["간섭", "회절", "광전 효과", "편광"], answer: "광전 효과", isCalc: false },
  { id: 41, category: "물리", question: "원자 핵을 구성하는 입자는?", options: ["전자와 양성자", "양성자와 중성자", "전자와 중성자", "양성자만"], answer: "양성자와 중성자", isCalc: false },
  { id: 42, category: "물리", question: "질량-에너지 등가 원리 공식은?", options: ["E=mc", "E=mc²", "E=1/2 mc²", "E=hf"], answer: "E=mc²", isCalc: false },
  { id: 43, category: "물리", question: "물질파(드브로이 파)의 파장은 운동량에 비례한다. (참/거짓)", options: ["참", "거짓"], answer: "거짓", isCalc: false },
  { id: 44, category: "물리", question: "반도체에서 p형 반도체의 주요 전하 운반자는?", options: ["전자", "양공", "이온", "중성자"], answer: "양공", isCalc: false },
  { id: 45, category: "물리", question: "전류의 열작용을 이용한 장치가 아닌 것은?", options: ["전기다리미", "헤어드라이어", "전기난로", "전동기"], answer: "전동기", isCalc: false },
  { id: 46, category: "물리", question: "소리의 3요소는 크기, 높낮이, 그리고 무엇인가?", options: ["속도", "맵시(음색)", "파장", "진동수"], answer: "맵시(음색)", isCalc: false },
  { id: 47, category: "물리", question: "거울에서 입사각과 반사각의 크기는 항상 같다. (참/거짓)", options: ["참", "거짓"], answer: "참", isCalc: false },
  { id: 48, category: "물리", question: "핵분열 시 발생하는 에너지는 질량 결손에 의한 것이다. (참/거짓)", options: ["참", "거짓"], answer: "참", isCalc: false },
  { id: 49, category: "물리", question: "자기 부상 열차에 활용되는 현상은?", options: ["초전도 현상", "광전 효과", "도플러 효과", "터널 효과"], answer: "초전도 현상", isCalc: false },
  { id: 50, category: "물리", question: "우주가 팽창하고 있음을 보여주는 빛의 현상은?", options: ["청색 편이", "적색 편이", "굴절", "전반사"], answer: "적색 편이", isCalc: false }
];export const physics_Part2 = [
  { id: 51, category: "물리", question: "관성(Inertia)의 크기를 결정하는 물체의 고유한 양은?", options: ["속도", "질량", "무게", "부피"], answer: "질량", isCalc: false },
  { id: 52, category: "물리", question: "수평으로 던진 물체의 수평 방향 운동 성분은?", options: ["등가속도 운동", "등속 직선 운동", "자유 낙하 운동", "원운동"], answer: "등속 직선 운동", isCalc: false },
  { id: 53, category: "물리", question: "운동량의 단위로 옳은 것은?", options: ["kg·m/s", "kg·m/s²", "N·m", "J·s"], answer: "kg·m/s", isCalc: false },
  { id: 54, category: "물리", question: "두 물체가 충돌할 때 외력이 없다면 총 운동량은 보존된다. (참/거짓)", options: ["참", "거짓"], answer: "참", isCalc: false },
  { id: 55, category: "물리", question: "반발 계수가 1인 충돌을 무엇이라 하는가?", options: ["완전 탄성 충돌", "비탄성 충돌", "완전 비탄성 충돌", "소성 충돌"], answer: "완전 탄성 충돌", isCalc: false },
  { id: 56, category: "물리", question: "질량 1kg의 물체가 10m 높이에 있을 때 중력 위치 에너지는? (g=10m/s²)", options: ["10J", "50J", "100J", "200J"], answer: "100J", isCalc: true },
  { id: 57, category: "물리", question: "일-에너지 정리에 따르면 알짜힘이 한 일은 무엇의 변화량과 같은가?", options: ["위치 에너지", "운동 에너지", "열 에너지", "탄성 에너지"], answer: "운동 에너지", isCalc: false },
  { id: 58, category: "물리", question: "마찰력의 방향은 항상 물체의 운동 방향과 반대이다. (참/거짓)", options: ["참", "거짓"], answer: "참", isCalc: false },
  { id: 59, category: "물리", question: "정지해 있는 물체에 작용하여 움직이기 직전까지 버티는 마찰력은?", options: ["운동 마찰력", "최대 정지 마찰력", "슬라이딩 마찰력", "유체 마찰력"], answer: "최대 정지 마찰력", isCalc: false },
  { id: 60, category: "물리", question: "단진자의 주기는 추의 질량에 비례한다. (참/거짓)", options: ["참", "거짓"], answer: "거짓", isCalc: false },
  { id: 61, category: "물리", question: "물체가 액체 속에서 받는 부력의 크기는 물체가 밀어낸 액체의 무게와 같다는 원리는?", options: ["파스칼의 원리", "아르키메데스의 원리", "베르누이의 원리", "연속의 방정식"], answer: "아르키메데스의 원리", isCalc: false },
  { id: 62, category: "물리", question: "밀폐된 용기 내 유체에 가해진 압력은 모든 방향으로 동일하게 전달된다는 원리는?", options: ["파스칼의 원리", "보일의 법칙", "샤를의 법칙", "토르첼리의 정리"], answer: "파스칼의 원리", isCalc: false },
  { id: 63, category: "물리", question: "이상 기체 상태 방정식은?", options: ["PV=nRT", "F=ma", "V=IR", "E=hf"], answer: "PV=nRT", isCalc: false },
  { id: 64, category: "물리", question: "온도가 일정할 때 기체의 압력과 부피는 반비례한다는 법칙은?", options: ["보일의 법칙", "샤를의 법칙", "아보가드로 법칙", "그레이엄 법칙"], answer: "보일의 법칙", isCalc: false },
  { id: 65, category: "물리", question: "압력이 일정할 때 기체의 부피는 절대 온도에 비례한다는 법칙은?", options: ["샤를의 법칙", "보일의 법칙", "기체 분자 운동론", "돌턴의 법칙"], answer: "샤를의 법칙", isCalc: false },
  { id: 66, category: "물리", question: "열의 이동 방식 중 매질 없이 전자기파의 형태로 직접 전달되는 방식은?", options: ["전도", "대류", "복사", "확산"], answer: "복사", isCalc: false },
  { id: 67, category: "물리", question: "고체 내부에서 입자의 충돌을 통해 열이 전달되는 방식은?", options: ["전도", "대류", "복사", "승화"], answer: "전도", isCalc: false },
  { id: 68, category: "물리", question: "전기장의 세기를 나타내는 단위는?", options: ["V/m", "C/m", "N/C", "V/m 또는 N/C"], answer: "V/m 또는 N/C", isCalc: false },
  { id: 69, category: "물리", question: "두 점전하 사이의 전기력은 거리의 제곱에 반비례한다는 법칙은?", options: ["가우스 법칙", "쿨롱의 법칙", "페러데이 법칙", "비오-사바르 법칙"], answer: "쿨롱의 법칙", isCalc: false },
  { id: 70, category: "물리", question: "전기 퍼텐셜(전위)의 단위는?", options: ["Joule", "Watt", "Volt", "Ampere"], answer: "Volt", isCalc: false },
  { id: 71, category: "물리", question: "축전기(Capacitor)가 전하를 저장하는 능력을 무엇이라 하는가?", options: ["저항", "유전율", "전기 용량", "인덕턴스"], answer: "전기 용량", isCalc: false },
  { id: 72, category: "물리", question: "전하의 흐름인 전류의 단위는?", options: ["Volt", "Ampere", "Ohm", "Coulomb"], answer: "Ampere", isCalc: false },
  { id: 73, category: "물리", question: "비저항이 매우 작아 전류가 잘 흐르는 물질을 무엇이라 하는가?", options: ["도체", "부도체", "반도체", "절연체"], answer: "도체", isCalc: false },
  { id: 74, category: "물리", question: "키르히호프의 전류 법칙(제1법칙)은 무엇의 보존을 의미하는가?", options: ["에너지 보존", "전하량 보존", "운동량 보존", "질량 보존"], answer: "전하량 보존", isCalc: false },
  { id: 75, category: "물리", question: "키르히호프의 전압 법칙(제2법칙)은 무엇의 보존을 의미하는가?", options: ["에너지 보존", "전하량 보존", "자기장 보존", "전류 보존"], answer: "에너지 보존", isCalc: false },
  { id: 76, category: "물리", question: "자기장의 단위(SI)는?", options: ["Weber", "Tesla", "Gauss", "Henry"], answer: "Tesla", isCalc: false },
  { id: 77, category: "물리", question: "전류가 흐르는 도선 주위에 자기장이 형성됨을 발견한 사람은?", options: ["외르스테드", "패러데이", "맥스웰", "헤르츠"], answer: "외르스테드", isCalc: false },
  { id: 78, category: "물리", question: "자기장 속에서 움직이는 전하가 받는 힘을 무엇이라 하는가?", options: ["전기력", "로런츠 힘", "강력", "약력"], answer: "로런츠 힘", isCalc: false },
  { id: 79, category: "물리", question: "변압기는 어떤 원리를 이용하여 전압을 바꾸는가?", options: ["자기 차폐", "전자기 유도", "열전 효과", "홀 효과"], answer: "전자기 유도", isCalc: false },
  { id: 80, category: "물리", question: "전자기파 중 파장이 가장 짧고 에너지가 가장 강한 것은?", options: ["적외선", "자외선", "X선", "감마선"], answer: "감마선", isCalc: false },
  { id: 81, category: "물리", question: "거울이나 렌즈에서 상의 크기와 물체의 크기 비율을 무엇이라 하는가?", options: ["배율", "굴절률", "초점 거리", "곡률 반지름"], answer: "배율", isCalc: false },
  { id: 82, category: "물리", question: "빛이 굴절률이 큰 매질에서 작은 매질로 갈 때 특정 각 이상에서 모두 반사되는 현상은?", options: ["난반사", "전반사", "정반사", "회절"], answer: "전반사", isCalc: false },
  { id: 83, category: "물리", question: "빛의 전반사 현상을 이용한 통신 매체는?", options: ["구리선", "동축 케이블", "광섬유", "마이크로파"], answer: "광섬유", isCalc: false },
  { id: 84, category: "물리", question: "파동이 장애물 뒤로 돌아 들어가는 현상을 무엇이라 하는가?", options: ["반사", "굴절", "회절", "간섭"], answer: "회절", isCalc: false },
  { id: 85, category: "물리", question: "두 파동이 만나 진폭이 커지거나 작아지는 현상을 무엇이라 하는가?", options: ["간섭", "산란", "분산", "편광"], answer: "간섭", isCalc: false },
  { id: 86, category: "물리", question: "영(Young)의 이중 슬릿 실험은 빛의 어떤 성질을 증명하는가?", options: ["입자성", "파동성", "직진성", "질량성"], answer: "파동성", isCalc: false },
  { id: 87, category: "물리", question: "파동의 진원지와 관찰자의 상대적 운동에 의해 진동수가 변하는 현상은?", options: ["도플러 효과", "광전 효과", "콤프턴 효과", "터널 효과"], answer: "도플러 효과", isCalc: false },
  { id: 88, category: "물리", question: "특수 상대성 이론의 두 가설은 상대성 원리와 무엇인가?", options: ["질량 보존 법칙", "광속 불변 원리", "가속도 법칙", "중첩 원리"], answer: "광속 불변 원리", isCalc: false },
  { id: 89, category: "물리", question: "빠르게 움직이는 물체의 시간은 정지한 관찰자가 볼 때 어떻게 되는가?", options: ["빠르게 간다", "느리게 간다(시간 지연)", "변화 없다", "멈춘다"], answer: "느리게 간다(시간 지연)", isCalc: false },
  { id: 90, category: "물리", question: "움직이는 관찰자가 측정하는 운동 방향의 물체 길이는 어떻게 보이는가?", options: ["길어진다", "짧아진다(길이 수축)", "변화 없다", "왜곡된다"], answer: "짧아진다(길이 수축)", isCalc: false },
  { id: 91, category: "물리", question: "광전 효과에서 금속 표면에서 전자를 떼어내기 위한 최소 에너지는?", options: ["일함수", "운동 에너지", "전위차", "이온화 에너지"], answer: "일함수", isCalc: false },
  { id: 92, category: "물리", question: "빛의 입자(에너지 양자)를 무엇이라 부르는가?", options: ["전자", "광자(Photon)", "양성자", "뉴트리노"], answer: "광자(Photon)", isCalc: false },
  { id: 93, category: "물리", question: "러더퍼드의 알파 입자 산란 실험으로 발견한 것은?", options: ["전자", "원자핵", "중성자", "쿼크"], answer: "원자핵", isCalc: false },
  { id: 94, category: "물리", question: "보어의 원자 모델에서 전자는 정해진 궤도에서만 회전한다. (참/거짓)", options: ["참", "거짓"], answer: "참", isCalc: false },
  { id: 95, category: "물리", question: "불확정성 원리를 제안하여 양자 역학의 기초를 닦은 과학자는?", options: ["아인슈타인", "하이젠베르크", "슈뢰딩거", "뉴턴"], answer: "하이젠베르크", isCalc: false },
  { id: 96, category: "물리", question: "수소 원자에서 전자가 높은 에너지 준위에서 낮은 준위로 떨어질 때 발생하는 것은?", options: ["전자 방출", "빛(광자) 방출", "중성자 방출", "질량 증가"], answer: "빛(광자) 방출", isCalc: false },
  { id: 97, category: "물리", question: "태양 에너지의 근원은 무엇인가?", options: ["핵분열", "핵융합", "화학 연소", "중력 붕괴"], answer: "핵융합", isCalc: false },
  { id: 98, category: "물리", question: "전류의 흐름을 한쪽 방향으로만 제한하는 반도체 소자는?", options: ["트랜지스터", "다이오드", "저항기", "축전기"], answer: "다이오드", isCalc: false },
  { id: 99, category: "물리", question: "신호를 증폭하거나 스위치 역할을 하는 반도체 소자는?", options: ["다이오드", "트랜지스터", "발전기", "코일"], answer: "트랜지스터", isCalc: false },
  { id: 100, category: "물리", question: "초전도체가 자기장을 밀어내어 자석 위에 떠오르는 현상은?", options: ["마이스너 효과", "제베크 효과", "펠티에 효과", "광전 효과"], answer: "마이스너 효과", isCalc: false }
];export const physics_Part3 = [
  { id: 101, category: "물리", question: "물체에 힘을 가했으나 물체가 이동하지 않았다면, 힘이 한 일의 양은?", options: ["최대", "힘의 크기와 같다", "0", "계산할 수 없다"], answer: "0", isCalc: true },
  { id: 102, category: "물리", question: "수직 항력이 물체의 운동 방향과 수직일 때, 수직 항력이 한 일은?", options: ["0", "양의 값", "음의 값", "무한대"], answer: "0", isCalc: false },
  { id: 103, category: "물리", question: "속력이 2배가 되면 운동 에너지는 몇 배가 되는가?", options: ["2배", "√2배", "4배", "8배"], answer: "4배", isCalc: true },
  { id: 104, category: "물리", question: "비보존력(예: 마찰력)이 작용하면 역학적 에너지는 보존되는가?", options: ["보존된다", "보존되지 않는다", "질량에 따라 다르다", "항상 증가한다"], answer: "보존되지 않는다", isCalc: false },
  { id: 105, category: "물리", question: "용수철 상수 k인 용수철을 x만큼 늘렸을 때 탄성 위치 에너지는?", options: ["kx", "1/2 kx", "kx²", "1/2 kx²"], answer: "1/2 kx²", isCalc: false },
  { id: 106, category: "물리", question: "완전 비탄성 충돌 후 두 물체는 어떻게 운동하는가?", options: ["서로 반대로 튕겨나간다", "한 덩어리가 되어 이동한다", "모두 정지한다", "속력이 더 빨라진다"], answer: "한 덩어리가 되어 이동한다", isCalc: false },
  { id: 107, category: "물리", question: "충돌 시간이 길어질수록 물체가 받는 평균 충격력은?", options: ["커진다", "작아진다", "변함없다", "0이 된다"], answer: "작아진다", isCalc: false },
  { id: 108, category: "물리", question: "액체 내 같은 깊이에서 모든 방향의 압력은 같다. (참/거짓)", options: ["참", "거짓"], answer: "참", isCalc: false },
  { id: 109, category: "물리", question: "표면 장력의 원인이 되는 분자 사이의 힘은?", options: ["척력", "응집력(인력)", "중력", "마찰력"], answer: "응집력(인력)", isCalc: false },
  { id: 110, category: "물리", question: "유체가 흐르는 관의 단면적이 좁아지면 유속은 어떻게 되는가?", options: ["느려진다", "빨라진다", "변함없다", "흐름이 멈춘다"], answer: "빨라진다", isCalc: false },
  { id: 111, category: "물리", question: "섭씨 0도는 절대 온도(K)로 약 얼마인가?", options: ["0 K", "100 K", "273 K", "373 K"], answer: "273 K", isCalc: true },
  { id: 112, category: "물리", question: "기체 분자의 평균 운동 에너지는 무엇에 비례하는가?", options: ["압력", "부피", "절대 온도", "밀도"], answer: "절대 온도", isCalc: false },
  { id: 113, category: "물리", question: "단열 팽창 시 기체의 온도는 어떻게 되는가?", options: ["올라간다", "내려간다", "일정하다", "0이 된다"], answer: "내려간다", isCalc: false },
  { id: 114, category: "물리", question: "열기관이 흡수한 열을 모두 일로 바꿀 수 있는가?", options: ["가능하다", "불가능하다"], answer: "불가능하다", isCalc: false },
  { id: 115, category: "물리", question: "가장 높은 효율을 가진 이상적인 열기관 사이클은?", options: ["오토 사이클", "카르노 사이클", "랭킨 사이클", "디젤 사이클"], answer: "카르노 사이클", isCalc: false },
  { id: 116, category: "물리", question: "전기력선의 밀도가 높을수록 전기장의 세기는?", options: ["약하다", "강하다", "0이다", "일정하다"], answer: "강하다", isCalc: false },
  { id: 117, category: "물리", question: "전위가 높은 곳에서 낮은 곳으로 흐르는 것은?", options: ["전자", "양전하(전류의 방향)", "중성자", "자기력선"], answer: "양전하(전류의 방향)", isCalc: false },
  { id: 118, category: "물리", question: "평행판 축전기의 간격이 좁아지면 전기 용량은?", options: ["감소한다", "증가한다", "변함없다", "0이 된다"], answer: "증가한다", isCalc: false },
  { id: 119, category: "물리", question: "전기 저항의 단위 '옴(Ω)'을 기본 단위로 풀면?", options: ["V/A", "A/V", "W/V", "J/C"], answer: "V/A", isCalc: true },
  { id: 120, category: "물리", question: "전하가 흐르는 도선 주위의 자기장 세기는 거리에 비례한다. (참/거짓)", options: ["참", "거짓"], answer: "거짓", isCalc: false },
  { id: 121, category: "물리", question: "강자성체의 예로 적절한 것은?", options: ["구리", "알루미늄", "철", "유리"], answer: "철", isCalc: false },
  { id: 122, category: "물리", question: "자기력선은 항상 N극에서 나와 S극으로 들어간다. (참/거짓)", options: ["참", "거짓"], answer: "참", isCalc: false },
  { id: 123, category: "물리", question: "솔레노이드 내부의 자기장은 거의 균일하다. (참/거짓)", options: ["참", "거짓"], answer: "참", isCalc: false },
  { id: 124, category: "물리", question: "전류가 흐르는 도선이 자기장 내에서 받는 힘의 방향은?", options: ["전류 방향", "자기장 방향", "전류와 자기장에 모두 수직", "전류와 평행"], answer: "전류와 자기장에 모두 수직", isCalc: false },
  { id: 125, category: "물리", question: "전동기(모터)는 전기 에너지를 무엇으로 바꾸는가?", options: ["열 에너지", "화학 에너지", "역학적 에너지", "빛 에너지"], answer: "역학적 에너지", isCalc: false },
  { id: 126, category: "물리", question: "전자기 유도 현상을 이용하여 전기를 생산하는 장치는?", options: ["전동기", "발전기", "축전기", "저항기"], answer: "발전기", isCalc: false },
  { id: 127, category: "물리", question: "패러데이 법칙에 따르면 유도 기전력은 자속의 변화율에 비례한다. (참/거짓)", options: ["참", "거짓"], answer: "참", isCalc: false },
  { id: 128, category: "물리", question: "가시광선 중 파장이 가장 긴 색깔은?", options: ["보라", "초록", "노랑", "빨강"], answer: "빨강", isCalc: false },
  { id: 129, category: "물리", question: "진공에서 모든 전자기파의 속력은 같다. (참/거짓)", options: ["참", "거짓"], answer: "참", isCalc: false },
  { id: 130, category: "물리", question: "소리의 속도는 기온이 높을수록 어떻게 되는가?", options: ["느려진다", "빨라진다", "변함없다", "0이 된다"], answer: "빨라진다", isCalc: false },
  { id: 131, category: "물리", question: "정상파에서 진동이 전혀 없는 부분을 무엇이라 하는가?", options: ["마루", "골", "배", "마디"], answer: "마디", isCalc: false },
  { id: 132, category: "물리", question: "빛의 분산 현상이 일어나는 도구의 대표적 예는?", options: ["평면 거울", "프리즘", "볼록 거울", "오목 렌즈"], answer: "프리즘", isCalc: false },
  { id: 133, category: "물리", question: "임계각보다 큰 각도로 입사할 때 발생하는 현상은?", options: ["전반사", "부분 반사", "산란", "회절"], answer: "전반사", isCalc: false },
  { id: 134, category: "물리", question: "멀어지는 구급차의 사이렌 소리가 낮게 들리는 현상은?", options: ["간섭", "공명", "도플러 효과", "굴절"], answer: "도플러 효과", isCalc: false },
  { id: 135, category: "물리", question: "물체의 진동수와 외부 힘의 진동수가 일치하여 진폭이 커지는 현상은?", options: ["회절", "공명", "편광", "반사"], answer: "공명", isCalc: false },
  { id: 136, category: "물리", question: "상대성 이론에 따르면 빛의 속도는 관찰자의 속도와 관계없이 일정하다. (참/거짓)", options: ["참", "거짓"], answer: "참", isCalc: false },
  { id: 137, category: "물리", question: "질량이 있는 물체는 빛의 속도에 도달할 수 있는가?", options: ["가능하다", "불가능하다"], answer: "불가능하다", isCalc: false },
  { id: 138, category: "물리", question: "일반 상대성 이론에서 중력은 무엇의 왜곡으로 설명되는가?", options: ["빛의 경로", "시공간", "물체의 질량", "전자기장"], answer: "시공간", isCalc: false },
  { id: 139, category: "물리", question: "빛의 이중성이란 무엇과 무엇의 성질을 모두 가짐을 뜻하는가?", options: ["질량과 에너지", "반사와 굴절", "입자와 파동", "전기와 자기"], answer: "입자와 파동", isCalc: false },
  { id: 140, category: "물리", question: "광전 효과 실험에서 빛의 세기가 세지면 튀어나오는 전자의 수는?", options: ["감소한다", "증가한다", "변함없다", "에너지만 커진다"], answer: "증가한다", isCalc: false },
  { id: 141, category: "물리", question: "드브로이 관계식에 따르면 입자의 파장은 무엇에 반비례하는가?", options: ["에너지", "속도", "운동량", "전하량"], answer: "운동량", isCalc: false },
  { id: 142, category: "물리", question: "전자가 원자핵 주위 특정 궤도에 존재한다는 모델을 제시한 학자는?", options: ["톰슨", "러더퍼드", "보어", "채드윅"], answer: "보어", isCalc: false },
  { id: 143, category: "물리", question: "원자핵에서 중성자를 발견한 과학자는?", options: ["뉴턴", "채드윅", "퀴리 부인", "밀리컨"], answer: "채드윅", isCalc: false },
  { id: 144, category: "물리", question: "강력(강한 핵력)은 어떤 입자들을 묶어주는 역할을 하는가?", options: ["전자와 양성자", "핵자(양성자와 중성자)", "원자와 원자", "분자와 분자"], answer: "핵자(양성자와 중성자)", isCalc: false },
  { id: 145, category: "물리", question: "질량 결손 Δm이 발생했을 때 방출되는 에너지 E는?", options: ["Δmc", "Δmc²", "1/2 Δmc²", "Δm/c"], answer: "Δmc²", isCalc: true },
  { id: 146, category: "물리", question: "p-n 접합 다이오드에서 전류가 흐르는 방향의 전압은?", options: ["순방향 전압", "역방향 전압", "교류 전압", "임계 전압"], answer: "순방향 전압", isCalc: false },
  { id: 147, category: "물리", question: "태양 전지는 어떤 원리를 이용하는가?", options: ["도플러 효과", "광전 효과", "열전 효과", "콤프턴 효과"], answer: "광전 효과", isCalc: false },
  { id: 148, category: "물리", question: "액정 디스플레이(LCD)에서 빛의 방향을 조절하는 성질은?", options: ["간섭", "회절", "편광", "분산"], answer: "편광", isCalc: false },
  { id: 149, category: "물리", question: "레이저(LASER) 광선의 특징이 아닌 것은?", options: ["단색성", "지향성", "간섭성", "사방으로 퍼짐"], answer: "사방으로 퍼짐", isCalc: false },
  { id: 150, category: "물리", question: "쿼크 3개가 모여 양성자를 이룰 때, 양성자의 전하량 합은?", options: ["0", "+1", "-1", "+2"], answer: "+1", isCalc: true }
];export const physics_Part4 = [
  { id: 151, category: "물리", question: "물체의 회전 상태를 변화시키는 물리량인 '돌림힘'의 다른 이름은?", options: ["관성", "토크(Torque)", "일률", "운동량"], answer: "토크(Torque)", isCalc: false },
  { id: 152, category: "물리", question: "지렛대 원리에서 힘점까지의 거리가 멀수록 작은 힘으로 큰 힘을 낼 수 있다. (참/거짓)", options: ["참", "거짓"], answer: "참", isCalc: false },
  { id: 153, category: "물리", question: "물체가 정적 평형 상태에 있기 위한 조건은 알짜힘이 0이고 ( )이 0이어야 한다. 빈칸은?", options: ["알짜 돌림힘", "운동 에너지", "가속도", "질량"], answer: "알짜 돌림힘", isCalc: false },
  { id: 154, category: "물리", question: "물체의 질량이 중심에 모여 있다고 간주할 수 있는 점을 무엇이라 하는가?", options: ["초점", "무게 중심", "접점", "변곡점"], answer: "무게 중심", isCalc: false },
  { id: 155, category: "물리", question: "단진동 운동을 하는 물체의 복원력은 변위 x에 어떻게 비례하는가?", options: ["x에 비례", "x의 제곱에 비례", "x에 반비례", "루트 x에 비례"], answer: "x에 비례", isCalc: false },
  { id: 156, category: "물리", question: "포물선 운동에서 공기 저항이 없을 때 최고점에서의 연직 방향 속도는?", options: ["최대", "0", "수평 속도와 같다", "알 수 없다"], answer: "0", isCalc: true },
  { id: 157, category: "물리", question: "인공위성이 지구 주위를 돌 수 있는 이유는 중력이 ( ) 역할을 하기 때문이다.", options: ["원심력", "구심력", "마찰력", "전기력"], answer: "구심력", isCalc: false },
  { id: 158, category: "물리", question: "탈출 속도는 행성의 질량이 클수록 어떻게 되는가?", options: ["작아진다", "커진다", "변함없다", "0이 된다"], answer: "커진다", isCalc: false },
  { id: 159, category: "물리", question: "점성(Viscosity)은 유체의 무엇을 나타내는 척도인가?", options: ["흐름에 대한 저항", "압축률", "밀도", "확산 속도"], answer: "흐름에 대한 저항", isCalc: false },
  { id: 160, category: "물리", question: "구형 물체가 액체 속에서 낙하할 때 속도에 비례하는 저항력을 받는다는 법칙은?", options: ["스토크스의 법칙", "뉴턴의 법칙", "파스칼의 법칙", "훅의 법칙"], answer: "스토크스의 법칙", isCalc: false },
  { id: 161, category: "물리", question: "열역학 과정 중 외부와 열 교환이 없는 과정을 무엇이라 하는가?", options: ["등압 과정", "등적 과정", "등온 과정", "단열 과정"], answer: "단열 과정", isCalc: false },
  { id: 162, category: "물리", question: "기체의 부피가 일정하게 유지되는 열역학 과정을 무엇이라 하는가?", options: ["등압 과정", "등적 과정", "단열 과정", "자유 팽창"], answer: "등적 과정", isCalc: false },
  { id: 163, category: "물리", question: "열기관의 열효율은 항상 1(100%)보다 작다. (참/거짓)", options: ["참", "거짓"], answer: "참", isCalc: false },
  { id: 164, category: "물리", question: "냉장고는 외부에서 일을 받아 열을 저온에서 고온으로 이동시킨다. (참/거짓)", options: ["참", "거짓"], answer: "참", isCalc: false },
  { id: 165, category: "물리", question: "자연계에서 비가역 현상은 항상 엔트로피가 감소하는 방향으로 일어난다. (참/거짓)", options: ["참", "거짓"], answer: "거짓", isCalc: false },
  { id: 166, category: "물리", question: "전기 용량의 단위 F(패럿)은 무엇의 약자인가?", options: ["Faraday", "Franklin", "Fermi", "Fourier"], answer: "Faraday", isCalc: false },
  { id: 167, category: "물리", question: "유전체(Dielectric)를 축전기 사이에 넣으면 전기 용량은 어떻게 되는가?", options: ["감소한다", "증가한다", "변함없다", "0이 된다"], answer: "증가한다", isCalc: false },
  { id: 168, category: "물리", question: "전류의 열작용에 의해 발생하는 열량을 무엇이라 하는가?", options: ["쿨롱 열", "줄 열(Joule heat)", "볼타 열", "암페어 열"], answer: "줄 열(Joule heat)", isCalc: false },
  { id: 169, category: "물리", question: "휘트스톤 브리지는 무엇을 정밀하게 측정하기 위한 장치인가?", options: ["전압", "전류", "미지의 저항", "전기 용량"], answer: "미지의 저항", isCalc: false },
  { id: 170, category: "물리", question: "자기장 속에서 도선이 받는 힘 F = BIl sinθ이다. θ가 몇 도일 때 힘이 최대인가?", options: ["0도", "45도", "90도", "180도"], answer: "90도", isCalc: true },
  { id: 171, category: "물리", question: "지구 자기장의 북극(S극 성질)은 지리상의 북극과 정확히 일치한다. (참/거짓)", options: ["참", "거짓"], answer: "거짓", isCalc: false },
  { id: 172, category: "물리", question: "자석을 반으로 자르면 N극과 S극을 분리할 수 있다. (참/거짓)", options: ["참", "거짓"], answer: "거짓", isCalc: false },
  { id: 173, category: "물리", question: "상자성체는 외부 자기장에 의해 같은 방향으로 약하게 자화된다. (참/거짓)", options: ["참", "거짓"], answer: "참", isCalc: false },
  { id: 174, category: "물리", question: "전자기 유도에서 코일의 감은 수가 많을수록 유도 기전력은 어떻게 되는가?", options: ["작아진다", "커진다", "변함없다", "0이 된다"], answer: "커진다", isCalc: false },
  { id: 175, category: "물리", question: "가정용 전기는 주로 직류(DC)인가 교류(AC)인가?", options: ["직류", "교류"], answer: "교류", isCalc: false },
  { id: 176, category: "물리", question: "교류 회로에서 전류의 흐름을 방해하는 총 저항 성분을 무엇이라 하는가?", options: ["임피던스", "리액턴스", "컨덕턴스", "어드미턴스"], answer: "임피던스", isCalc: false },
  { id: 177, category: "물리", question: "빛이 전자기파의 일종임을 이론적으로 예측하고 통합한 과학자는?", options: ["뉴턴", "맥스웰", "아인슈타인", "패러데이"], answer: "맥스웰", isCalc: false },
  { id: 178, category: "물리", question: "전자기파 파장 중 적외선보다 길고 라디오파보다 짧은 영역은?", options: ["가시광선", "자외선", "마이크로파", "X선"], answer: "마이크로파", isCalc: false },
  { id: 179, category: "물리", question: "렌즈의 굴절률이 주변 매질보다 클 때, 가운데가 두꺼운 렌즈는 빛을 어떻게 하는가?", options: ["발산시킨다", "수렴시킨다", "직진시킨다", "흡수한다"], answer: "수렴시킨다", isCalc: false },
  { id: 180, category: "물리", question: "비눗방울 표면에서 무지개색이 나타나는 원인은 빛의 ( ) 현상 때문이다.", options: ["굴절", "간섭", "회절", "분산"], answer: "간섭", isCalc: false },
  { id: 181, category: "물리", question: "단색광이 격자를 통과할 때 나타나는 무늬를 통해 빛의 무엇을 측정할 수 있는가?", options: ["입자의 크기", "빛의 파장", "빛의 질량", "빛의 전하"], answer: "빛의 파장", isCalc: true },
  { id: 182, category: "물리", question: "특수 상대성 이론에서 모든 관성계의 물리 법칙은 동일하게 적용된다. (참/거짓)", options: ["참", "거짓"], answer: "참", isCalc: false },
  { id: 183, category: "물리", question: "광전 효과에서 빛의 진동수가 ( )보다 낮으면 전자가 튀어나오지 않는다. 빈칸은?", options: ["문턱 진동수(한계 진동수)", "최대 진동수", "공명 진동수", "평균 진동수"], answer: "문턱 진동수(한계 진동수)", isCalc: false },
  { id: 184, category: "물리", question: "콤프턴 효과는 빛의 어떤 성질을 강력하게 뒷받침하는가?", options: ["파동성", "입자성", "회절성", "간섭성"], answer: "입자성", isCalc: false },
  { id: 185, category: "물리", question: "현대 물리학에서 입자의 위치와 운동량을 동시에 정확히 알 수 없다는 원리는?", options: ["베르누이 원리", "불확정성 원리", "배타 원리", "상대성 원리"], answer: "불확정성 원리", isCalc: false },
  { id: 186, category: "물리", question: "슈뢰딩거의 고양이 역설은 양자 역학의 어떤 상태를 설명하기 위한 것인가?", options: ["결정론적 상태", "중첩 상태", "입자 상태", "가속 상태"], answer: "중첩 상태", isCalc: false },
  { id: 187, category: "물리", question: "원자 내 전자가 가질 수 있는 에너지 값들이 불연속적인 것을 무엇이라 하는가?", options: ["에너지 양자화", "에너지 연속성", "에너지 보존", "에너지 증폭"], answer: "에너지 양자화", isCalc: false },
  { id: 188, category: "물리", question: "파울리 배타 원리에 따르면 한 양자 상태에 동일한 페르미온이 몇 개까지 들어갈 수 있는가?", options: ["1개", "2개", "무제한", "0개"], answer: "1개", isCalc: false },
  { id: 189, category: "물리", question: "원자핵을 이루는 양성자와 중성자를 통칭하여 무엇이라 하는가?", options: ["전자", "핵자", "중간자", "렙톤"], answer: "핵자", isCalc: false },
  { id: 190, category: "물리", question: "베타 붕괴 과정에서 방출되는 아주 가벼운 중성 입자는?", options: ["광자", "중성미자(뉴트리노)", "중성자", "양전자"], answer: "중성미자(뉴트리노)", isCalc: false },
  { id: 191, category: "물리", question: "원자핵의 질량 합이 구성 핵자들의 개별 질량 합보다 작은 현상을 무엇이라 하는가?", options: ["질량 보존", "질량 결손", "질량 증가", "질량 역전"], answer: "질량 결손", isCalc: false },
  { id: 192, category: "물리", question: "핵발전소에서 중성자의 속도를 늦추기 위해 사용하는 물질은?", options: ["감속재", "제어봉", "냉각재", "연료봉"], answer: "감속재", isCalc: false },
  { id: 193, category: "물리", question: "핵분열 연쇄 반응을 조절하기 위해 중성자를 흡수하는 장치는?", options: ["제어봉", "터빈", "변압기", "가속기"], answer: "제어봉", isCalc: false },
  { id: 194, category: "물리", question: "표준 모형에서 물질을 구성하는 기본 입자가 아닌 것은?", options: ["쿼크", "렙톤", "매개 입자", "원자"], answer: "원자", isCalc: false },
  { id: 195, category: "물리", question: "양성자는 2개의 업 쿼크와 1개의 ( ) 쿼크로 구성된다. 빈칸은?", options: ["다운", "스트레인지", "참", "바텀"], answer: "다운", isCalc: false },
  { id: 196, category: "물리", question: "중력을 매개할 것으로 예상되는 가상의 입자는?", options: ["광자", "글루온", "중력자", "힉스 입자"], answer: "중력자", isCalc: false },
  { id: 197, category: "물리", question: "입자들에게 질량을 부여하는 역할을 하여 '신의 입자'라 불리는 것은?", options: ["힉스 보손", "W 보손", "Z 보손", "뮤온"], answer: "힉스 보손", isCalc: false },
  { id: 198, category: "물리", question: "우주 배경 복사는 어떤 사건의 증거로 여겨지는가?", options: ["블랙홀 탄생", "빅뱅(대폭발)", "은하 충돌", "초신성 폭발"], answer: "빅뱅(대폭발)", isCalc: false },
  { id: 199, category: "물리", question: "태양광 발전은 빛 에너지를 직접 전기에너지로 변환한다. (참/거짓)", options: ["참", "거짓"], answer: "참", isCalc: false },
  { id: 200, category: "물리", question: "전류가 흐르면 주위에 자기장이 생기는 현상을 발견한 시험은?", options: ["패러데이 시험", "외르스테드 시험", "밀리컨 기름방울 시험", "영의 실험"], answer: "외르스테드 시험", isCalc: false }
];export const physics_Part5 = [
  { id: 201, category: "물리", question: "물체의 속도가 일정할 때, 물체에 작용하는 알짜힘은 얼마인가?", options: ["일정하다", "0이다", "질량과 같다", "속도와 같다"], answer: "0이다", isCalc: true },
  { id: 202, category: "물리", question: "원운동 하는 물체에서 속도의 방향은 항상 궤도의 어느 방향인가?", options: ["중심 방향", "접선 방향", "바깥 방향", "법선 방향"], answer: "접선 방향", isCalc: false },
  { id: 203, category: "물리", question: "관성 좌표계에서만 성립하는 뉴턴의 법칙은?", options: ["제1법칙", "제2법칙", "제3법칙", "모든 법칙"], answer: "모든 법칙", isCalc: false },
  { id: 204, category: "물리", question: "가속되는 좌표계에서 관찰자가 느끼는 가상의 힘은?", options: ["마찰력", "중력", "관성력", "장력"], answer: "관성력", isCalc: false },
  { id: 205, category: "물리", question: "탄성 충돌에서 보존되는 양은 운동량과 무엇인가?", options: ["위치 에너지", "운동 에너지", "열 에너지", "충격량"], answer: "운동 에너지", isCalc: false },
  { id: 206, category: "물리", question: "물리학에서 '계(System)'의 외부에서 가해지는 힘을 무엇이라 하는가?", options: ["내력", "외력", "복원력", "기전력"], answer: "외력", isCalc: false },
  { id: 207, category: "물리", question: "중력 이외의 힘이 일을 하지 않을 때, 무엇이 일정하게 유지되는가?", options: ["운동량", "역학적 에너지", "속도", "가속도"], answer: "역학적 에너지", isCalc: false },
  { id: 208, category: "물리", question: "기압의 단위 중 '1기압'은 약 몇 hPa(헥토파스칼)인가?", options: ["760", "1013", "100", "500"], answer: "1013", isCalc: true },
  { id: 209, category: "물리", question: "유체의 흐름에서 소용돌이가 없는 매끄러운 흐름을 무엇이라 하는가?", options: ["난류", "층류", "대류", "와류"], answer: "층류", isCalc: false },
  { id: 210, category: "물리", question: "베르누이 방정식은 유체의 무엇에 대한 에너지 보존 법칙인가?", options: ["질량", "압력과 속도", "온도", "밀도"], answer: "압력과 속도", isCalc: false },
  { id: 211, category: "물리", question: "물질의 상태 변화 중 고체에서 기체로 직접 변하는 현상은?", options: ["융해", "응고", "승화", "기화"], answer: "승화", isCalc: false },
  { id: 212, category: "물리", question: "열역학 제1법칙 식 ΔU = Q - W에서 ΔU는 무엇의 변화량인가?", options: ["외부 에너지", "내부 에너지", "운동 에너지", "전위 에너지"], answer: "내부 에너지", isCalc: false },
  { id: 213, category: "물리", question: "이상 기체가 등온 팽창할 때, 기체가 흡수한 열량은 무엇과 같은가?", options: ["기체가 한 일", "내부 에너지 변화", "0", "압력 변화"], answer: "기체가 한 일", isCalc: false },
  { id: 214, category: "물리", question: "엔트로피를 '무질서도'로 정의한 통계역학의 대가는?", options: ["볼츠만", "맥스웰", "기브스", "플랑크"], answer: "볼츠만", isCalc: false },
  { id: 215, category: "물리", question: "절대 영도에 도달할 수 없다는 법칙은?", options: ["열역학 1법칙", "열역학 2법칙", "열역학 3법칙", "에너지 보존 법칙"], answer: "열역학 3법칙", isCalc: false },
  { id: 216, category: "물리", question: "전기 선속(Flux)과 전하량의 관계를 설명하는 법칙은?", options: ["가우스 법칙", "앙페르 법칙", "패러데이 법칙", "비오-사바르 법칙"], answer: "가우스 법칙", isCalc: false },
  { id: 217, category: "물리", question: "전위 V인 곳에 전하 q가 있을 때 가지는 전기 퍼텐셜 에너지는?", options: ["qV", "q/V", "V/q", "1/2 qV"], answer: "qV", isCalc: true },
  { id: 218, category: "물리", question: "축전기에 저장되는 에너지는 전하량 Q와 전압 V에 대해 어떻게 표현되는가?", options: ["QV", "1/2 QV", "Q/V", "V/Q"], answer: "1/2 QV", isCalc: false },
  { id: 219, category: "물리", question: "금속의 저항은 온도가 높아질수록 어떻게 변하는가?", options: ["감소한다", "증가한다", "변함없다", "0이 된다"], answer: "증가한다", isCalc: false },
  { id: 220, category: "물리", question: "전력(P)은 전압(V)과 전류(I)의 곱이다. (참/거짓)", options: ["참", "거짓"], answer: "참", isCalc: false },
  { id: 221, category: "물리", question: "자기장 B 내에서 전류 I가 흐르는 길이 L인 직선 도선이 받는 힘은?", options: ["BIL", "B/IL", "IL/B", "BI/L"], answer: "BIL", isCalc: false },
  { id: 222, category: "물리", question: "전류가 흐르는 원형 코일 중심의 자기장 방향은 무엇으로 결정하는가?", options: ["오른손 법칙", "왼손 법칙", "렌츠의 법칙", "비오의 법칙"], answer: "오른손 법칙", isCalc: false },
  { id: 223, category: "물리", question: "전자기 유도에서 유도 기전력의 크기를 결정하는 법칙은?", options: ["패러데이 법칙", "앙페르 법칙", "옴의 법칙", "쿨롱의 법칙"], answer: "패러데이 법칙", isCalc: false },
  { id: 224, category: "물리", question: "자기 다이폴 모멘트의 단위는?", options: ["A·m²", "N/C", "V·m", "Wb/m"], answer: "A·m²", isCalc: false },
  { id: 225, category: "물리", question: "자속(Magnetic Flux)의 SI 단위는?", options: ["Tesla", "Weber(Wb)", "Henry", "Farad"], answer: "Weber(Wb)", isCalc: false },
  { id: 226, category: "물리", question: "인덕터(코일)가 전류의 변화에 저항하는 성질을 무엇이라 하는가?", options: ["커패시턴스", "인덕턴스", "저항", "임피던스"], answer: "인덕턴스", isCalc: false },
  { id: 227, category: "물리", question: "빛의 속도 c는 전기 상수(ε₀)와 자기 상수(μ₀)의 곱의 제곱근의 역수와 같다. (참/거짓)", options: ["참", "거짓"], answer: "참", isCalc: false },
  { id: 228, category: "물리", question: "전자기파 중 살균 작용을 하며 피부 노화의 원인이 되는 것은?", options: ["적외선", "가시광선", "자외선", "마이크로파"], answer: "자외선", isCalc: false },
  { id: 229, category: "물리", question: "반사 법칙에서 입사광선, 반사광선, 법선은 모두 한 평면 위에 있다. (참/거짓)", options: ["참", "거짓"], answer: "참", isCalc: false },
  { id: 230, category: "물리", question: "빛의 굴절에서 n₁sinθ₁ = n₂sinθ₂는 어떤 법칙인가?", options: ["스넬의 법칙", "반사의 법칙", "브루스터의 법칙", "말뤼스의 법칙"], answer: "스넬의 법칙", isCalc: false },
  { id: 231, category: "물리", question: "두 파동의 위상차가 반파장의 홀수 배일 때 일어나는 간섭은?", options: ["보강 간섭", "상쇄 간섭", "회절 간섭", "굴절 간섭"], answer: "상쇄 간섭", isCalc: false },
  { id: 232, category: "물리", question: "편광판을 통과한 빛의 세기 변화를 설명하는 법칙은?", options: ["말뤼스의 법칙", "스넬의 법칙", "뉴턴의 법칙", "맥스웰 방정식"], answer: "말뤼스의 법칙", isCalc: false },
  { id: 233, category: "물리", question: "광통신에서 신호 감쇠를 최소화하기 위해 사용하는 현상은?", options: ["전반사", "산란", "간섭", "회절"], answer: "전반사", isCalc: false },
  { id: 234, category: "물리", question: "특수 상대성 이론의 시간 지연 효과는 일상 속도의 자동차에서도 뚜렷하게 관찰된다. (참/거짓)", options: ["참", "거짓"], answer: "거짓", isCalc: false },
  { id: 235, category: "물리", question: "정지 질량 에너지를 나타내는 공식은?", options: ["mc²", "1/2 mv²", "mgh", "hf"], answer: "mc²", isCalc: true },
  { id: 236, category: "물리", question: "광전 효과에서 방출되는 광전자의 최대 운동 에너지는 무엇에 비례하는가?", options: ["빛의 세기", "빛의 진동수", "빛의 파장", "금속의 질량"], answer: "빛의 진동수", isCalc: false },
  { id: 237, category: "물리", question: "빛의 진동수 f인 광자 한 개의 에너지는? (h는 플랑크 상수)", options: ["hf", "h/f", "f/h", "1/2 hf"], answer: "hf", isCalc: true },
  { id: 238, category: "물리", question: "전자와 같은 입자도 파동의 성질을 가진다는 가설을 세운 사람은?", options: ["드브로이", "슈뢰딩거", "보어", "아인슈타인"], answer: "드브로이", isCalc: false },
  { id: 239, category: "물리", question: "슈뢰딩거 방정식은 양자 역학에서 무엇의 시간 변화를 설명하는가?", options: ["입자의 위치", "파동 함수", "에너지", "운동량"], answer: "파동 함수", isCalc: false },
  { id: 240, category: "물리", question: "양자 역학에서 파동 함수의 절댓값 제곱은 무엇을 의미하는가?", options: ["입자의 에너지", "발견 확률 밀도", "입자의 속도", "입자의 질량"], answer: "발견 확률 밀도", isCalc: false },
  { id: 241, category: "물리", question: "터널 효과는 입자가 고전적으로 넘을 수 없는 장벽을 통과하는 현상이다. (참/거짓)", options: ["참", "거짓"], answer: "참", isCalc: false },
  { id: 242, category: "물리", question: "전자 구름 모델은 현대 원자 모형을 가장 잘 설명한다. (참/거짓)", options: ["참", "거짓"], answer: "참", isCalc: false },
  { id: 243, category: "물리", question: "중성자가 붕괴하여 양성자, 전자, 중성미자가 되는 과정은?", options: ["알파 붕괴", "베타 붕괴", "감마 붕괴", "핵융합"], answer: "베타 붕괴", isCalc: false },
  { id: 244, category: "물리", question: "핵결합 에너지가 가장 커서 가장 안정적인 원소는?", options: ["수소", "헬륨", "철", "우라늄"], answer: "철", isCalc: false },
  { id: 245, category: "물리", question: "별의 내부에서 가벼운 원자핵이 합쳐져 무거운 원자핵이 되는 반응은?", options: ["핵분열", "핵융합", "산화 반응", "연쇄 반응"], answer: "핵융합", isCalc: false },
  { id: 246, category: "물리", question: "가장 먼저 발견된 기본 입자는?", options: ["양성자", "중성자", "전자", "쿼크"], answer: "전자", isCalc: false },
  { id: 247, category: "물리", question: "강한 상호작용(강력)을 매개하는 입자는?", options: ["광자", "글루온", "W 보손", "중력자"], answer: "글루온", isCalc: false },
  { id: 248, category: "물리", question: "반입자는 대응하는 입자와 질량은 같고 ( )는 반대이다. 빈칸은?", options: ["전하", "스핀", "부피", "속도"], answer: "전하", isCalc: false },
  { id: 249, category: "물리", question: "입자와 반입자가 만나 빛을 내며 사라지는 현상을 무엇이라 하는가?", options: ["쌍소멸", "쌍생성", "산란", "회절"], answer: "쌍소멸", isCalc: false },
  { id: 250, category: "물리", question: "우주 전체 에너지의 약 70%를 차지하며 우주 팽창을 가속하는 힘은?", options: ["암흑 물질", "암흑 에너지", "중력", "강력"], answer: "암흑 에너지", isCalc: false }
];export const physics_Part6 = [
  { id: 251, category: "물리", question: "강체의 회전 운동에서 질량에 대응하는 회전 관성을 무엇이라 하는가?", options: ["관성 모멘트", "각운동량", "토크", "회전 반경"], answer: "관성 모멘트", isCalc: false },
  { id: 252, category: "물리", question: "각운동량 보존 법칙에 따라 회전 반경이 줄어들면 각속도는 어떻게 되는가?", options: ["줄어든다", "커진다", "변함없다", "0이 된다"], answer: "커진다", isCalc: false },
  { id: 253, category: "물리", question: "지구의 자전으로 인해 북반구에서 운동하는 물체가 오른쪽으로 휘어지는 힘은?", options: ["원심력", "전향력(코리올리 힘)", "마찰력", "만유인력"], answer: "전향력(코리올리 힘)", isCalc: false },
  { id: 254, category: "물리", question: "베르누이 정리는 에너지 보존 법칙을 유체에 적용한 것이다. (참/거짓)", options: ["참", "거짓"], answer: "참", isCalc: false },
  { id: 255, category: "물리", question: "이상 기체에서 정압 비열(Cp)과 정적 비열(Cv) 중 더 큰 값은?", options: ["Cp", "Cv", "항상 같다", "분자량에 따라 다르다"], answer: "Cp", isCalc: false },
  { id: 256, category: "물리", question: "열역학적 가역 과정에서 엔트로피 변화량 ΔS는 얼마인가?", options: ["0", "양수", "음수", "무한대"], answer: "0", isCalc: false },
  { id: 257, category: "물리", question: "열기관이 한 순수 일(W)을 흡수한 열량(Q)으로 나눈 값은?", options: ["열효율", "성능 계수", "엔트로피", "내부 에너지"], answer: "열효율", isCalc: true },
  { id: 258, category: "물리", question: "맥스웰 방정식 중 자기 홀극(Magnetic Monopole)이 없음을 나타내는 법칙은?", options: ["가우스 자기 법칙", "가우스 전기 법칙", "패러데이 법칙", "앙페르-맥스웰 법칙"], answer: "가우스 자기 법칙", isCalc: false },
  { id: 259, category: "물리", question: "전자기파는 전계와 자계가 서로 수직으로 진동하며 전파되는 파동이다. (참/거짓)", options: ["참", "거짓"], answer: "참", isCalc: false },
  { id: 260, category: "물리", question: "빛의 속도 c를 넘어서는 정보 전달은 현대 물리학에서 가능한가?", options: ["가능하다", "불가능하다"], answer: "불가능하다", isCalc: false },
  { id: 261, category: "물리", question: "포인팅 벡터(Poynting vector)는 전자기파의 무엇을 나타내는가?", options: ["진동수", "에너지 흐름의 방향과 크기", "파장", "전하량"], answer: "에너지 흐름의 방향과 크기", isCalc: false },
  { id: 262, category: "물리", question: "매질의 굴절률 n은 항상 1보다 작을 수 있는가?", options: ["그렇다", "아니다 (일반적 매질 기준)"], answer: "아니다 (일반적 매질 기준)", isCalc: false },
  { id: 263, category: "물리", question: "빛이 비스듬히 입사할 때 반사광이 완전히 편광되는 각도를 무엇이라 하는가?", options: ["임계각", "브루스터 각", "굴절각", "입사각"], answer: "브루스터 각", isCalc: false },
  { id: 264, category: "물리", question: "망원경의 성능 중 두 점을 구분할 수 있는 능력을 무엇이라 하는가?", options: ["배율", "분해능", "집광력", "색수차"], answer: "분해능", isCalc: false },
  { id: 265, category: "물리", question: "도파관 내에서 전자기파가 전파될 때 특정 주파수 이하는 차단되는 현상이 있다. (참/거짓)", options: ["참", "거짓"], answer: "참", isCalc: false },
  { id: 266, category: "물리", question: "특수 상대성 이론에서 두 사건의 동시성은 관찰자의 운동 상태에 따라 달라진다. (참/거짓)", options: ["참", "거짓"], answer: "참", isCalc: false },
  { id: 267, category: "물리", question: "일반 상대성 이론의 증거 중 하나로, 태양 근처를 지나는 별빛이 굴절되는 현상은?", options: ["중력 렌즈 효과", "적색 편이", "도플러 효과", "광전 효과"], answer: "중력 렌즈 효과", isCalc: false },
  { id: 268, category: "물리", question: "블랙홀의 경계로, 빛조차 빠져나올 수 없는 지점을 무엇이라 하는가?", options: ["특이점", "사건의 지평선(Event Horizon)", "에르고 영역", "슈바르츠실트 반지름"], answer: "사건의 지평선(Event Horizon)", isCalc: false },
  { id: 269, category: "물리", question: "흑체 복사 실험 결과를 설명하기 위해 에너지 양자화 가설을 세운 과학자는?", options: ["아인슈타인", "플랑크", "보어", "맥스웰"], answer: "플랑크", isCalc: false },
  { id: 270, category: "물리", question: "광전 효과에서 빛의 세기가 증가하면 방출되는 광전자의 속도가 빨라진다. (참/거짓)", options: ["참", "거짓"], answer: "거짓", isCalc: false },
  { id: 271, category: "물리", question: "전자 회절 실험은 전자의 어떤 성질을 보여주는가?", options: ["입자성", "파동성", "질량성", "스핀성"], answer: "파동성", isCalc: false },
  { id: 272, category: "물리", question: "불확정성 원리에 따르면 에너지와 ( ) 사이에도 측정의 불확정성이 존재한다.", options: ["속도", "시간", "질량", "거리"], answer: "시간", isCalc: false },
  { id: 273, category: "물리", question: "슈뢰딩거의 파동 함수가 시간에 따라 변하지 않는 상태를 무엇이라 하는가?", options: ["정상 상태", "붕괴 상태", "가속 상태", "중첩 상태"], answer: "정상 상태", isCalc: false },
  { id: 274, category: "물리", question: "양자 역학에서 물리량의 측정값은 연산자의 ( )값으로 나타난다.", options: ["기댓값", "고윳값", "평균값", "최댓값"], answer: "고윳값", isCalc: false },
  { id: 275, category: "물리", question: "원자핵 주위 전자의 분포를 확률로 나타낸 함수를 무엇이라 하는가?", options: ["오비탈(Orbital)", "트랙", "궤도", "에너지 띠"], answer: "오비탈(Orbital)", isCalc: false },
  { id: 276, category: "물리", question: "서로 다른 원소들이 고유한 선 스펙트럼을 갖는 이유는 무엇의 차이 때문인가?", options: ["질량", "에너지 준위 구조", "원자 크기", "중성자 수"], answer: "에너지 준위 구조", isCalc: false },
  { id: 277, category: "물리", question: "고체의 에너지 띠 구조에서 원자가 띠와 전도 띠 사이의 간격을 무엇이라 하는가?", options: ["띠 간격(Band gap)", "페르미 준위", "자유 구멍", "절연 층"], answer: "띠 간격(Band gap)", isCalc: false },
  { id: 278, category: "물리", question: "자석 없이도 전기적 신호로 정보를 저장하는 플래시 메모리는 무엇을 이용하는가?", options: ["전자 터널링", "자기 유도", "열전 효과", "압전 효과"], answer: "전자 터널링", isCalc: false },
  { id: 279, category: "물리", question: "원자핵에서 질량수가 너무 큰 원소들이 주로 일으키는 붕괴는?", options: ["알파 붕괴", "베타 붕괴", "감마 붕괴", "핵융합"], answer: "알파 붕괴", isCalc: false },
  { id: 280, category: "물리", question: "방사성 원소의 양이 처음의 절반으로 줄어드는 데 걸리는 시간은?", options: ["반수명", "반감기", "평균 수명", "붕괴 상수"], answer: "반감기", isCalc: true },
  { id: 281, category: "물리", question: "핵융합 반응이 일어나기 위해 필요한 매우 높은 온도의 물질 상태는?", options: ["고체", "액체", "기체", "플라스마"], answer: "플라스마", isCalc: false },
  { id: 282, category: "물리", question: "빛의 속도에 가까운 입자를 충돌시켜 물질의 구조를 연구하는 장치는?", options: ["입자 가속기", "원자로", "변압기", "반사 망원경"], answer: "입자 가속기", isCalc: false },
  { id: 283, category: "물리", question: "표준 모형에서 전자기력을 매개하는 입자는?", options: ["광자", "글루온", "W 보손", "Z 보손"], answer: "광자", isCalc: false },
  { id: 284, category: "물리", question: "약한 상호작용(약력)을 매개하는 입자는 무엇인가?", options: ["W와 Z 보손", "광자", "글루온", "중력자"], answer: "W와 Z 보손", isCalc: false },
  { id: 285, category: "물리", question: "쿼크는 단독 입자로 존재할 수 있다. (참/거짓)", options: ["참", "거짓"], answer: "거짓", isCalc: false },
  { id: 286, category: "물리", question: "중성자는 1개의 업 쿼크와 2개의 ( ) 쿼크로 구성된다.", options: ["다운", "스트레인지", "참", "바텀"], answer: "다운", isCalc: false },
  { id: 287, category: "물리", question: "뮤온(Muon)은 렙톤(경입자) 가족에 속하는 입자이다. (참/거짓)", options: ["참", "거짓"], answer: "참", isCalc: false },
  { id: 288, category: "물리", question: "힉스 메커니즘은 입자들이 어떻게 ( )을 얻는지 설명한다.", options: ["전하", "질량", "스핀", "속도"], answer: "질량", isCalc: false },
  { id: 289, category: "물리", question: "허블 법칙에 따르면 은하의 후퇴 속도는 거리와 ( )한다.", options: ["비례", "반비례", "제곱 비례", "무관"], answer: "비례", isCalc: false },
  { id: 290, category: "물리", question: "우주 초기에 수소와 헬륨의 질량비가 약 3:1임은 빅뱅 이론의 증거다. (참/거짓)", options: ["참", "거짓"], answer: "참", isCalc: false },
  { id: 291, category: "물리", question: "빛이 중력에 의해 휘어지는 현상을 무엇이라 하는가?", options: ["중력 렌즈", "빛의 분산", "전반사", "광전 효과"], answer: "중력 렌즈", isCalc: false },
  { id: 292, category: "물리", question: "전하가 가속 운동을 할 때 발생하는 파동은?", options: ["음파", "전자기파", "물결파", "지진파"], answer: "전자기파", isCalc: false },
  { id: 293, category: "물리", question: "원자핵 안에서 양성자끼리 밀어내는 전기력을 이기고 묶어두는 힘은?", options: ["중력", "강한 핵력", "약한 핵력", "전기력"], answer: "강한 핵력", isCalc: false },
  { id: 294, category: "물리", question: "현대 물리학에서 시간과 공간은 절대적인 기준이 아니다. (참/거짓)", options: ["참", "거짓"], answer: "참", isCalc: false },
  { id: 295, category: "물리", question: "초전도체에서 전기 저항이 0이 되는 온도를 무엇이라 하는가?", options: ["임계 온도", "큐리 온도", "절대 온도", "전이 온도"], answer: "임계 온도", isCalc: false },
  { id: 296, category: "물리", question: "반도체에 불순물을 섞어 전기 전도성을 조절하는 과정을 무엇이라 하는가?", options: ["도핑", "합금", "이온화", "어닐링"], answer: "도핑", isCalc: false },
  { id: 297, category: "물리", question: "태양의 중심에서 일어나는 주된 반응은 수소 핵융합이다. (참/거짓)", options: ["참", "거짓"], answer: "참", isCalc: false },
  { id: 298, category: "물리", question: "우주가 가속 팽창하고 있음을 발견한 천체 관측 대상은?", options: ["태양", "블랙홀", "Ia형 초신성", "성운"], answer: "Ia형 초신성", isCalc: false },
  { id: 299, category: "물리", question: "입자의 파동성이 관찰되는 전자 현미경은 광학 현미경보다 분해능이 높다. (참/거짓)", options: ["참", "거짓"], answer: "참", isCalc: false },
  { id: 300, category: "물리", question: "물리학의 궁극적인 목표 중 하나인 네 가지 힘을 하나로 합치는 이론은?", options: ["모든 것의 이론(TOE)", "상대성 이론", "양자 역학", "열역학"], answer: "모든 것의 이론(TOE)", isCalc: false }
];  